In [2]:
import os
import time
import pandas as pd
import akshare as ak
import datetime
import warnings
import psycopg2
from datetime import timedelta, datetime
warnings.filterwarnings("ignore")
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('expand_frame_repr', False)
pd.set_option('display.unicode.ambiguous_as_wide', True)
pd.set_option('display.unicode.east_asian_width', True)

In [3]:
code_list = pd.read_csv('CodeList.csv')

In [8]:
def create_path(ak_code:str,Date:str):
    global path
    path = os.path.join(".","1min_DFCF")
    # save data
    if not os.path.exists(path) :
        # os.mkdir(path) 
        os.makedirs(path)  
    file_name = ak_code + ".csv"
    return os.path.join(path,file_name)

In [9]:
def check(ak_code:str,Date:str):
    path = os.path.join(".","1min_DFCF",ak_code)
    path = path+".csv"
    if os.path.isfile(path):
        return True
    return False

In [3]:
def GetMinuteID(x:str):
    dt = datetime.strptime(x, "%Y-%m-%d %H:%M:%S")
    result = int(dt.strftime("%Y%m%d%H%M"))
    return result

In [41]:
#stock_zh_a_hist_min_em_df = ak.stock_zh_a_hist_min_em(symbol="000001", start_date="2023-11-20 09:30:00", end_date="2023-11-20 15:00:00", period='1', adjust='')
#stock_zh_a_hist_min_em_df.rename(columns = {'时间':'Time','开盘':'Open','收盘':'Close','最高':'High','最低':'Low',
#                                                '成交量':'Volume','成交额':'Turnover','最新价':'Latest'},inplace = True)
#stock_zh_a_hist_min_em_df['Minute_ID'] = stock_zh_a_hist_min_em_df['Time'].apply(lambda x:GetMinuteID(x))
stock_zh_a_hist_min_em_df['FSM_ID'] = ak_code[2:]+stock_zh_a_hist_min_em_df['Minute_ID'].astype(str)
stock_zh_a_hist_min_em_df

                    Time  Open  Close   High    Low  Volume    Turnover  Latest     Minute_ID              FSM_ID
0    2023-11-20 09:30:00   0.0  10.15  10.15  10.15    7628   7742420.0  10.150  202311200930  830896202311200930
1    2023-11-20 09:31:00   0.0  10.14  10.18  10.14   17726  18002691.0  10.154  202311200931  830896202311200931
2    2023-11-20 09:32:00   0.0  10.15  10.16  10.14    7517   7624925.0  10.152  202311200932  830896202311200932
3    2023-11-20 09:33:00   0.0  10.13  10.15  10.13    6391   6480819.0  10.150  202311200933  830896202311200933
4    2023-11-20 09:34:00   0.0  10.14  10.14  10.13    5254   5323795.0  10.148  202311200934  830896202311200934
5    2023-11-20 09:35:00   0.0  10.13  10.14  10.13    4456   4514999.0  10.147  202311200935  830896202311200935
6    2023-11-20 09:36:00   0.0  10.13  10.14  10.12    7171   7265793.0  10.145  202311200936  830896202311200936
7    2023-11-20 09:37:00   0.0  10.12  10.13  10.12    3691   3737420.0  10.144  202311200937  830896202311200937
8    2023-11-20 09:38:00   0.0  10.12  10.13  10.12    5188   5252179.0  10.142  202311200938  830896202311200938
9    2023-11-20 09:39:00   0.0  10.14  10.14  10.12   11951  12099533.0  10.139  202311200939  830896202311200939
10   2023-11-20 09:40:00   0.0  10.13  10.14  10.13    2278   2308047.0  10.139  202311200940  830896202311200940
11   2023-11-20 09:41:00   0.0  10.13  10.14  10.13    5458   5529120.0  10.139  202311200941  830896202311200941
12   2023-11-20 09:42:00   0.0  10.14  10.14  10.13    1416   1434980.0  10.138  202311200942  830896202311200942
13   2023-11-20 09:43:00   0.0  10.13  10.14  10.13    2534   2567274.0  10.138  202311200943  830896202311200943
14   2023-11-20 09:44:00   0.0  10.14  10.14  10.13    5210   5277883.0  10.138  202311200944  830896202311200944
15   2023-11-20 09:45:00   0.0  10.14  10.14  10.13    1003   1016236.0  10.138  202311200945  830896202311200945
16   2023-11-20 09:46:00   0.0  10.14  10.14  10.13    1554   1574949.0  10.138  202311200946  830896202311200946
17   2023-11-20 09:47:00   0.0  10.13  10.14  10.13    1029   1042469.0  10.138  202311200947  830896202311200947
18   2023-11-20 09:48:00   0.0  10.13  10.14  10.13    1520   1540485.0  10.138  202311200948  830896202311200948
19   2023-11-20 09:49:00   0.0  10.14  10.14  10.13    1901   1926964.0  10.138  202311200949  830896202311200949
20   2023-11-20 09:50:00   0.0  10.14  10.14  10.13    2434   2467258.0  10.138  202311200950  830896202311200950
21   2023-11-20 09:51:00   0.0  10.12  10.14  10.12    7915   8016030.0  10.137  202311200951  830896202311200951
22   2023-11-20 09:52:00   0.0  10.13  10.13  10.12    8062   8160134.0  10.136  202311200952  830896202311200952
23   2023-11-20 09:53:00   0.0  10.12  10.13  10.12    4791   4849101.0  10.135  202311200953  830896202311200953
24   2023-11-20 09:54:00   0.0  10.12  10.13  10.12    3272   3311557.0  10.135  202311200954  830896202311200954
25   2023-11-20 09:55:00   0.0  10.13  10.13  10.12    2799   2832915.0  10.135  202311200955  830896202311200955
26   2023-11-20 09:56:00   0.0  10.13  10.13  10.12    2998   3035250.0  10.134  202311200956  830896202311200956
27   2023-11-20 09:57:00   0.0  10.12  10.13  10.12    2694   2726766.0  10.134  202311200957  830896202311200957
28   2023-11-20 09:58:00   0.0  10.12  10.13  10.12    1243   1258239.0  10.134  202311200958  830896202311200958
29   2023-11-20 09:59:00   0.0  10.13  10.13  10.12    2591   2622369.0  10.134  202311200959  830896202311200959
30   2023-11-20 10:00:00   0.0  10.12  10.13  10.11    5864   5933961.0  10.133  202311201000  830896202311201000
31   2023-11-20 10:01:00   0.0  10.11  10.12  10.11    5584   5646816.0  10.132  202311201001  830896202311201001
32   2023-11-20 10:02:00   0.0  10.11  10.12  10.11    4361   4409689.0  10.132  202311201002  830896202311201002
33   2023-11-20 10:03:00   0.0  10.10  10.11  10.10   11477  11603267.0  10.130  202311201003  830896202311201003
34   2023-11-20 10:04:00   0.0  10.10  10.11  10.10    5384   5441091.0  10.130  202311201004  830896202311201004
35   2023-11-20 10:05:00   0.0  10.11  10.12  10.10    4680   4730260.0  10.129  202311201005  830896202311201005
36   2023-11-20 10:06:00   0.0  10.12  10.12  10.10    2620   2648542.0  10.129  202311201006  830896202311201006
37   2023-11-20 10:07:00   0.0  10.11  10.12  10.11     694    701757.0  10.129  202311201007  830896202311201007
38   2023-11-20 10:08:00   0.0  10.11  10.12  10.11    1250   1264140.0  10.129  202311201008  830896202311201008
39   2023-11-20 10:09:00   0.0  10.11  10.12  10.11    1244   1258139.0  10.128  202311201009  830896202311201009
40   2023-11-20 10:10:00   0.0  10.13  10.13  10.11    5996   6067834.0  10.128  202311201010  830896202311201010
41   2023-11-20 10:11:00   0.0  10.13  10.13  10.12     805    814889.0  10.128  202311201011  830896202311201011
42   2023-11-20 10:12:00   0.0  10.12  10.13  10.12     904    915046.0  10.128  202311201012  830896202311201012
43   2023-11-20 10:13:00   0.0  10.13  10.13  10.12    3770   3815549.0  10.128  202311201013  830896202311201013
44   2023-11-20 10:14:00   0.0  10.12  10.13  10.11    1564   1582001.0  10.128  202311201014  830896202311201014
45   2023-11-20 10:15:00   0.0  10.12  10.12  10.11    1740   1760052.0  10.128  202311201015  830896202311201015
46   2023-11-20 10:16:00   0.0  10.11  10.12  10.11    1237   1251188.0  10.128  202311201016  830896202311201016
47   2023-11-20 10:17:00   0.0  10.12  10.12  10.11    1748   1768590.0  10.128  202311201017  830896202311201017
48   2023-11-20 10:18:00   0.0  10.11  10.12  10.11     782    791036.0  10.128  202311201018  830896202311201018
49   2023-11-20 10:19:00   0.0  10.11  10.12  10.11     956    967105.0  10.127  202311201019  830896202311201019
50   2023-11-20 10:20:00   0.0  10.12  10.12  10.11    1462   1478599.0  10.127  202311201020  830896202311201020
51   2023-11-20 10:21:00   0.0  10.12  10.12  10.11    1521   1538816.0  10.127  202311201021  830896202311201021
52   2023-11-20 10:22:00   0.0  10.13  10.13  10.11    7971   8065926.0  10.127  202311201022  830896202311201022
53   2023-11-20 10:23:00   0.0  10.12  10.13  10.12    1971   1994853.0  10.127  202311201023  830896202311201023
54   2023-11-20 10:24:00   0.0  10.12  10.13  10.12     796    805912.0  10.127  202311201024  830896202311201024
55   2023-11-20 10:25:00   0.0  10.13  10.14  10.12    7955   8057890.0  10.127  202311201025  830896202311201025
56   2023-11-20 10:26:00   0.0  10.14  10.14  10.13    1703   1725299.0  10.127  202311201026  830896202311201026
57   2023-11-20 10:27:00   0.0  10.13  10.14  10.13    2025   2052946.0  10.127  202311201027  830896202311201027
58   2023-11-20 10:28:00   0.0  10.15  10.15  10.13    3489   3537117.0  10.127  202311201028  830896202311201028
59   2023-11-20 10:29:00   0.0  10.15  10.15  10.14     769    780002.0  10.127  202311201029  830896202311201029
60   2023-11-20 10:30:00   0.0  10.15  10.15  10.14    1601   1623814.0  10.127  202311201030  830896202311201030
61   2023-11-20 10:31:00   0.0  10.14  10.15  10.14    1897   1924202.0  10.128  202311201031  830896202311201031
62   2023-11-20 10:32:00   0.0  10.14  10.15  10.14     616    624691.0  10.128  202311201032  830896202311201032
63   2023-11-20 10:33:00   0.0  10.14  10.15  10.13    1966   1993177.0  10.128  202311201033  830896202311201033
64   2023-11-20 10:34:00   0.0  10.14  10.15  10.13     826    837458.0  10.128  202311201034  830896202311201034
65   2023-11-20 10:35:00   0.0  10.15  10.15  10.14     681    690989.0  10.128  202311201035  830896202311201035
66   2023-11-20 10:36:00   0.0  10.14  10.15  10.14     428    434251.0  10.128  202311201036  830896202311201036
67   2023-11-20 10:37:00   0.0  10.16  10.16  10.14   12414  12603655.0  10.129  202311201037  830896202311201037
68   2023-11-20 10:38:00   0.0  10.17  10.17  10.15    4817   4894370.0  10.130  202311201038  830896202311201038
69   2023-11-20 10:39:00   0.0  10.16  10.17  10.16    4034   4100351.0  10.130  202311201039  830896202311201039
70   2023-11-20 10:40:00   0.0  10.17  10.17  10.16    1837   1866754.0  10.130  202311201040  830896202311201040
71   2023-11-20 10:41:00   0.0  10.15  10.17  10.15    2782   2827143.0  10.131  202311201041  830896202311201041
72   2023-11-20 10:42:00   0.0  10.16  10.16  10.15     833    845966.0  10.131  202311201042  830896202311201042
73   2023-11-20 10:43:00   0.0  10.16  10.16  10.15    3348   3401165.0  10.131  202311201043  830896202311201043
74   2023-11-20 10:44:00   0.0  10.17  10.17  10.16     758    770386.0  10.131  202311201044  830896202311201044
75   2023-11-20 10:45:00   0.0  10.17  10.17  10.16     959    975007.0  10.131  202311201045  830896202311201045
76   2023-11-20 10:46:00   0.0  10.16  10.17  10.16    3383   3437814.0  10.132  202311201046  830896202311201046
77   2023-11-20 10:47:00   0.0  10.16  10.16  10.15    1321   1341905.0  10.132  202311201047  830896202311201047
78   2023-11-20 10:48:00   0.0  10.15  10.16  10.15     595    604129.0  10.132  202311201048  830896202311201048
79   2023-11-20 10:49:00   0.0  10.16  10.16  10.15     740    751360.0  10.132  202311201049  830896202311201049
80   2023-11-20 10:50:00   0.0  10.15  10.16  10.15     651    660835.0  10.132  202311201050  830896202311201050
81   2023-11-20 10:51:00   0.0  10.16  10.16  10.15    2381   2418769.0  10.132  202311201051  830896202311201051
82   2023-11-20 10:52:00   0.0  10.16  10.16  10.15     922    936597.0  10.132  202311201052  830896202311201052
83   2023-11-20 10:53:00   0.0  10.16  10.16  10.15     873    886870.0  10.132  202311201053  830896202311201053
84   2023-11-20 10:54:00   0.0  10.15  10.16  10.15     498    505778.0  10.132  202311201054  830896202311201054
85   2023-11-20 10:55:00   0.0  10.16  10.16  10.15    2087   2120370.0  10.133  202311201055  830896202311201055
86   2023-11-20 10:56:00   0.0  10.16  10.16  10.15    3182   3232788.0  10.133  202311201056  830896202311201056
87   2023-11-20 10:57:00   0.0  10.17  10.17  10.16     818    831018.0  10.133  202311201057  830896202311201057
88   2023-11-20 10:58:00   0.0  10.17  10.17  10.16     435    442231.0  10.133  202311201058  830896202311201058
89   2023-11-20 10:59:00   0.0  10.16  10.17  10.16     666    677123.0  10.133  202311201059  830896202311201059
90   2023-11-20 11:00:00   0.0  10.16  10.17  10.16    1098   1115927.0  10.133  202311201100  830896202311201100
91   2023-11-20 11:01:00   0.0  10.17  10.17  10.16     581    590656.0  10.133  202311201101  830896202311201101
92   2023-11-20 11:02:00   0.0  10.16  10.17  10.16     547    555853.0  10.133  202311201102  830896202311201102
93   2023-11-20 11:03:00   0.0  10.16  10.17  10.16     911    925897.0  10.134  202311201103  830896202311201103
94   2023-11-20 11:04:00   0.0  10.16  10.17  10.16     868    882077.0  10.134  202311201104  830896202311201104
95   2023-11-20 11:05:00   0.0  10.17  10.17  10.16    2046   2080271.0  10.134  202311201105  830896202311201105
96   2023-11-20 11:06:00   0.0  10.16  10.17  10.16    2253   2290660.0  10.134  202311201106  830896202311201106
97   2023-11-20 11:07:00   0.0  10.17  10.17  10.16    1767   1795665.0  10.134  202311201107  830896202311201107
98   2023-11-20 11:08:00   0.0  10.16  10.17  10.16     558    567205.0  10.134  202311201108  830896202311201108
99   2023-11-20 11:09:00   0.0  10.16  10.17  10.16     644    654731.0  10.134  202311201109  830896202311201109
100  2023-11-20 11:10:00   0.0  10.17  10.17  10.16     733    745011.0  10.134  202311201110  830896202311201110
101  2023-11-20 11:11:00   0.0  10.17  10.18  10.16   13051  13276399.0  10.136  202311201111  830896202311201111
102  2023-11-20 11:12:00   0.0  10.18  10.19  10.17    5946   6052829.0  10.137  202311201112  830896202311201112
103  2023-11-20 11:13:00   0.0  10.19  10.19  10.18    2051   2089515.0  10.137  202311201113  830896202311201113
104  2023-11-20 11:14:00   0.0  10.18  10.19  10.18    7483   7624092.0  10.138  202311201114  830896202311201114
105  2023-11-20 11:15:00   0.0  10.20  10.20  10.18    4807   4897819.0  10.139  202311201115  830896202311201115
106  2023-11-20 11:16:00   0.0  10.20  10.21  10.19   13273  13537322.0  10.141  202311201116  830896202311201116
107  2023-11-20 11:17:00   0.0  10.19  10.20  10.19    3306   3371333.0  10.142  202311201117  830896202311201117
108  2023-11-20 11:18:00   0.0  10.20  10.20  10.19    4429   4516506.0  10.143  202311201118  830896202311201118
109  2023-11-20 11:19:00   0.0  10.20  10.20  10.19    4772   4867282.0  10.143  202311201119  830896202311201119
110  2023-11-20 11:20:00   0.0  10.21  10.22  10.20    8141   8311851.0  10.145  202311201120  830896202311201120
111  2023-11-20 11:21:00   0.0  10.21  10.22  10.20    4418   4511611.0  10.146  202311201121  830896202311201121
112  2023-11-20 11:22:00   0.0  10.22  10.22  10.20    4537   4633301.0  10.146  202311201122  830896202311201122
113  2023-11-20 11:23:00   0.0  10.21  10.22  10.21    4648   4749000.0  10.147  202311201123  830896202311201123
114  2023-11-20 11:24:00   0.0  10.20  10.22  10.20    3697   3774352.0  10.148  202311201124  830896202311201124
115  2023-11-20 11:25:00   0.0  10.20  10.21  10.20    1919   1958051.0  10.148  202311201125  830896202311201125
116  2023-11-20 11:26:00   0.0  10.20  10.21  10.20    1868   1906404.0  10.148  202311201126  830896202311201126
117  2023-11-20 11:27:00   0.0  10.20  10.21  10.20    1025   1045815.0  10.149  202311201127  830896202311201127
118  2023-11-20 11:28:00   0.0  10.20  10.21  10.20    1500   1530790.0  10.149  202311201128  830896202311201128
119  2023-11-20 11:29:00   0.0  10.20  10.21  10.20    1541   1572126.0  10.149  202311201129  830896202311201129
120  2023-11-20 11:30:00   0.0  10.20  10.21  10.20    1832   1869761.0  10.149  202311201130  830896202311201130
121  2023-11-20 13:01:00   0.0  10.21  10.21  10.20   13064  13333916.0  10.151  202311201301  830896202311201301
122  2023-11-20 13:02:00   0.0  10.20  10.21  10.20     936    955077.0  10.151  202311201302  830896202311201302
123  2023-11-20 13:03:00   0.0  10.20  10.21  10.20    4898   4996328.0  10.152  202311201303  830896202311201303
124  2023-11-20 13:04:00   0.0  10.20  10.21  10.20    3842   3918556.0  10.152  202311201304  830896202311201304
125  2023-11-20 13:05:00   0.0  10.19  10.21  10.19    1779   1814639.0  10.152  202311201305  830896202311201305
126  2023-11-20 13:06:00   0.0  10.20  10.20  10.19    2930   2986410.0  10.153  202311201306  830896202311201306
127  2023-11-20 13:07:00   0.0  10.19  10.20  10.19     839    855096.0  10.153  202311201307  830896202311201307
128  2023-11-20 13:08:00   0.0  10.19  10.20  10.19    1151   1173377.0  10.153  202311201308  830896202311201308
129  2023-11-20 13:09:00   0.0  10.19  10.20  10.19     882    899278.0  10.153  202311201309  830896202311201309
130  2023-11-20 13:10:00   0.0  10.20  10.20  10.19     394    401594.0  10.153  202311201310  830896202311201310
131  2023-11-20 13:11:00   0.0  10.20  10.20  10.19    5539   5648896.0  10.154  202311201311  830896202311201311
132  2023-11-20 13:12:00   0.0  10.20  10.21  10.20     989   1008592.0  10.154  202311201312  830896202311201312
133  2023-11-20 13:13:00   0.0  10.20  10.20  10.19    2016   2056248.0  10.154  202311201313  830896202311201313
134  2023-11-20 13:14:00   0.0  10.20  10.20  10.19    2830   2886273.0  10.154  202311201314  830896202311201314
135  2023-11-20 13:15:00   0.0  10.20  10.20  10.19    2347   2394126.0  10.154  202311201315  830896202311201315
136  2023-11-20 13:16:00   0.0  10.20  10.21  10.20    2134   2176184.0  10.155  202311201316  830896202311201316
137  2023-11-20 13:17:00   0.0  10.19  10.20  10.19    1064   1085299.0  10.155  202311201317  830896202311201317
138  2023-11-20 13:18:00   0.0  10.19  10.20  10.19     885    902336.0  10.155  202311201318  830896202311201318
139  2023-11-20 13:19:00   0.0  10.19  10.20  10.19     734    748116.0  10.155  202311201319  830896202311201319
140  2023-11-20 13:20:00   0.0  10.19  10.20  10.19     676    689148.0  10.155  202311201320  830896202311201320
141  2023-11-20 13:21:00   0.0  10.19  10.20  10.19    1607   1637585.0  10.155  202311201321  830896202311201321
142  2023-11-20 13:22:00   0.0  10.19  10.20  10.18    1284   1308395.0  10.155  202311201322  830896202311201322
143  2023-11-20 13:23:00   0.0  10.19  10.20  10.19     655    667565.0  10.155  202311201323  830896202311201323
144  2023-11-20 13:24:00   0.0  10.20  10.20  10.19     407    414924.0  10.155  202311201324  830896202311201324
145  2023-11-20 13:25:00   0.0  10.19  10.20  10.19    1038   1057862.0  10.155  202311201325  830896202311201325
146  2023-11-20 13:26:00   0.0  10.20  10.20  10.19     492    501447.0  10.155  202311201326  830896202311201326
147  2023-11-20 13:27:00   0.0  10.19  10.20  10.19    1098   1119491.0  10.155  202311201327  830896202311201327
148  2023-11-20 13:28:00   0.0  10.19  10.20  10.19     476    485233.0  10.156  202311201328  830896202311201328
149  2023-11-20 13:29:00   0.0  10.19  10.20  10.19    1388   1414842.0  10.156  202311201329  830896202311201329
150  2023-11-20 13:30:00   0.0  10.19  10.20  10.19    1653   1685379.0  10.156  202311201330  830896202311201330
151  2023-11-20 13:31:00   0.0  10.19  10.20  10.19    1539   1568792.0  10.156  202311201331  830896202311201331
152  2023-11-20 13:32:00   0.0  10.19  10.20  10.19     639    651477.0  10.156  202311201332  830896202311201332
153  2023-11-20 13:33:00   0.0  10.19  10.20  10.19     632    644129.0  10.156  202311201333  830896202311201333
154  2023-11-20 13:34:00   0.0  10.19  10.20  10.19     908    925465.0  10.156  202311201334  830896202311201334
155  2023-11-20 13:35:00   0.0  10.19  10.20  10.19     703    716729.0  10.156  202311201335  830896202311201335
156  2023-11-20 13:36:00   0.0  10.19  10.20  10.19    1733   1766703.0  10.156  202311201336  830896202311201336
157  2023-11-20 13:37:00   0.0  10.20  10.20  10.19    7741   7894435.0  10.157  202311201337  830896202311201337
158  2023-11-20 13:38:00   0.0  10.20  10.20  10.19    5884   6001295.0  10.157  202311201338  830896202311201338
159  2023-11-20 13:39:00   0.0  10.20  10.21  10.19    1241   1265643.0  10.158  202311201339  830896202311201339
160  2023-11-20 13:40:00   0.0  10.20  10.20  10.19    1048   1068505.0  10.158  202311201340  830896202311201340
161  2023-11-20 13:41:00   0.0  10.19  10.20  10.19     538    548368.0  10.158  202311201341  830896202311201341
162  2023-11-20 13:42:00   0.0  10.20  10.20  10.19     668    680937.0  10.158  202311201342  830896202311201342
163  2023-11-20 13:43:00   0.0  10.19  10.20  10.19    2220   2262465.0  10.158  202311201343  830896202311201343
164  2023-11-20 13:44:00   0.0  10.18  10.20  10.18    5579   5684453.0  10.158  202311201344  830896202311201344
165  2023-11-20 13:45:00   0.0  10.19  10.19  10.18     848    863665.0  10.158  202311201345  830896202311201345
166  2023-11-20 13:46:00   0.0  10.19  10.19  10.18    1579   1608576.0  10.158  202311201346  830896202311201346
167  2023-11-20 13:47:00   0.0  10.18  10.19  10.18     673    685458.0  10.158  202311201347  830896202311201347
168  2023-11-20 13:48:00   0.0  10.20  10.20  10.18    1872   1907610.0  10.159  202311201348  830896202311201348
169  2023-11-20 13:49:00   0.0  10.19  10.20  10.19     847    863131.0  10.159  202311201349  830896202311201349
170  2023-11-20 13:50:00   0.0  10.20  10.20  10.18    1677   1709236.0  10.159  202311201350  830896202311201350
171  2023-11-20 13:51:00   0.0  10.19  10.20  10.18     462    470574.0  10.159  202311201351  830896202311201351
172  2023-11-20 13:52:00   0.0  10.18  10.19  10.18     600    611053.0  10.159  202311201352  830896202311201352
173  2023-11-20 13:53:00   0.0  10.19  10.19  10.18     468    476634.0  10.159  202311201353  830896202311201353

In [47]:
#Dates = ['2023-11-20','2023-11-21','2023-11-22','2023-11-23','2023-11-24']
start_min = '2023-11-20 09:30:00'
end_min = '2023-11-24 15:00:00'

for CodeDes in code_list.values:
    ak_code, ak_name = CodeDes[1],CodeDes[2]
    print(date,ak_code,ak_name)
    if check(ak_code,date):
        print(True)
        continue
    try:
        stock_zh_a_hist_min_em_df = ak.stock_zh_a_hist_min_em(symbol=ak_code[2:], start_date=start_min, end_date=end_min, period='1', adjust='')
    except Exception as e:
        print(e)
        continue
    stock_zh_a_hist_min_em_df.rename(columns = {'时间':'Time','开盘':'Open','收盘':'Close','最高':'High','最低':'Low',
                                                '成交量':'Volume','成交额':'Turnover','最新价':'Latest'},inplace = True)
    stock_zh_a_hist_min_em_df['Minute_ID'] = stock_zh_a_hist_min_em_df['Time'].apply(lambda x:GetMinuteID(x))
    stock_zh_a_hist_min_em_df['FSM_ID'] = ak_code[2:]+stock_zh_a_hist_min_em_df['Minute_ID'].astype(str)
    stock_zh_a_hist_min_em_df['Stock_ID'] = ak_code[2:]
    stock_zh_a_hist_min_em_df['Stock_Name'] = ak_name
    stock_zh_a_hist_min_em_df = stock_zh_a_hist_min_em_df[['FSM_ID','Stock_ID','Minute_ID','Open',
                                                           'High','Low','Volume','Stock_Name','Turnover','Close']]
    path=create_path(ak_code,date)
    print(path)
    stock_zh_a_hist_min_em_df.to_csv(path, index=False, mode='w',encoding='gbk')

2023-11-24 bj430017 星昊医药
True
2023-11-24 bj430047 诺思兰德
True
2023-11-24 bj430090 同辉信息
True
2023-11-24 bj430139 华岭股份
True
2023-11-24 bj430198 微创光电
True
2023-11-24 bj430300 辰光医疗
True
2023-11-24 bj430418 苏轴股份
True
2023-11-24 bj430425 乐创技术
True
2023-11-24 bj430476 海能技术
True
2023-11-24 bj430478 峆一药业
True
2023-11-24 bj430489 佳先股份
True
2023-11-24 bj430510 丰光精密
True
2023-11-24 bj430556 雅达股份
True
2023-11-24 bj430564 天润科技
True
2023-11-24 bj430685 新芝生物
True
2023-11-24 bj430718 合肥高科
True
2023-11-24 bj830779 武汉蓝电
True
2023-11-24 bj830799 艾融软件
True
2023-11-24 bj830809 安达科技
True
2023-11-24 bj830832 齐鲁华信
True
2023-11-24 bj830839 万通液压
True
2023-11-24 bj830879 基康仪器
True
2023-11-24 bj830896 旺成科技
True
2023-11-24 bj830946 森萱医药
True
2023-11-24 bj830964 润农节水
True
2023-11-24 bj830974 凯大催化
True
2023-11-24 bj831010 凯添燃气
True
2023-11-24 bj831039 国义招标
True
2023-11-24 bj831087 秋乐种业
True
2023-11-24 bj831152 昆工科技
True
2023-11-24 bj831167 鑫汇科
True
2023-11-24 bj831195 三祥科技
True
2023-11-24 bj831278 泰德股份
True
2023-11-24 bj831304 迪尔化工
True
2023-11-24 bj831305 海希通讯
True
2023-11-24 bj831370 新安洁
True
2023-11-24 bj831445 龙竹科技
True
2023-11-24 bj831526 凯华材料
True
2023-11-24 bj831627 力王股份
True
2023-11-24 bj831641 格利尔
True
2023-11-24 bj831689 克莱特
True
2023-11-24 bj831726 朱老六
True
2023-11-24 bj831768 拾比佰
True
2023-11-24 bj831832 科达自控
True
2023-11-24 bj831834 三维股份
True
2023-11-24 bj831855 浙江大农
True
2023-11-24 bj831856 浩淼科技
True
2023-11-24 bj831906 舜宇精工
True
2023-11-24 bj831961 创远信科
True
2023-11-24 bj832000 安徽凤凰
True
2023-11-24 bj832023 田野股份
True
2023-11-24 bj832089 禾昌聚合
True
2023-11-24 bj832110 雷特科技
True
2023-11-24 bj832145 恒合股份
True
2023-11-24 bj832149 利尔达
True
2023-11-24 bj832171 志晟信息
True
2023-11-24 bj832175 东方碳素
True
2023-11-24 bj832225 利通科技
True
2023-11-24 bj832278 鹿得医疗
True
2023-11-24 bj832419 路斯股份
True
2023-11-24 bj832469 富恒新材
True
2023-11-24 bj832471 美邦科技
True
2023-11-24 bj832491 奥迪威
True
2023-11-24 bj832522 纳科诺尔
True
2023-11-24 bj832566 梓橦宫
True
2023-11-24 bj832651 天罡股份
True
2023-11-24 bj832662 方盛股份
True
2023-11-24 bj832735 德源药业
True
2023-11-24 bj832786 骑士乳业
True
2023-11-24 bj832802 保丽洁
True
2023-11-24 bj832876 慧为智能
True
2023-11-24 bj832885 星辰科技
True
2023-11-24 bj832978 开特股份
True
2023-11-24 bj832982 锦波生物
True
2023-11-24 bj833030 立方控股
True
2023-11-24 bj833075 柏星龙
True
2023-11-24 bj833171 国航远洋
True
2023-11-24 bj833230 欧康医药
True
2023-11-24 bj833266 生物谷
True
2023-11-24 bj833346 威贸电子
True
2023-11-24 bj833394 民士达
True
2023-11-24 bj833427 华维设计
True
2023-11-24 bj833429 康比特
True
2023-11-24 bj833454 同心传动
True
2023-11-24 bj833455 汇隆活塞
True
2023-11-24 bj833509 同惠电子
True
2023-11-24 bj833523 德瑞锂电
True
2023-11-24 bj833533 骏创科技
True
2023-11-24 bj833575 康乐卫士
True
2023-11-24 bj833580 科创新材
True
2023-11-24 bj833751 惠同新材
True
2023-11-24 bj833781 瑞奇智造
True
2023-11-24 bj833819 颖泰生物
True
2023-11-24 bj833873 中设咨询
True
2023-11-24 bj833914 远航精密
True
2023-11-24 bj833943 优机股份
True
2023-11-24 bj834014 特瑞斯
True
2023-11-24 bj834021 流金科技
True
2023-11-24 bj834033 康普化学
True
2023-11-24 bj834058 华洋赛车
True
2023-11-24 bj834062 科润智控
True
2023-11-24 bj834261 一诺威
True
2023-11-24 bj834407 驰诚股份
True
2023-11-24 bj834415 恒拓开源
True
2023-11-24 bj834475 三友科技
True
2023-11-24 bj834599 同力股份
True
2023-11-24 bj834639 晨光电缆
True
2023-11-24 bj834682 球冠电缆
True
2023-11-24 bj834765 美之高
True
2023-11-24 bj834770 艾能聚
True
2023-11-24 bj834950 迅安科技
True
2023-11-24 bj835174 五新隧装
True
2023-11-24 bj835179 凯德石英
True
2023-11-24 bj835184 国源科技
True
2023-11-24 bj835185 贝特瑞
True
2023-11-24 bj835207 众诚科技
True
2023-11-24 bj835237 力佳科技
True
2023-11-24 bj835305 云创数据
True
2023-11-24 bj835368 连城数控
True
2023-11-24 bj835508 殷图网联
True
2023-11-24 bj835640 富士达
True
2023-11-24 bj835670 数字人
True
2023-11-24 bj835857 百甲科技
True
2023-11-24 bj835892 中科美菱
True
2023-11-24 bj835985 海泰新能
True
2023-11-24 bj836077 吉林碳谷
True
2023-11-24 bj836149 旭杰科技
True
2023-11-24 bj836208 青矩技术
True
2023-11-24 bj836221 易实精密
True
2023-11-24 bj836239 长虹能源
True
2023-11-24 bj836247 华密新材
True
2023-11-24 bj836260 中寰股份
True
2023-11-24 bj836263 中航泰达
True
2023-11-24 bj836270 天铭科技
True
2023-11-24 bj836395 朗鸿科技
True
2023-11-24 bj836414 欧普泰
True
2023-11-24 bj836419 万德股份
True
2023-11-24 bj836422 润普食品
True
2023-11-24 bj836433 大唐药业
True
2023-11-24 bj836504 博迅生物
True
2023-11-24 bj836675 秉扬科技
True
2023-11-24 bj836699 海达尔
True
2023-11-24 bj836717 瑞星股份
True
2023-11-24 bj836720 吉冈精密
True
2023-11-24 bj836807 奔朗新材
True
2023-11-24 bj836826 盖世食品
True
2023-11-24 bj836871 派特尔
True
2023-11-24 bj836892 广咨国际
True
2023-11-24 bj836942 恒立钻具
True
2023-11-24 bj836957 汉维科技
True
2023-11-24 bj837006 晟楠科技
True
2023-11-24 bj837046 亿能电力
True
2023-11-24 bj837092 汉鑫科技
True
2023-11-24 bj837174 宏裕包材
True
2023-11-24 bj837212 智新电子
True
2023-11-24 bj837242 建邦科技
True
2023-11-24 bj837344 三元基因
True
2023-11-24 bj837592 华信永道
True
2023-11-24 bj837663 明阳科技
True
2023-11-24 bj837748 路桥信息
True
2023-11-24 bj837821 则成电子
True
2023-11-24 bj838030 德众汽车
True
2023-11-24 bj838163 方大新材
True
2023-11-24 bj838171 邦德股份
True
2023-11-24 bj838227 美登科技
True
2023-11-24 bj838262 太湖雪
True
2023-11-24 bj838275 驱动力
True
2023-11-24 bj838402 硅烷科技
True
2023-11-24 bj838670 恒进感应
True
2023-11-24 bj838701 豪声电子
True
2023-11-24 bj838810 春光药装
True
2023-11-24 bj838837 华原股份
True
2023-11-24 bj838924 广脉科技
True
2023-11-24 bj838971 天马新材
True
2023-11-24 bj839167 同享科技
True
2023-11-24 bj839273 一致魔芋
True
2023-11-24 bj839371 欧福蛋业
True
2023-11-24 bj839493 并行科技
True
2023-11-24 bj839680 广道数字
True
2023-11-24 bj839719 宁新新材
True
2023-11-24 bj839725 惠丰钻石
True
2023-11-24 bj839729 永顺生物
True
2023-11-24 bj839790 联迪信息
True
2023-11-24 bj839792 东和新材
True
2023-11-24 bj839946 华阳变速
True
2023-11-24 bj870199 倍益康
True
2023-11-24 bj870204 沪江材料
True
2023-11-24 bj870299 灿能电力
True
2023-11-24 bj870357 雅葆轩
True
2023-11-24 bj870436 大地电气
True
2023-11-24 bj870508 丰安股份
True
2023-11-24 bj870726 鸿智科技
True
2023-11-24 bj870866 绿亨科技
True
2023-11-24 bj870976 视声智能
True
2023-11-24 bj871245 威博液压
True
2023-11-24 bj871396 常辅股份
True
2023-11-24 bj871478 巨能股份
True
2023-11-24 bj871553 凯腾精工
True
2023-11-24 bj871634 新威凌
True
2023-11-24 bj871642 通易航天
True
2023-11-24 bj871694 中裕科技
True
2023-11-24 bj871753 天纺标
True
2023-11-24 bj871857 泓禧科技
True
2023-11-24 bj871970 大禹生物
True
2023-11-24 bj871981 晶赛科技
True
2023-11-24 bj872190 雷神科技
True
2023-11-24 bj872351 华光源海
True
2023-11-24 bj872374 云里物里
True
2023-11-24 bj872392 佳合科技
True
2023-11-24 bj872541 铁大科技
True
2023-11-24 bj872808 曙光数创
True
2023-11-24 bj872895 花溪科技
True
2023-11-24 bj872925 锦好医疗
True
2023-11-24 bj872953 国子软件
True
2023-11-24 bj873001 纬达光电
True
2023-11-24 bj873122 中纺标
True
2023-11-24 bj873132 泰鹏智能
True
2023-11-24 bj873152 天宏锂电
True
2023-11-24 bj873167 新赣江
True
2023-11-24 bj873169 七丰精工
True
2023-11-24 bj873223 荣亿精密
True
2023-11-24 bj873305 九菱科技
True
2023-11-24 bj873339 恒太照明
True
2023-11-24 bj873527 夜光明
True
2023-11-24 bj873576 天力复合
True
2023-11-24 bj873593 鼎智科技
True
2023-11-24 bj873665 科强股份
True
2023-11-24 bj873679 前进科技
True
2023-11-24 bj873693 阿为特
True
2023-11-24 bj873726 卓兆点胶
True
2023-11-24 bj873833 美心翼申
True
2023-11-24 sh600000 浦发银行
True
2023-11-24 sh600004 白云机场
True
2023-11-24 sh600006 东风汽车
True
2023-11-24 sh600007 中国国贸
True
2023-11-24 sh600008 首创环保
True
2023-11-24 sh600009 上海机场
True
2023-11-24 sh600010 包钢股份
True
2023-11-24 sh600011 华能国际
True
2023-11-24 sh600012 皖通高速
True
2023-11-24 sh600015 华夏银行
True
2023-11-24 sh600016 民生银行
True
2023-11-24 sh600017 日照港
True
2023-11-24 sh600018 上港集团
True
2023-11-24 sh600019 宝钢股份
True
2023-11-24 sh600020 中原高速
True
2023-11-24 sh600021 上海电力
True
2023-11-24 sh600022 山东钢铁
True
2023-11-24 sh600023 浙能电力
True
2023-11-24 sh600025 华能水电
True
2023-11-24 sh600026 中远海能
True
2023-11-24 sh600027 华电国际
True
2023-11-24 sh600028 中国石化
True
2023-11-24 sh600029 南方航空
True
2023-11-24 sh600030 中信证券
True
2023-11-24 sh600031 三一重工
True
2023-11-24 sh600032 浙江新能
True
2023-11-24 sh600033 福建高速
True
2023-11-24 sh600035 楚天高速
True
2023-11-24 sh600036 招商银行
True
2023-11-24 sh600037 歌华有线
True
2023-11-24 sh600038 中直股份
True
2023-11-24 sh600039 四川路桥
True
2023-11-24 sh600048 保利发展
True
2023-11-24 sh600050 中国联通
True
2023-11-24 sh600051 宁波联合
True
2023-11-24 sh600052 东望时代
True
2023-11-24 sh600053 九鼎投资
True
2023-11-24 sh600054 黄山旅游
True
2023-11-24 sh600055 万东医疗
True
2023-11-24 sh600056 中国医药
True
2023-11-24 sh600057 厦门象屿
True
2023-11-24 sh600058 五矿发展
True
2023-11-24 sh600059 古越龙山
True
2023-11-24 sh600060 海信视像
True
2023-11-24 sh600061 国投资本
True
2023-11-24 sh600062 华润双鹤
True
2023-11-24 sh600063 皖维高新
True
2023-11-24 sh600064 南京高科
True
2023-11-24 sh600066 宇通客车
True
2023-11-24 sh600067 冠城大通
True
2023-11-24 sh600070 ST富润
True
2023-11-24 sh600071 凤凰光学
True
2023-11-24 sh600072 中船科技
True
2023-11-24 sh600073 上海梅林
True
2023-11-24 sh600075 新疆天业
True
2023-11-24 sh600076 康欣新材
True
2023-11-24 sh600078 ST澄星
True
2023-11-24 sh600079 人福医药
True
2023-11-24 sh600080 金花股份
True
2023-11-24 sh600081 东风科技
True
2023-11-24 sh600082 海泰发展
True
2023-11-24 sh600083 博信股份
True
2023-11-24 sh600084 中信尼雅
True
2023-11-24 sh600085 同仁堂
True
2023-11-24 sh600088 中视传媒
True
2023-11-24 sh600089 特变电工
True
2023-11-24 sh600094 大名城
True
2023-11-24 sh600095 湘财股份
True
2023-11-24 sh600096 云天化
True
2023-11-24 sh600097 开创国际
True
2023-11-24 sh600098 广州发展
True
2023-11-24 sh600099 林海股份
True
2023-11-24 sh600100 同方股份
True
2023-11-24 sh600101 明星电力
True
2023-11-24 sh600103 青山纸业
True
2023-11-24 sh600104 上汽集团
True
2023-11-24 sh600105 永鼎股份
True
2023-11-24 sh600106 重庆路桥
True
2023-11-24 sh600107 美尔雅
True
2023-11-24 sh600108 亚盛集团
True
2023-11-24 sh600109 国金证券
True
2023-11-24 sh600110 诺德股份
True
2023-11-24 sh600111 北方稀土
True
2023-11-24 sh600112 ST天成
True
2023-11-24 sh600113 浙江东日
True
2023-11-24 sh600114 东睦股份
True
2023-11-24 sh600115 中国东航
True
2023-11-24 sh600116 三峡水利
True
2023-11-24 sh600117 *ST西钢
True
2023-11-24 sh600118 中国卫星
True
2023-11-24 sh600119 长江投资
True
2023-11-24 sh600120 浙江东方
True
2023-11-24 sh600121 郑州煤电
True
2023-11-24 sh600123 兰花科创
True
2023-11-24 sh600125 铁龙物流
True
2023-11-24 sh600126 杭钢股份
True
2023-11-24 sh600127 金健米业
True
2023-11-24 sh600128 苏豪弘业
True
2023-11-24 sh600129 太极集团
True
2023-11-24 sh600130 波导股份
True
2023-11-24 sh600131 国网信通
True
2023-11-24 sh600132 重庆啤酒
True
2023-11-24 sh600133 东湖高新
True
2023-11-24 sh600135 乐凯胶片
True
2023-11-24 sh600136 *ST明诚
True
2023-11-24 sh600137 浪莎股份
True
2023-11-24 sh600138 中青旅
True
2023-11-24 sh600141 兴发集团
True
2023-11-24 sh600143 金发科技
True
2023-11-24 sh600148 长春一东
True
2023-11-24 sh600149 廊坊发展
True
2023-11-24 sh600150 中国船舶
True
2023-11-24 sh600151 航天机电
True
2023-11-24 sh600152 维科技术
True
2023-11-24 sh600153 建发股份
True
2023-11-24 sh600155 华创云信
True
2023-11-24 sh600156 华升股份
True
2023-11-24 sh600157 永泰能源
True
2023-11-24 sh600158 中体产业
True
2023-11-24 sh600159 大龙地产
True
2023-11-24 sh600160 巨化股份
True
2023-11-24 sh600161 天坛生物
True
2023-11-24 sh600162 香江控股
True
2023-11-24 sh600163 中闽能源
True
2023-11-24 sh600165 宁科生物
True
2023-11-24 sh600166 福田汽车
True
2023-11-24 sh600167 联美控股
True
2023-11-24 sh600168 武汉控股
True
2023-11-24 sh600169 太原重工
True
2023-11-24 sh600170 上海建工
True
2023-11-24 sh600171 上海贝岭
True
2023-11-24 sh600172 黄河旋风
True
2023-11-24 sh600173 卧龙地产
True
2023-11-24 sh600176 中国巨石
True
2023-11-24 sh600177 雅戈尔
True
2023-11-24 sh600178 东安动力
True
2023-11-24 sh600179 安通控股
True
2023-11-24 sh600180 瑞茂通
True
2023-11-24 sh600182 S佳通
True
2023-11-24 sh600183 生益科技
True
2023-11-24 sh600184 光电股份
True
2023-11-24 sh600185 格力地产
True
2023-11-24 sh600186 莲花健康
True
2023-11-24 sh600187 国中水务
True
2023-11-24 sh600188 兖矿能源
True
2023-11-24 sh600189 泉阳泉
True
2023-11-24 sh600190 锦州港
True
2023-11-24 sh600191 华资实业
True
2023-11-24 sh600192 长城电工
True
2023-11-24 sh600193 创兴资源
True
2023-11-24 sh600195 中牧股份
True
2023-11-24 sh600196 复星医药
True
2023-11-24 sh600197 伊力特
True
2023-11-24 sh600198 大唐电信
True
2023-11-24 sh600199 金种子酒
True
2023-11-24 sh600200 江苏吴中
True
2023-11-24 sh600201 生物股份
True
2023-11-24 sh600202 哈空调
True
2023-11-24 sh600203 福日电子
True
2023-11-24 sh600206 有研新材
True
2023-11-24 sh600207 安彩高科
True
2023-11-24 sh600208 新湖中宝
True
2023-11-24 sh600210 紫江企业
True
2023-11-24 sh600211 西藏药业
True
2023-11-24 sh600212 绿能慧充
True
2023-11-24 sh600213 亚星客车
True
2023-11-24 sh600215 派斯林
True
2023-11-24 sh600216 浙江医药
True
2023-11-24 sh600217 中再资环
True
2023-11-24 sh600218 全柴动力
True
2023-11-24 sh600219 南山铝业
True
2023-11-24 sh600220 江苏阳光
True
2023-11-24 sh600221 海航控股
True
2023-11-24 sh600222 太龙药业
True
2023-11-24 sh600223 福瑞达
True
2023-11-24 sh600225 卓朗科技
True
2023-11-24 sh600226 瀚叶股份
True
2023-11-24 sh600227 赤天化
True
2023-11-24 sh600228 返利科技
True
2023-11-24 sh600229 城市传媒
True
2023-11-24 sh600230 沧州大化
True
2023-11-24 sh600231 凌钢股份
True
2023-11-24 sh600232 金鹰股份
True
2023-11-24 sh600233 圆通速递
True
2023-11-24 sh600234 科新发展
True
2023-11-24 sh600235 民丰特纸
True
2023-11-24 sh600236 桂冠电力
True
2023-11-24 sh600237 铜峰电子
True
2023-11-24 sh600238 海南椰岛
True
2023-11-24 sh600239 云南城投
True
2023-11-24 sh600241 时代万恒
True
2023-11-24 sh600243 青海华鼎
True
2023-11-24 sh600246 万通发展
True
2023-11-24 sh600248 陕建股份
True
2023-11-24 sh600249 两面针
True
2023-11-24 sh600250 南纺股份
True
2023-11-24 sh600251 冠农股份
True
2023-11-24 sh600252 中恒集团
True
2023-11-24 sh600255 鑫科材料
True
2023-11-24 sh600256 广汇能源
True
2023-11-24 sh600257 大湖股份
True
2023-11-24 sh600258 首旅酒店
True
2023-11-24 sh600259 广晟有色
True
2023-11-24 sh600261 阳光照明
True
2023-11-24 sh600262 北方股份
True
2023-11-24 sh600265 ST景谷
True
2023-11-24 sh600266 城建发展
True
2023-11-24 sh600267 海正药业
True
2023-11-24 sh600268 国电南自
True
2023-11-24 sh600269 赣粤高速
True
2023-11-24 sh600271 航天信息
True
2023-11-24 sh600272 开开实业
True
2023-11-24 sh600273 嘉化能源
True
2023-11-24 sh600276 恒瑞医药
True
2023-11-24 sh600277 亿利洁能
True
2023-11-24 sh600278 东方创业
True
2023-11-24 sh600279 重庆港
True
2023-11-24 sh600280 中央商场
True
2023-11-24 sh600281 华阳新材
True
2023-11-24 sh600282 南钢股份
True
2023-11-24 sh600283 钱江水利
True
2023-11-24 sh600284 浦东建设
True
2023-11-24 sh600285 羚锐制药
True
2023-11-24 sh600287 江苏舜天
True
2023-11-24 sh600288 大恒科技
True
2023-11-24 sh600289 ST信通
True
2023-11-24 sh600290 *ST华仪
True
2023-11-24 sh600292 远达环保
True
2023-11-24 sh600293 三峡新材
True
2023-11-24 sh600295 鄂尔多斯
True
2023-11-24 sh600297 广汇汽车
True
2023-11-24 sh600298 安琪酵母
True
2023-11-24 sh600299 安迪苏
True
2023-11-24 sh600300 维维股份
True
2023-11-24 sh600301 华锡有色
True
2023-11-24 sh600302 标准股份
True
2023-11-24 sh600303 ST曙光
True
2023-11-24 sh600305 恒顺醋业
True
2023-11-24 sh600306 *ST商城
True
2023-11-24 sh600307 酒钢宏兴
True
2023-11-24 sh600308 华泰股份
True
2023-11-24 sh600309 万华化学
True
2023-11-24 sh600310 广西能源
True
2023-11-24 sh600312 平高电气
True
2023-11-24 sh600313 农发种业
True
2023-11-24 sh600315 上海家化
True
2023-11-24 sh600316 洪都航空
True
2023-11-24 sh600318 新力金融
True
2023-11-24 sh600319 亚星化学
True
2023-11-24 sh600320 振华重工
True
2023-11-24 sh600321 正源股份
True
2023-11-24 sh600322 津投城开
True
2023-11-24 sh600323 瀚蓝环境
True
2023-11-24 sh600325 华发股份
True
2023-11-24 sh600326 西藏天路
True
2023-11-24 sh600327 大东方
True
2023-11-24 sh600328 中盐化工
True
2023-11-24 sh600329 达仁堂
True
2023-11-24 sh600330 天通股份
True
2023-11-24 sh600331 宏达股份
True
2023-11-24 sh600332 白云山
True
2023-11-24 sh600333 长春燃气
True
2023-11-24 sh600335 国机汽车
True
2023-11-24 sh600336 澳柯玛
True
2023-11-24 sh600337 美克家居
True
2023-11-24 sh600338 西藏珠峰
True
2023-11-24 sh600339 中油工程
True
2023-11-24 sh600340 华夏幸福
True
2023-11-24 sh600343 航天动力
True
2023-11-24 sh600345 长江通信
True
2023-11-24 sh600346 恒力石化
True
2023-11-24 sh600348 华阳股份
True
2023-11-24 sh600350 山东高速
True
2023-11-24 sh600351 亚宝药业
True
2023-11-24 sh600352 浙江龙盛
True
2023-11-24 sh600353 旭光电子
True
2023-11-24 sh600354 敦煌种业
True
2023-11-24 sh600355 精伦电子
True
2023-11-24 sh600356 恒丰纸业
True
2023-11-24 sh600358 国旅联合
True
2023-11-24 sh600359 新农开发
True
2023-11-24 sh600360 华微电子
True
2023-11-24 sh600361 创新新材
True
2023-11-24 sh600362 江西铜业
True
2023-11-24 sh600363 联创光电
True
2023-11-24 sh600365 ST通葡
True
2023-11-24 sh600366 宁波韵升
True
2023-11-24 sh600367 红星发展
True
2023-11-24 sh600368 五洲交通
True
2023-11-24 sh600369 西南证券
True
2023-11-24 sh600370 三房巷
True
2023-11-24 sh600371 万向德农
True
2023-11-24 sh600372 中航机载
True
2023-11-24 sh600373 中文传媒
True
2023-11-24 sh600375 汉马科技
True
2023-11-24 sh600376 首开股份
True
2023-11-24 sh600377 宁沪高速
True
2023-11-24 sh600378 昊华科技
True
2023-11-24 sh600379 宝光股份
True
2023-11-24 sh600380 健康元
True
2023-11-24 sh600381 青海春天
True
2023-11-24 sh600382 广东明珠
True
2023-11-24 sh600383 金地集团
True
2023-11-24 sh600386 北巴传媒
True
2023-11-24 sh600387 ST海越
True
2023-11-24 sh600388 龙净环保
True
2023-11-24 sh600389 江山股份
True
2023-11-24 sh600390 五矿资本
True
2023-11-24 sh600391 航发科技
True
2023-11-24 sh600392 盛和资源
True
2023-11-24 sh600395 盘江股份
True
2023-11-24 sh600396 *ST金山
True
2023-11-24 sh600397 安源煤业
True
2023-11-24 sh600398 海澜之家
True
2023-11-24 sh600399 抚顺特钢
True
2023-11-24 sh600400 红豆股份
True
2023-11-24 sh600403 大有能源
True
2023-11-24 sh600405 动力源
True
2023-11-24 sh600406 国电南瑞
True
2023-11-24 sh600408 安泰集团
True
2023-11-24 sh600409 三友化工
True
2023-11-24 sh600410 华胜天成
True
2023-11-24 sh600415 小商品城
True
2023-11-24 sh600416 湘电股份
True
2023-11-24 sh600418 江淮汽车
True
2023-11-24 sh600419 天润乳业
True
2023-11-24 sh600420 国药现代
True
2023-11-24 sh600421 华嵘控股
True
2023-11-24 sh600422 昆药集团
True
2023-11-24 sh600423 柳化股份
True
2023-11-24 sh600425 青松建化
True
2023-11-24 sh600426 华鲁恒升
True
2023-11-24 sh600428 中远海特
True
2023-11-24 sh600429 三元股份
True
2023-11-24 sh600433 冠豪高新
True
2023-11-24 sh600435 北方导航
True
2023-11-24 sh600436 片仔癀
True
2023-11-24 sh600438 通威股份
True
2023-11-24 sh600439 瑞贝卡
True
2023-11-24 sh600444 国机通用
True
2023-11-24 sh600446 金证股份
True
2023-11-24 sh600448 华纺股份
True
2023-11-24 sh600449 宁夏建材
True
2023-11-24 sh600452 涪陵电力
True
2023-11-24 sh600455 博通股份
True
2023-11-24 sh600456 宝钛股份
True
2023-11-24 sh600458 时代新材
True
2023-11-24 sh600459 贵研铂业
True
2023-11-24 sh600460 士兰微
True
2023-11-24 sh600461 洪城环境
True
2023-11-24 sh600462 ST九有
True
2023-11-24 sh600463 空港股份
True
2023-11-24 sh600467 好当家
True
2023-11-24 sh600468 百利电气
True
2023-11-24 sh600469 风神股份
True
2023-11-24 sh600470 六国化工
True
2023-11-24 sh600475 华光环能
True
2023-11-24 sh600476 湘邮科技
True
2023-11-24 sh600477 杭萧钢构
True
2023-11-24 sh600478 科力远
True
2023-11-24 sh600479 千金药业
True
2023-11-24 sh600480 凌云股份
True
2023-11-24 sh600481 双良节能
True
2023-11-24 sh600482 中国动力
True
2023-11-24 sh600483 福能股份
True
2023-11-24 sh600486 扬农化工
True
2023-11-24 sh600487 亨通光电
True
2023-11-24 sh600488 津药药业
True
2023-11-24 sh600489 中金黄金
True
2023-11-24 sh600490 鹏欣资源
True
2023-11-24 sh600491 龙元建设
True
2023-11-24 sh600493 凤竹纺织
True
2023-11-24 sh600495 晋西车轴
True
2023-11-24 sh600496 精工钢构
True
2023-11-24 sh600497 驰宏锌锗
True
2023-11-24 sh600498 烽火通信
True
2023-11-24 sh600499 科达制造
True
2023-11-24 sh600500 中化国际
True
2023-11-24 sh600501 航天晨光
True
2023-11-24 sh600502 安徽建工
True
2023-11-24 sh600503 华丽家族
True
2023-11-24 sh600505 西昌电力
True
2023-11-24 sh600506 统一股份
True
2023-11-24 sh600507 方大特钢
True
2023-11-24 sh600508 上海能源
True
2023-11-24 sh600509 天富能源
True
2023-11-24 sh600510 黑牡丹
True
2023-11-24 sh600511 国药股份
True
2023-11-24 sh600512 腾达建设
True
2023-11-24 sh600513 联环药业
True
2023-11-24 sh600515 海南机场
True
2023-11-24 sh600516 方大炭素
True
2023-11-24 sh600517 国网英大
True
2023-11-24 sh600518 ST康美
True
2023-11-24 sh600519 贵州茅台
True
2023-11-24 sh600520 文一科技
True
2023-11-24 sh600521 华海药业
True
2023-11-24 sh600522 中天科技
True
2023-11-24 sh600523 贵航股份
True
2023-11-24 sh600525 长园集团
True
2023-11-24 sh600526 菲达环保
True
2023-11-24 sh600527 江南高纤
True
2023-11-24 sh600528 中铁工业
True
2023-11-24 sh600529 山东药玻
True
2023-11-24 sh600530 ST交昂
True
2023-11-24 sh600531 豫光金铅
True
2023-11-24 sh600533 栖霞建设
True
2023-11-24 sh600535 天士力
True
2023-11-24 sh600536 中国软件
True
2023-11-24 sh600537 亿晶光电
True
2023-11-24 sh600538 国发股份
True
2023-11-24 sh600539 狮头股份
True
2023-11-24 sh600540 新赛股份
True
2023-11-24 sh600543 *ST莫高
True
2023-11-24 sh600545 卓郎智能
True
2023-11-24 sh600546 山煤国际
True
2023-11-24 sh600547 山东黄金
True
2023-11-24 sh600548 深高速
True
2023-11-24 sh600549 厦门钨业
True
2023-11-24 sh600550 保变电气
True
2023-11-24 sh600551 时代出版
True
2023-11-24 sh600552 凯盛科技
True
2023-11-24 sh600556 天下秀
True
2023-11-24 sh600557 康缘药业
True
2023-11-24 sh600558 大西洋
True
2023-11-24 sh600559 老白干酒
True
2023-11-24 sh600560 金自天正
True
2023-11-24 sh600561 江西长运
True
2023-11-24 sh600562 国睿科技
True
2023-11-24 sh600563 法拉电子
True
2023-11-24 sh600565 迪马股份
True
2023-11-24 sh600566 济川药业
True
2023-11-24 sh600567 山鹰国际
True
2023-11-24 sh600568 ST中珠
True
2023-11-24 sh600569 安阳钢铁
True
2023-11-24 sh600570 恒生电子
True
2023-11-24 sh600571 信雅达
True
2023-11-24 sh600572 康恩贝

./1min_DFCF/sh688620.csv
2023-11-24 sh688621 阳光诺和
True
2023-11-24 sh688622 禾信仪器
True
2023-11-24 sh688623 双元科技
True
2023-11-24 sh688625 呈和科技
True
2023-11-24 sh688626 翔宇医疗
True
2023-11-24 sh688627 精智达
True
2023-11-24 sh688628 优利德
True
2023-11-24 sh688629 华丰科技
True
2023-11-24 sh688630 芯碁微装
True
2023-11-24 sh688631 莱斯信息
True
2023-11-24 sh688633 星球石墨
True
2023-11-24 sh688636 智明达
True
2023-11-24 sh688638 誉辰智能
True
2023-11-24 sh688639 华恒生物
True
2023-11-24 sh688646 逸飞激光
True
2023-11-24 sh688648 C中邮
True
2023-11-24 sh688651 盛邦安全
True
2023-11-24 sh688653 N康希
True
2023-11-24 sh688655 迅捷兴
True
2023-11-24 sh688656 浩欧博
True
2023-11-24 sh688657 浩辰软件
True
2023-11-24 sh688658 悦康药业
True
2023-11-24 sh688659 元琛科技
True
2023-11-24 sh688660 电气风电
True
2023-11-24 sh688661 和林微纳
True
2023-11-24 sh688662 富信科技
True
2023-11-24 sh688663 新风光
True
2023-11-24 sh688665 四方光电
True
2023-11-24 sh688667 菱电电控
True
2023-11-24 sh688668 鼎通科技
True
2023-11-24 sh688669 聚石化学
True
2023-11-24 sh688670 金迪克
True
2023-11-24 sh688671 碧兴物联
True
2023-11-24 sh688676 金盘科技
True
2023-11-24 sh688677 海泰新光
True
2023-11-24 sh688678 福立旺
True
2023-11-24 sh688679 通源环境
True
2023-11-24 sh688680 海优新材
True
2023-11-24 sh688681 科汇股份
True
2023-11-24 sh688682 霍莱沃
True
2023-11-24 sh688683 莱尔科技
True
2023-11-24 sh688685 迈信林
True
2023-11-24 sh688686 奥普特
True
2023-11-24 sh688687 凯因科技
True
2023-11-24 sh688689 银河微电
True
2023-11-24 sh688690 纳微科技
True
2023-11-24 sh688693 锴威特
True
2023-11-24 sh688696 极米科技
True
2023-11-24 sh688697 纽威数控
True
2023-11-24 sh688698 伟创电气
True
2023-11-24 sh688699 明微电子
True
2023-11-24 sh688700 东威科技
True
2023-11-24 sh688701 卓锦股份
True
2023-11-24 sh688702 盛科通信
True
2023-11-24 sh688707 振华新材
True
2023-11-24 sh688711 宏微科技
True
2023-11-24 sh688716 中研股份
True
2023-11-24 sh688718 唯赛勃
True
2023-11-24 sh688719 爱科赛博
True
2023-11-24 sh688722 同益中
True
2023-11-24 sh688728 格科微
True
2023-11-24 sh688733 壹石通
True
2023-11-24 sh688737 中自科技
True
2023-11-24 sh688739 成大生物
True
2023-11-24 sh688766 普冉股份
True
2023-11-24 sh688767 博拓生物
True
2023-11-24 sh688768 容知日新
True
2023-11-24 sh688772 珠海冠宇
True
2023-11-24 sh688776 国光电气
True
2023-11-24 sh688777 中控技术
True
2023-11-24 sh688778 厦钨新能
True
2023-11-24 sh688779 长远锂科
True
2023-11-24 sh688786 悦安新材
True
2023-11-24 sh688787 海天瑞声
True
2023-11-24 sh688788 科思科技
True
2023-11-24 sh688789 宏华数科
True
2023-11-24 sh688793 倍轻松
True
2023-11-24 sh688798 艾为电子
True
2023-11-24 sh688799 华纳药厂
True
2023-11-24 sh688800 瑞可达
True
2023-11-24 sh688819 天能股份
True
2023-11-24 sh688981 中芯国际
True
2023-11-24 sz000001 平安银行
True
2023-11-24 sz000002 万 科Ａ
True
2023-11-24 sz000004 国华网安
True
2023-11-24 sz000005 ST星源
./1min_DFCF/sz000005.csv
2023-11-24 sz000006 深振业Ａ
True
2023-11-24 sz000007 *ST全新
True
2023-11-24 sz000008 神州高铁
True
2023-11-24 sz000009 中国宝安
True
2023-11-24 sz000010 美丽生态
True
2023-11-24 sz000011 深物业A
True
2023-11-24 sz000012 南 玻Ａ
True
2023-11-24 sz000014 沙河股份
True
2023-11-24 sz000016 深康佳Ａ
True
2023-11-24 sz000017 深中华A
True
2023-11-24 sz000019 深粮控股
True
2023-11-24 sz000020 深华发Ａ
True
2023-11-24 sz000021 深科技
True
2023-11-24 sz000023 ST深天
True
2023-11-24 sz000025 特 力Ａ
True
2023-11-24 sz000026 飞亚达
True
2023-11-24 sz000027 深圳能源
True
2023-11-24 sz000028 国药一致
True
2023-11-24 sz000029 深深房Ａ
True
2023-11-24 sz000030 富奥股份
True
2023-11-24 sz000031 大悦城
True
2023-11-24 sz000032 深桑达Ａ
True
2023-11-24 sz000034 神州数码
True
2023-11-24 sz000035 中国天楹
True
2023-11-24 sz000036 华联控股
True
2023-11-24 sz000037 深南电A
True
2023-11-24 sz000039 中集集团
True
2023-11-24 sz000040 东旭蓝天
True
2023-11-24 sz000042 中洲控股
True
2023-11-24 sz000045 深纺织Ａ
True
2023-11-24 sz000046 *ST泛海
True
2023-11-24 sz000048 京基智农
True
2023-11-24 sz000049 德赛电池
True
2023-11-24 sz000050 深天马Ａ
True
2023-11-24 sz000055 方大集团
True
2023-11-24 sz000056 皇庭国际
True
2023-11-24 sz000058 深 赛 格
True
2023-11-24 sz000059 华锦股份
True
2023-11-24 sz000060 中金岭南
True
2023-11-24 sz000061 农 产 品
True
2023-11-24 sz000062 深圳华强
True
2023-11-24 sz000063 中兴通讯
True
2023-11-24 sz000065 北方国际
True
2023-11-24 sz000066 中国长城
True
2023-11-24 sz000068 华控赛格
True
2023-11-24 sz000069 华侨城Ａ
True
2023-11-24 sz000070 特发信息
True
2023-11-24 sz000078 海王生物
True
2023-11-24 sz000088 盐 田 港
True
2023-11-24 sz000089 深圳机场
True
2023-11-24 sz000090 天健集团
True
2023-11-24 sz000096 广聚能源
True
2023-11-24 sz000099 中信海直
True
2023-11-24 sz000100 TCL科技
True
2023-11-24 sz000151 中成股份
True
2023-11-24 sz000153 丰原药业
True
2023-11-24 sz000155 川能动力
True
2023-11-24 sz000156 华数传媒
True
2023-11-24 sz000157 中联重科
True
2023-11-24 sz000158 常山北明
True
2023-11-24 sz000159 国际实业
True
2023-11-24 sz000166 申万宏源
True
2023-11-24 sz000301 东方盛虹
True
2023-11-24 sz000333 美的集团
True
2023-11-24 sz000338 潍柴动力
True
2023-11-24 sz000400 许继电气
True
2023-11-24 sz000401 冀东水泥
True
2023-11-24 sz000402 金 融 街
True
2023-11-24 sz000403 派林生物
True
2023-11-24 sz000404 长虹华意
True
2023-11-24 sz000407 胜利股份
True
2023-11-24 sz000408 藏格矿业
True
2023-11-24 sz000409 云鼎科技
True
2023-11-24 sz000410 沈阳机床
True
2023-11-24 sz000411 英特集团
True
2023-11-24 sz000413 东旭光电
True
2023-11-24 sz000415 渤海租赁
True
2023-11-24 sz000416 *ST民控
True
2023-11-24 sz000417 合肥百货
True
2023-11-24 sz000419 通程控股
True
2023-11-24 sz000420 吉林化纤
True
2023-11-24 sz000421 南京公用
True
2023-11-24 sz000422 湖北宜化
True
2023-11-24 sz000423 东阿阿胶
True
2023-11-24 sz000425 徐工机械
True
2023-11-24 sz000426 兴业银锡
True
2023-11-24 sz000428 华天酒店
True
2023-11-24 sz000429 粤高速Ａ
True
2023-11-24 sz000430 张家界
True
2023-11-24 sz000488 晨鸣纸业
True
2023-11-24 sz000498 山东路桥
True
2023-11-24 sz000501 武商集团
True
2023-11-24 sz000503 国新健康
./1min_DFCF/sz000503.csv
2023-11-24 sz000504 南华生物
True
2023-11-24 sz000505 京粮控股
True
2023-11-24 sz000506 中润资源
True
2023-11-24 sz000507 珠海港
True
2023-11-24 sz000509 华塑控股
True
2023-11-24 sz000510 新金路
True
2023-11-24 sz000513 丽珠集团
True
2023-11-24 sz000514 渝 开 发
True
2023-11-24 sz000516 国际医学
True
2023-11-24 sz000517 荣安地产
True
2023-11-24 sz000518 四环生物
True
2023-11-24 sz000519 中兵红箭
True
2023-11-24 sz000520 凤凰航运
True
2023-11-24 sz000521 长虹美菱
True
2023-11-24 sz000523 广州浪奇
True
2023-11-24 sz000524 岭南控股
True
2023-11-24 sz000525 ST红太阳
True
2023-11-24 sz000526 学大教育
True
2023-11-24 sz000528 柳 工
True
2023-11-24 sz000529 广弘控股
True
2023-11-24 sz000530 冰山冷热
True
2023-11-24 sz000531 穗恒运Ａ
True
2023-11-24 sz000532 华金资本
True
2023-11-24 sz000533 顺钠股份
True
2023-11-24 sz000534 万泽股份
True
2023-11-24 sz000536 华映科技
True
2023-11-24 sz000537 广宇发展
True
2023-11-24 sz000538 云南白药
True
2023-11-24 sz000539 粤电力Ａ
True
2023-11-24 sz000541 佛山照明
True
2023-11-24 sz000543 皖能电力
True
2023-11-24 sz000544 中原环保
True
2023-11-24 sz000545 金浦钛业
True
2023-11-24 sz000546 金圆股份
True
2023-11-24 sz000547 航天发展
True
2023-11-24 sz000548 湖南投资
True
2023-11-24 sz000550 江铃汽车
True
2023-11-24 sz000551 创元科技
True
2023-11-24 sz000552 甘肃能化
True
2023-11-24 sz000553 安道麦A
True
2023-11-24 sz000554 泰山石油
True
2023-11-24 sz000555 神州信息
True
2023-11-24 sz000557 西部创业
True
2023-11-24 sz000558 莱茵体育
True
2023-11-24 sz000559 万向钱潮
True
2023-11-24 sz000560 我爱我家
True
2023-11-24 sz000561 烽火电子
True
2023-11-24 sz000563 陕国投Ａ
True
2023-11-24 sz000564 ST大集
True
2023-11-24 sz000565 渝三峡Ａ
True
2023-11-24 sz000566 海南海药
True
2023-11-24 sz000567 海德股份
True
2023-11-24 sz000568 泸州老窖
True
2023-11-24 sz000570 苏常柴Ａ
True
2023-11-24 sz000571 新大洲A
True
2023-11-24 sz000572 海马汽车
True
2023-11-24 sz000573 粤宏远Ａ
True
2023-11-24 sz000576 甘化科工
True
2023-11-24 sz000581 威孚高科
True
2023-11-24 sz000582 北部湾港
True
2023-11-24 sz000584 ST工智
True
2023-11-24 sz000586 汇源通信
True
2023-11-24 sz000589 贵州轮胎
True
2023-11-24 sz000590 启迪药业
True
2023-11-24 sz000591 太阳能
True
2023-11-24 sz000592 平潭发展
True
2023-11-24 sz000593 德龙汇能
True
2023-11-24 sz000595 宝塔实业
True
2023-11-24 sz000596 古井贡酒
True
2023-11-24 sz000597 东北制药
True
2023-11-24 sz000598 兴蓉环境
True
2023-11-24 sz000599 青岛双星
True
2023-11-24 sz000600 建投能源
True
2023-11-24 sz000601 韶能股份
True
2023-11-24 sz000603 盛达资源
True
2023-11-24 sz000605 渤海股份
True
2023-11-24 sz000607 华媒控股
True
2023-11-24 sz000608 阳光股份
True
2023-11-24 sz000609 中迪投资
True
2023-11-24 sz000610 西安旅游
True
2023-11-24 sz000612 焦作万方
True
2023-11-24 sz000615 *ST美谷
True
2023-11-24 sz000617 中油资本
True
2023-11-24 sz000619 海螺新材
True
2023-11-24 sz000620 *ST新联
True
2023-11-24 sz000622 恒立实业
True
2023-11-24 sz000623 吉林敖东
True
2023-11-24 sz000625 长安汽车
True
2023-11-24 sz000626 远大控股
True
2023-11-24 sz000627 天茂集团
True
2023-11-24 sz000628 高新发展
True
2023-11-24 sz000629 钒钛股份
True
2023-11-24 sz000630 铜陵有色
True
2023-11-24 sz000631 顺发恒业
True
2023-11-24 sz000632 三木集团
True
2023-11-24 sz000633 合金投资
True
2023-11-24 sz000635 英 力 特
True
2023-11-24 sz000636 风华高科
True
2023-11-24 sz000637 ST实华
True
2023-11-24 sz000638 万方发展
True
2023-11-24 sz000639 西王食品
True
2023-11-24 sz000650 仁和药业
True
2023-11-24 sz000651 格力电器
True
2023-11-24 sz000652 泰达股份
True
2023-11-24 sz000655 金岭矿业
True
2023-11-24 sz000656 金科股份
True
2023-11-24 sz000657 中钨高新
True
2023-11-24 sz000659 珠海中富
True
2023-11-24 sz000661 长春高新
True
2023-11-24 sz000663 永安林业
True
2023-11-24 sz000665 湖北广电
True
2023-11-24 sz000668 荣丰控股
True
2023-11-24 sz000669 ST金鸿
True
2023-11-24 sz000670 盈方微
True
2023-11-24 sz000672 上峰水泥
True
2023-11-24 sz000676 智度股份
True
2023-11-24 sz000677 恒天海龙
True
2023-11-24 sz000678 襄阳轴承
True
2023-11-24 sz000679 大连友谊
True
2023-11-24 sz000680 山推股份
True
2023-11-24 sz000681 视觉中国
True
2023-11-24 sz000682 东方电子
True
2023-11-24 sz000683 远兴能源
True
2023-11-24 sz000685 中山公用
True
2023-11-24 sz000686 东北证券
True
2023-11-24 sz000688 国城矿业
True
2023-11-24 sz000690 宝新能源
True
2023-11-24 sz000691 亚太实业
True
2023-11-24 sz000692 *ST惠天
True
2023-11-24 sz000695 滨海能源
True
2023-11-24 sz000697 *ST炼石
True
2023-11-24 sz000698 沈阳化工
True
2023-11-24 sz000700 模塑科技
True
2023-11-24 sz000701 厦门信达
True
2023-11-24 sz000702 正虹科技
True
2023-11-24 sz000703 恒逸石化
True
2023-11-24 sz000705 浙江震元
True
2023-11-24 sz000707 双环科技
True
2023-11-24 sz000708 中信特钢
True
2023-11-24 sz000709 河钢股份
True
2023-11-24 sz000710 贝瑞基因
True
2023-11-24 sz000711 *ST京蓝
True
2023-11-24 sz000712 锦龙股份
True
2023-11-24 sz000713 丰乐种业
True
2023-11-24 sz000715 中兴商业
True
2023-11-24 sz000716 黑芝麻
True
2023-11-24 sz000717 中南股份
True
2023-11-24 sz000718 苏宁环球
True
2023-11-24 sz000719 中原传媒
True
2023-11-24 sz000720 新能泰山
True
2023-11-24 sz000721 西安饮食
True
2023-11-24 sz000722 湖南发展
True
2023-11-24 sz000723 美锦能源
True
2023-11-24 sz000725 京东方Ａ
True
2023-11-24 sz000726 鲁 泰Ａ
True
2023-11-24 sz000727 冠捷科技
True
2023-11-24 sz000728 国元证券
True
2023-11-24 sz000729 燕京啤酒
True
2023-11-24 sz000731 四川美丰
True
2023-11-24 sz000733 振华科技
True
2023-11-24 sz000735 罗 牛 山
True
2023-11-24 sz000736 中交地产
True
2023-11-24 sz000737 北方铜业
True
2023-11-24 sz000738 航发控制
True
2023-11-24 sz000739 普洛药业
True
2023-11-24 sz000750 国海证券
True
2023-11-24 sz000751 锌业股份
True
2023-11-24 sz000752 *ST西发
True
2023-11-24 sz000753 漳州发展
True
2023-11-24 sz000755 山西路桥
True
2023-11-24 sz000756 新华制药
True
2023-11-24 sz000757 浩物股份
True
2023-11-24 sz000758 中色股份
True
2023-11-24 sz000759 中百集团
True
2023-11-24 sz000761 本钢板材
True
2023-11-24 sz000762 西藏矿业
True
2023-11-24 sz000766 通化金马
True
2023-11-24 sz000767 晋控电力
True
2023-11-24 sz000768 中航西飞
True
2023-11-24 sz000776 广发证券
True
2023-11-24 sz000777 中核科技
True
2023-11-24 sz000778 新兴铸管
True
2023-11-24 sz000779 甘咨询
True
2023-11-24 sz000782 美达股份
True
2023-11-24 sz000783 长江证券
True
2023-11-24 sz000785 居然之家
True
2023-11-24 sz000786 北新建材
True
2023-11-24 sz000788 北大医药
True
2023-11-24 sz000789 万年青
True
2023-11-24 sz000790 华神科技
True
2023-11-24 sz000791 甘肃能源
True
2023-11-24 sz000792 盐湖股份
True
2023-11-24 sz000793 华闻集团
True
2023-11-24 sz000795 英洛华
True
2023-11-24 sz000796 *ST凯撒
True
2023-11-24 sz000797 中国武夷
True
2023-11-24 sz000798 中水渔业
True
2023-11-24 sz000799 酒鬼酒
True
2023-11-24 sz000800 一汽解放
True
2023-11-24 sz000801 四川九洲
True
2023-11-24 sz000802 北京文化
True
2023-11-24 sz000803 山高环能
True
2023-11-24 sz000807 云铝股份
True
2023-11-24 sz000809 铁岭新城
True
2023-11-24 sz000810 创维数字
True
2023-11-24 sz000811 冰轮环境
True
2023-11-24 sz000812 陕西金叶
True
2023-11-24 sz000813 德展健康
True
2023-11-24 sz000815 美利云
True
2023-11-24 sz000816 智慧农业
True
2023-11-24 sz000818 航锦科技
True
2023-11-24 sz000819 岳阳兴长
True
2023-11-24 sz000820 神雾节能
True
2023-11-24 sz000821 京山轻机
True
2023-11-24 sz000822 山东海化
True
2023-11-24 sz000823 超声电子
True
2023-11-24 sz000825 太钢不锈
True
2023-11-24 sz000826 启迪环境
True
2023-11-24 sz000828 东莞控股
True
2023-11-24 sz000829 天音控股
True
2023-11-24 sz000830 鲁西化工
True
2023-11-24 sz000831 中国稀土
True
2023-11-24 sz000833 粤桂股份
True
2023-11-24 sz000836 富通信息
True
2023-11-24 sz000837 秦川机床
True
2023-11-24 sz000838 财信发展
True
2023-11-24 sz000839 ST国安
True
2023-11-24 sz000848 承德露露
True
2023-11-24 sz000850 华茂股份
True
2023-11-24 sz000851 高鸿股份
True
2023-11-24 sz000852 石化机械
True
2023-11-24 sz000856 冀东装备
True
2023-11-24 sz000858 五 粮 液
True
2023-11-24 sz000859 国风新材
True
2023-11-24 sz000860 顺鑫农业
True
2023-11-24 sz000861 海印股份
True
2023-11-24 sz000862 银星能源
True
2023-11-24 sz000863 三湘印象
True
2023-11-24 sz000868 安凯客车
True
2023-11-24 sz000869 张 裕Ａ
True
2023-11-24 sz000875 吉电股份
True
2023-11-24 sz000876 新 希 望
True
2023-11-24 sz000877 天山股份
True
2023-11-24 sz000878 云南铜业
True
2023-11-24 sz000880 潍柴重机
True
2023-11-24 sz000881 中广核技
True
2023-11-24 sz000882 华联股份
True
2023-11-24 sz000883 湖北能源
True
2023-11-24 sz000885 城发环境
True
2023-11-24 sz000886 海南高速
True
2023-11-24 sz000887 中鼎股份
True
2023-11-24 sz000888 峨眉山Ａ
True
2023-11-24 sz000889 ST中嘉
True
2023-11-24 sz000890 法尔胜
True
2023-11-24 sz000892 欢瑞世纪
True
2023-11-24 sz000893 亚钾国际
True
2023-11-24 sz000895 双汇发展
True
2023-11-24 sz000897 津滨发展
True
2023-11-24 sz000898 鞍钢股份
True
2023-11-24 sz000899 赣能股份
True
2023-11-24 sz000900 现代投资
True
2023-11-24 sz000901 航天科技
True
2023-11-24 sz000902 新洋丰
True
2023-11-24 sz000903 云内动力
True
2023-11-24 sz000905 厦门港务
True
2023-11-24 sz000906 浙商中拓
True
2023-11-24 sz000908 景峰医药
True
2023-11-24 sz000909 ST数源
True
2023-11-24 sz000910 大亚圣象
True
2023-11-24 sz000911 广农糖业
True
2023-11-24 sz000912 泸天化
True
2023-11-24 sz000913 钱江摩托
True
2023-11-24 sz000915 华特达因
True
2023-11-24 sz000917 电广传媒
True
2023-11-24 sz000919 金陵药业
True
2023-11-24 sz000920 沃顿科技
True
2023-11-24 sz000921 海信家电
True
2023-11-24 sz000922 佳电股份
True
2023-11-24 sz000923 河钢资源
True
2023-11-24 sz000925 众合科技
True
2023-11-24 sz000926 福星股份
True
2023-11-24 sz000927 中国铁物
True
2023-11-24 sz000928 中钢国际
True
2023-11-24 sz000929 兰州黄河
True
2023-11-24 sz000930 中粮科技
True
2023-11-24 sz000931 中 关 村
True
2023-11-24 sz000932 华菱钢铁
True
2023-11-24 sz000933 神火股份
True
2023-11-24 sz000935 四川双马
True
2023-11-24 sz000936 华西股份
True
2023-11-24 sz000937 冀中能源
True
2023-11-24 sz000938 紫光股份
True
2023-11-24 sz000948 南天信息
True
2023-11-24 sz000949 新乡化纤
True
2023-11-24 sz000950 重药控股
True
2023-11-24 sz000951 中国重汽
True
2023-11-24 sz000952 广济药业
True
2023-11-24 sz000953 河化股份
True
2023-11-24 sz000955 欣龙控股
True
2023-11-24 sz000957 中通客车
True
2023-11-24 sz000958 电投产融
True
2023-11-24 sz000959 首钢股份
True
2023-11-24 sz000960 锡业股份
True
2023-11-24 sz000961 中南建设
True
2023-11-24 sz000962 东方钽业
True
2023-11-24 sz000963 华东医药
True
2023-11-24 sz000965 天保基建
True
2023-11-24 sz000966 长源电力
True
2023-11-24 sz000967 盈峰环境
True
2023-11-24 sz000968 蓝焰控股
True
2023-11-24 sz000969 安泰科技
True
2023-11-24 sz000970 中科三环
True
2023-11-24 sz000971 ST高升
True
2023-11-24 sz000972 中基健康
True
2023-11-24 sz000973 佛塑科技
True
2023-11-24 sz000975 银泰黄金
True
2023-11-24 sz000976 ST华铁
True
2023-11-24 sz000977 浪潮信息
True
2023-11-24 sz000978 桂林旅游
True
2023-11-24 sz000980 众泰汽车
True
2023-11-24 sz000981 山子股份
True
2023-11-24 sz000982 中银绒业
True
2023-11-24 sz000983 山西焦煤
True
2023-11-24 sz000985 大庆华科
True
2023-11-24 sz000987 越秀资本
True
2023-11-24 sz000988 华工科技
True
2023-11-24 sz000989 九 芝 堂
True
2023-11-24 sz000990 诚志股份
True
2023-11-24 sz000993 闽东电力
True
2023-11-24 sz000995 皇台酒业
True
2023-11-24 sz000996 *ST中期
True
2023-11-24 sz000997 新 大 陆
True
2023-11-24 sz000998 隆平高科
True
2023-11-24 sz000999 华润三九
True
2023-11-24 sz001201 东瑞股份
True
2023-11-24 sz001202 炬申股份
True
2023-11-24 sz001203 大中矿业
True
2023-11-24 sz001205 盛航股份
True
2023-11-24 sz001206 依依股份
True
2023-11-24 sz001207 联科科技
True
2023-11-24 sz001208 华菱线缆
True
2023-11-24 sz001209 洪兴股份
True
2023-11-24 sz001210 金房能源
True
2023-11-24 sz001211 双枪科技
True
2023-11-24 sz001212 中旗新材
True
2023-11-24 sz001213 中铁特货
True
2023-11-24 sz001215 千味央厨
True
2023-11-24 sz001216 华瓷股份
True
2023-11-24 sz001217 华尔泰
True
2023-11-24 sz001218 丽臣实业
True
2023-11-24 sz001219 青岛食品
True
2023-11-24 sz001222 源飞宠物
True
2023-11-24 sz001223 欧克科技
True
2023-11-24 sz001225 和泰机电
True
2023-11-24 sz001226 拓山重工
True
2023-11-24 sz001227 兰州银行
True
2023-11-24 sz001228 永泰运
True
2023-11-24 sz001229 魅视科技
True
2023-11-24 sz001230 劲旅环境
True
2023-11-24 sz001231 农心科技
True
2023-11-24 sz001234 泰慕士
True
2023-11-24 sz001236 弘业期货
True
2023-11-24 sz001238 浙江正特
True
2023-11-24 sz001255 博菲电气
True
2023-11-24 sz001256 炜冈科技
True
2023-11-24 sz001258 立新能源
True
2023-11-24 sz001259 利仁科技
True
2023-11-24 sz001260 坤泰股份
True
2023-11-24 sz001266 宏英智能
True
2023-11-24 sz001267 汇绿生态
True
2023-11-24 sz001268 联合精密
True
2023-11-24 sz001269 欧晶科技
True
2023-11-24 sz001270 铖昌科技
True
2023-11-24 sz001278 一彬科技
True
2023-11-24 sz001282 三联锻造
True
2023-11-24 sz001283 豪鹏科技
True
2023-11-24 sz001286 陕西能源
True
2023-11-24 sz001287 中电港
True
2023-11-24 sz001288 运机集团
True
2023-11-24 sz001289 龙源电力
True
2023-11-24 sz001296 长江材料
True
2023-11-24 sz001298 好上好
True
2023-11-24 sz001299 美能能源
True
2023-11-24 sz001300 三柏硕
True
2023-11-24 sz001301 尚太科技
True
2023-11-24 sz001306 C夏厦
True
2023-11-24 sz001308 康冠科技
True
2023-11-24 sz001309 德明利
True
2023-11-24 sz001311 多利科技
True
2023-11-24 sz001313 粤海饲料
True
2023-11-24 sz001314 亿道信息
True
2023-11-24 sz001316 润贝航科
True
2023-11-24 sz001317 三羊马
True
2023-11-24 sz001318 阳光乳业
True
2023-11-24 sz001319 铭科精技
True
2023-11-24 sz001322 箭牌家居
True
2023-11-24 sz001323 慕思股份
True
2023-11-24 sz001324 长青科技
True
2023-11-24 sz001326 联域股份
True
2023-11-24 sz001328 登康口腔
True
2023-11-24 sz001330 博纳影业
True
2023-11-24 sz001331 胜通能源
True
2023-11-24 sz001332 锡装股份
True
2023-11-24 sz001333 光华股份
True
2023-11-24 sz001336 楚环科技
True
2023-11-24 sz001337 四川黄金
True
2023-11-24 sz001338 永顺泰
True
2023-11-24 sz001339 智微智能
True
2023-11-24 sz001360 南矿集团
True
2023-11-24 sz001366 播恩集团
True
2023-11-24 sz001367 海森药业
True
2023-11-24 sz001368 通达创智
True
2023-11-24 sz001373 翔腾新材
True
2023-11-24 sz001376 百通能源
True
2023-11-24 sz001378 德冠新材
True
2023-11-24 sz001380 华纬科技
True
2023-11-24 sz001696 宗申动力
True
2023-11-24 sz001872 招商港口
True
2023-11-24 sz001896 豫能控股
True
2023-11-24 sz001914 招商积余
True
2023-11-24 sz001965 招商公路
True
2023-11-24 sz001979 招商蛇口
True
2023-11-24 sz002001 新 和 成
True
2023-11-24 sz002002 ST鸿达
True
2023-11-24 sz002003 伟星股份
True
2023-11-24 sz002004 华邦健康
True
2023-11-24 sz002005 ST德豪
True
2023-11-24 sz002006 精工科技
True
2023-11-24 sz002007 华兰生物
True
2023-11-24 sz002008 大族激光
True
2023-11-24 sz002009 天奇股份
True
2023-11-24 sz002010 传化智联
True
2023-11-24 sz002011 盾安环境
True
2023-11-24 sz002012 凯恩股份
True
2023-11-24 sz002014 永新股份
True
2023-11-24 sz002015 协鑫能科
True
2023-11-24 sz002016 世荣兆业
True
2023-11-24 sz002017 东信和平
True
2023-11-24 sz002019 亿帆医药
True
2023-11-24 sz002020 京新药业
True
2023-11-24 sz002021 *ST中捷
True
2023-11-24 sz002022 科华生物
True
2023-11-24 sz002023 海特高新
True
2023-11-24 sz002024 ST易购
True
2023-11-24 sz002025 航天电器
True
2023-11-24 sz002026 山东威达
True
2023-11-24 sz002027 分众传媒
True
2023-11-24 sz002028 思源电气
True
2023-11-24 sz002029 七 匹 狼
True
2023-11-24 sz002030 达安基因
True
2023-11-24 sz002031 巨轮智能
True
2023-11-24 sz002032 苏 泊 尔
True
2023-11-24 sz002033 丽江股份
True
2023-11-24 sz002034 旺能环境
True
2023-11-24 sz002035 华帝股份
True
2023-11-24 sz002036 联创电子
True
2023-11-24 sz002037 保利联合
True
2023-11-24 sz002038 双鹭药业
True
2023-11-24 sz002039 黔源电力
True
2023-11-24 sz002040 南 京 港
True
2023-11-24 sz002041 登海种业
True
2023-11-24 sz002042 华孚时尚
True
2023-11-24 sz002043 兔 宝 宝
True
2023-11-24 sz002044 美年健康
True
2023-11-24 sz002045 国光电器
True
2023-11-24 sz002046 国机精工
True
2023-11-24 sz002047 宝鹰股份
True
2023-11-24 sz002048 宁波华翔
True
2023-11-24 sz002049 紫光国微
True
2023-11-24 sz002050 三花智控
True
2023-11-24 sz002051 中工国际
True
2023-11-24 sz002052 ST同洲
True
2023-11-24 sz002053 云南能投
True
2023-11-24 sz002054 德美化工
True
2023-11-24 sz002055 得润电子
True
2023-11-24 sz002056 横店东磁
True
2023-11-24 sz002057 中钢天源
True
2023-11-24 sz002058 威尔泰
True
2023-11-24 sz002059 云南旅游
True
2023-11-24 sz002060 粤 水 电
True
2023-11-24 sz002061 浙江交科
True
2023-11-24 sz002062 宏润建设
True
2023-11-24 sz002063 远光软件
True
2023-11-24 sz002064 华峰化学
True
2023-11-24 sz002065 东华软件
True
2023-11-24 sz002066 瑞泰科技
True

./1min_DFCF/sz300223.csv
2023-11-24 sz300224 正海磁材
True
2023-11-24 sz300225 金力泰
True
2023-11-24 sz300226 上海钢联
True
2023-11-24 sz300227 光韵达
True
2023-11-24 sz300228 富瑞特装
True
2023-11-24 sz300229 拓尔思
True
2023-11-24 sz300230 永利股份
True
2023-11-24 sz300231 银信科技
True
2023-11-24 sz300232 洲明科技
True
2023-11-24 sz300233 金城医药
True
2023-11-24 sz300234 开尔新材
True
2023-11-24 sz300235 方直科技
True
2023-11-24 sz300236 上海新阳
True
2023-11-24 sz300237 美晨生态
True
2023-11-24 sz300238 冠昊生物
True
2023-11-24 sz300239 东宝生物
True
2023-11-24 sz300240 飞力达
True
2023-11-24 sz300241 瑞丰光电
True
2023-11-24 sz300242 佳云科技
True
2023-11-24 sz300243 瑞丰高材
True
2023-11-24 sz300244 迪安诊断
True
2023-11-24 sz300245 天玑科技
True
2023-11-24 sz300246 宝莱特
True
2023-11-24 sz300247 融捷健康
True
2023-11-24 sz300248 新开普
True
2023-11-24 sz300249 依米康
True
2023-11-24 sz300250 初灵信息
True
2023-11-24 sz300251 光线传媒
True
2023-11-24 sz300252 金信诺
True
2023-11-24 sz300253 卫宁健康
True
2023-11-24 sz300254 仟源医药
True
2023-11-24 sz300255 常山药业
True
2023-11-24 sz300256 星星科技
True
2023-11-24 sz300257 开山股份
True
2023-11-24 sz300258 精锻科技
True
2023-11-24 sz300259 新天科技
True
2023-11-24 sz300260 新莱应材
True
2023-11-24 sz300261 雅本化学
True
2023-11-24 sz300262 巴安水务
True
2023-11-24 sz300263 隆华科技
True
2023-11-24 sz300264 佳创视讯
True
2023-11-24 sz300265 通光线缆
True
2023-11-24 sz300266 兴源环境
True
2023-11-24 sz300267 尔康制药
True
2023-11-24 sz300268 *ST佳沃
True
2023-11-24 sz300269 联建光电
True
2023-11-24 sz300270 中威电子
True
2023-11-24 sz300271 华宇软件
True
2023-11-24 sz300272 开能健康
True
2023-11-24 sz300274 阳光电源
True
2023-11-24 sz300275 梅安森
True
2023-11-24 sz300276 三丰智能
True
2023-11-24 sz300277 海联讯
True
2023-11-24 sz300278 华昌达
True
2023-11-24 sz300279 和晶科技
True
2023-11-24 sz300280 紫天科技
True
2023-11-24 sz300281 金明精机
True
2023-11-24 sz300282 *ST三盛
True
2023-11-24 sz300283 温州宏丰
True
2023-11-24 sz300284 苏交科
True
2023-11-24 sz300285 国瓷材料
True
2023-11-24 sz300286 安科瑞
True
2023-11-24 sz300287 飞利信
True
2023-11-24 sz300288 朗玛信息
True
2023-11-24 sz300289 利德曼
True
2023-11-24 sz300290 荣科科技
True
2023-11-24 sz300291 百纳千成
True
2023-11-24 sz300292 吴通控股
True
2023-11-24 sz300293 蓝英装备
True
2023-11-24 sz300294 博雅生物
True
2023-11-24 sz300295 三六五网
True
2023-11-24 sz300296 利亚德
True
2023-11-24 sz300298 三诺生物
True
2023-11-24 sz300299 富春股份
True
2023-11-24 sz300300 海峡创新
True
2023-11-24 sz300301 *ST长方
True
2023-11-24 sz300302 同有科技
True
2023-11-24 sz300303 聚飞光电
True
2023-11-24 sz300304 云意电气
True
2023-11-24 sz300305 裕兴股份
True
2023-11-24 sz300306 远方信息
True
2023-11-24 sz300307 慈星股份
True
2023-11-24 sz300308 中际旭创
True
2023-11-24 sz300310 宜通世纪
True
2023-11-24 sz300311 任子行
True
2023-11-24 sz300313 *ST天山
True
2023-11-24 sz300314 戴维医疗
True
2023-11-24 sz300315 掌趣科技
True
2023-11-24 sz300316 晶盛机电
True
2023-11-24 sz300317 珈伟新能
True
2023-11-24 sz300318 博晖创新
True
2023-11-24 sz300319 麦捷科技
True
2023-11-24 sz300320 海达股份
True
2023-11-24 sz300321 同大股份
True
2023-11-24 sz300322 硕贝德
True
2023-11-24 sz300323 华灿光电
True
2023-11-24 sz300324 旋极信息
True
2023-11-24 sz300326 凯利泰
True
2023-11-24 sz300327 中颖电子
True
2023-11-24 sz300328 宜安科技
True
2023-11-24 sz300329 海伦钢琴
True
2023-11-24 sz300331 苏大维格
True
2023-11-24 sz300332 天壕能源
True
2023-11-24 sz300333 兆日科技
True
2023-11-24 sz300334 津膜科技
True
2023-11-24 sz300335 迪森股份
True
2023-11-24 sz300337 银邦股份
True
2023-11-24 sz300338 开元教育
True
2023-11-24 sz300339 润和软件
True
2023-11-24 sz300340 科恒股份
True
2023-11-24 sz300341 麦克奥迪
True
2023-11-24 sz300342 天银机电
True
2023-11-24 sz300343 联创股份
True
2023-11-24 sz300344 立方数科
True
2023-11-24 sz300345 华民股份
True
2023-11-24 sz300346 南大光电
True
2023-11-24 sz300347 泰格医药
True
2023-11-24 sz300348 长亮科技
True
2023-11-24 sz300349 金卡智能
True
2023-11-24 sz300350 华鹏飞
True
2023-11-24 sz300351 永贵电器
True
2023-11-24 sz300352 北信源
True
2023-11-24 sz300353 东土科技
True
2023-11-24 sz300354 东华测试
True
2023-11-24 sz300355 蒙草生态
True
2023-11-24 sz300357 我武生物
True
2023-11-24 sz300358 楚天科技
True
2023-11-24 sz300359 全通教育
True
2023-11-24 sz300360 炬华科技
True
2023-11-24 sz300363 博腾股份
True
2023-11-24 sz300364 中文在线
True
2023-11-24 sz300365 恒华科技
True
2023-11-24 sz300366 创意信息
True
2023-11-24 sz300368 汇金股份
True
2023-11-24 sz300369 绿盟科技
True
2023-11-24 sz300370 安控科技
True
2023-11-24 sz300371 汇中股份
True
2023-11-24 sz300373 扬杰科技
True
2023-11-24 sz300374 中铁装配
True
2023-11-24 sz300375 鹏翎股份
True
2023-11-24 sz300376 易事特
True
2023-11-24 sz300377 赢时胜
True
2023-11-24 sz300378 鼎捷软件
True
2023-11-24 sz300379 东方通
True
2023-11-24 sz300380 安硕信息
True
2023-11-24 sz300381 溢多利
True
2023-11-24 sz300382 斯莱克
True
2023-11-24 sz300383 光环新网
True
2023-11-24 sz300384 三联虹普
True
2023-11-24 sz300385 雪浪环境
True
2023-11-24 sz300386 飞天诚信
True
2023-11-24 sz300387 富邦股份
True
2023-11-24 sz300388 节能国祯
True
2023-11-24 sz300389 艾比森
True
2023-11-24 sz300390 天华新能
True
2023-11-24 sz300391 长药控股
True
2023-11-24 sz300393 中来股份
True
2023-11-24 sz300394 天孚通信
True
2023-11-24 sz300395 菲利华
True
2023-11-24 sz300396 迪瑞医疗
True
2023-11-24 sz300397 天和防务
True
2023-11-24 sz300398 飞凯材料
True
2023-11-24 sz300399 天利科技
True
2023-11-24 sz300400 劲拓股份
True
2023-11-24 sz300401 花园生物
True
2023-11-24 sz300402 宝色股份
True
2023-11-24 sz300403 汉宇集团
True
2023-11-24 sz300404 博济医药
True
2023-11-24 sz300405 科隆股份
True
2023-11-24 sz300406 九强生物
True
2023-11-24 sz300407 凯发电气
True
2023-11-24 sz300408 三环集团
True
2023-11-24 sz300409 道氏技术
True
2023-11-24 sz300410 正业科技
True
2023-11-24 sz300411 金盾股份
True
2023-11-24 sz300412 迦南科技
True
2023-11-24 sz300413 芒果超媒
True
2023-11-24 sz300414 中光防雷
True
2023-11-24 sz300415 伊之密
True
2023-11-24 sz300416 苏试试验
True
2023-11-24 sz300417 南华仪器
True
2023-11-24 sz300418 昆仑万维
True
2023-11-24 sz300419 浩丰科技
True
2023-11-24 sz300420 五洋停车
True
2023-11-24 sz300421 力星股份
True
2023-11-24 sz300422 博世科
True
2023-11-24 sz300423 昇辉科技
True
2023-11-24 sz300424 航新科技
True
2023-11-24 sz300425 中建环能
True
2023-11-24 sz300426 唐德影视
./1min_DFCF/sz300426.csv
2023-11-24 sz300427 *ST红相
True
2023-11-24 sz300428 立中集团
True
2023-11-24 sz300429 强力新材
True
2023-11-24 sz300430 诚益通
True
2023-11-24 sz300432 富临精工
True
2023-11-24 sz300433 蓝思科技
True
2023-11-24 sz300434 金石亚药
True
2023-11-24 sz300435 中泰股份
True
2023-11-24 sz300436 广生堂
True
2023-11-24 sz300437 清水源
True
2023-11-24 sz300438 鹏辉能源
True
2023-11-24 sz300439 美康生物
True
2023-11-24 sz300440 运达科技
True
2023-11-24 sz300441 鲍斯股份
True
2023-11-24 sz300442 润泽科技
True
2023-11-24 sz300443 金雷股份
True
2023-11-24 sz300444 双杰电气
True
2023-11-24 sz300445 康斯特
True
2023-11-24 sz300446 航天智造
True
2023-11-24 sz300447 全信股份
True
2023-11-24 sz300448 浩云科技
True
2023-11-24 sz300449 汉邦高科
True
2023-11-24 sz300450 先导智能
True
2023-11-24 sz300451 创业慧康
True
2023-11-24 sz300452 山河药辅
True
2023-11-24 sz300453 三鑫医疗
True
2023-11-24 sz300454 深信服
True
2023-11-24 sz300455 航天智装
True
2023-11-24 sz300456 赛微电子
True
2023-11-24 sz300457 赢合科技
True
2023-11-24 sz300458 全志科技
True
2023-11-24 sz300459 汤姆猫
True
2023-11-24 sz300460 惠伦晶体
True
2023-11-24 sz300461 田中精机
True
2023-11-24 sz300462 华铭智能
True
2023-11-24 sz300463 迈克生物
True
2023-11-24 sz300464 星徽股份
True
2023-11-24 sz300465 高伟达
True
2023-11-24 sz300466 赛摩智能
True
2023-11-24 sz300467 迅游科技
True
2023-11-24 sz300468 四方精创
True
2023-11-24 sz300469 信息发展
True
2023-11-24 sz300470 中密控股
True
2023-11-24 sz300471 厚普股份
True
2023-11-24 sz300472 新元科技
True
2023-11-24 sz300473 德尔股份
True
2023-11-24 sz300474 景嘉微
True
2023-11-24 sz300475 香农芯创
True
2023-11-24 sz300476 胜宏科技
True
2023-11-24 sz300477 合纵科技
True
2023-11-24 sz300478 杭州高新
True
2023-11-24 sz300479 神思电子
True
2023-11-24 sz300480 光力科技
True
2023-11-24 sz300481 濮阳惠成
True
2023-11-24 sz300482 万孚生物
True
2023-11-24 sz300483 首华燃气
./1min_DFCF/sz300483.csv
2023-11-24 sz300484 蓝海华腾
./1min_DFCF/sz300484.csv
2023-11-24 sz300485 赛升药业
./1min_DFCF/sz300485.csv
2023-11-24 sz300486 东杰智能
./1min_DFCF/sz300486.csv
2023-11-24 sz300487 蓝晓科技
./1min_DFCF/sz300487.csv
2023-11-24 sz300488 恒锋工具
./1min_DFCF/sz300488.csv
2023-11-24 sz300489 光智科技
./1min_DFCF/sz300489.csv
2023-11-24 sz300490 华自科技
./1min_DFCF/sz300490.csv
2023-11-24 sz300491 通合科技
./1min_DFCF/sz300491.csv
2023-11-24 sz300492 华图山鼎
./1min_DFCF/sz300492.csv
2023-11-24 sz300493 润欣科技
./1min_DFCF/sz300493.csv
2023-11-24 sz300494 盛天网络
./1min_DFCF/sz300494.csv
2023-11-24 sz300495 *ST美尚
./1min_DFCF/sz300495.csv
2023-11-24 sz300496 中科创达
./1min_DFCF/sz300496.csv
2023-11-24 sz300497 富祥药业
./1min_DFCF/sz300497.csv
2023-11-24 sz300498 温氏股份
./1min_DFCF/sz300498.csv
2023-11-24 sz300499 高澜股份
./1min_DFCF/sz300499.csv
2023-11-24 sz300500 启迪设计

./1min_DFCF/sz300500.csv
2023-11-24 sz300501 海顺新材
./1min_DFCF/sz300501.csv
2023-11-24 sz300502 新易盛
./1min_DFCF/sz300502.csv
2023-11-24 sz300503 昊志机电
./1min_DFCF/sz300503.csv
2023-11-24 sz300504 天邑股份
./1min_DFCF/sz300504.csv
2023-11-24 sz300505 川金诺
./1min_DFCF/sz300505.csv
2023-11-24 sz300506 名家汇
./1min_DFCF/sz300506.csv
2023-11-24 sz300507 苏奥传感
./1min_DFCF/sz300507.csv
2023-11-24 sz300508 维宏股份
./1min_DFCF/sz300508.csv
2023-11-24 sz300509 新美星
./1min_DFCF/sz300509.csv
2023-11-24 sz300510 金冠股份
./1min_DFCF/sz300510.csv
2023-11-24 sz300511 雪榕生物
./1min_DFCF/sz300511.csv
2023-11-24 sz300512 中亚股份
./1min_DFCF/sz300512.csv
2023-11-24 sz300513 恒实科技
./1min_DFCF/sz300513.csv
2023-11-24 sz300514 友讯达
./1min_DFCF/sz300514.csv
2023-11-24 sz300515 三德科技
./1min_DFCF/sz300515.csv
2023-11-24 sz300516 久之洋
./1min_DFCF/sz300516.csv
2023-11-24 sz300517 海波重科
./1min_DFCF/sz300517.csv
2023-11-24 sz300518 新迅达
./1min_DFCF/sz300518.csv
2023-11-24 sz300519 新光药业
./1min_DFCF/sz300519.csv
2023-11-24 sz300520 科大国创
./1min_DFCF/sz300520.csv
2023-11-24 sz300521 爱司凯
./1min_DFCF/sz300521.csv
2023-11-24 sz300522 世名科技
./1min_DFCF/sz300522.csv
2023-11-24 sz300523 辰安科技
./1min_DFCF/sz300523.csv
2023-11-24 sz300525 博思软件
./1min_DFCF/sz300525.csv
2023-11-24 sz300527 中船应急
./1min_DFCF/sz300527.csv
2023-11-24 sz300528 幸福蓝海
./1min_DFCF/sz300528.csv
2023-11-24 sz300529 健帆生物
./1min_DFCF/sz300529.csv
2023-11-24 sz300530 领湃科技
./1min_DFCF/sz300530.csv
2023-11-24 sz300531 优博讯
./1min_DFCF/sz300531.csv
2023-11-24 sz300532 今天国际
./1min_DFCF/sz300532.csv
2023-11-24 sz300533 冰川网络
./1min_DFCF/sz300533.csv
2023-11-24 sz300534 陇神戎发
./1min_DFCF/sz300534.csv
2023-11-24 sz300535 达威股份
./1min_DFCF/sz300535.csv
2023-11-24 sz300536 农尚环境
./1min_DFCF/sz300536.csv
2023-11-24 sz300537 广信材料
./1min_DFCF/sz300537.csv
2023-11-24 sz300538 同益股份
./1min_DFCF/sz300538.csv
2023-11-24 sz300539 横河精密
./1min_DFCF/sz300539.csv
2023-11-24 sz300540 蜀道装备
./1min_DFCF/sz300540.csv
2023-11-24 sz300541 先进数通
./1min_DFCF/sz300541.csv
2023-11-24 sz300542 新晨科技
./1min_DFCF/sz300542.csv
2023-11-24 sz300543 朗科智能
./1min_DFCF/sz300543.csv
2023-11-24 sz300545 联得装备
./1min_DFCF/sz300545.csv
2023-11-24 sz300546 雄帝科技
./1min_DFCF/sz300546.csv
2023-11-24 sz300547 川环科技
./1min_DFCF/sz300547.csv
2023-11-24 sz300548 博创科技
./1min_DFCF/sz300548.csv
2023-11-24 sz300549 优德精密
./1min_DFCF/sz300549.csv
2023-11-24 sz300550 和仁科技
./1min_DFCF/sz300550.csv
2023-11-24 sz300551 古鳌科技
./1min_DFCF/sz300551.csv
2023-11-24 sz300552 万集科技
./1min_DFCF/sz300552.csv
2023-11-24 sz300553 集智股份
./1min_DFCF/sz300553.csv
2023-11-24 sz300554 三超新材
./1min_DFCF/sz300554.csv
2023-11-24 sz300555 ST路通
./1min_DFCF/sz300555.csv
2023-11-24 sz300556 丝路视觉
./1min_DFCF/sz300556.csv
2023-11-24 sz300557 理工光科
./1min_DFCF/sz300557.csv
2023-11-24 sz300558 贝达药业
./1min_DFCF/sz300558.csv
2023-11-24 sz300559 佳发教育
./1min_DFCF/sz300559.csv
2023-11-24 sz300560 中富通
./1min_DFCF/sz300560.csv
2023-11-24 sz300561 汇金科技
./1min_DFCF/sz300561.csv
2023-11-24 sz300562 乐心医疗
./1min_DFCF/sz300562.csv
2023-11-24 sz300563 神宇股份
./1min_DFCF/sz300563.csv
2023-11-24 sz300564 筑博设计
./1min_DFCF/sz300564.csv
2023-11-24 sz300565 科信技术
./1min_DFCF/sz300565.csv
2023-11-24 sz300566 激智科技
./1min_DFCF/sz300566.csv
2023-11-24 sz300567 精测电子
./1min_DFCF/sz300567.csv
2023-11-24 sz300568 星源材质
./1min_DFCF/sz300568.csv
2023-11-24 sz300569 天能重工
./1min_DFCF/sz300569.csv
2023-11-24 sz300570 太辰光
./1min_DFCF/sz300570.csv
2023-11-24 sz300571 平治信息
./1min_DFCF/sz300571.csv
2023-11-24 sz300572 安车检测
./1min_DFCF/sz300572.csv
2023-11-24 sz300573 兴齐眼药
./1min_DFCF/sz300573.csv
2023-11-24 sz300575 中旗股份
./1min_DFCF/sz300575.csv
2023-11-24 sz300576 容大感光
./1min_DFCF/sz300576.csv
2023-11-24 sz300577 开润股份
./1min_DFCF/sz300577.csv
2023-11-24 sz300578 会畅通讯
./1min_DFCF/sz300578.csv
2023-11-24 sz300579 数字认证
./1min_DFCF/sz300579.csv
2023-11-24 sz300580 贝斯特
./1min_DFCF/sz300580.csv
2023-11-24 sz300581 晨曦航空
./1min_DFCF/sz300581.csv
2023-11-24 sz300582 英飞特
./1min_DFCF/sz300582.csv
2023-11-24 sz300583 赛托生物
./1min_DFCF/sz300583.csv
2023-11-24 sz300584 海辰药业
./1min_DFCF/sz300584.csv
2023-11-24 sz300585 奥联电子
./1min_DFCF/sz300585.csv
2023-11-24 sz300586 美联新材
./1min_DFCF/sz300586.csv
2023-11-24 sz300587 天铁股份
./1min_DFCF/sz300587.csv
2023-11-24 sz300588 熙菱信息
./1min_DFCF/sz300588.csv
2023-11-24 sz300589 江龙船艇
./1min_DFCF/sz300589.csv
2023-11-24 sz300590 移为通信
./1min_DFCF/sz300590.csv
2023-11-24 sz300591 万里马
./1min_DFCF/sz300591.csv
2023-11-24 sz300592 华凯易佰
./1min_DFCF/sz300592.csv
2023-11-24 sz300593 新雷能
./1min_DFCF/sz300593.csv
2023-11-24 sz300594 朗进科技
./1min_DFCF/sz300594.csv
2023-11-24 sz300595 欧普康视
./1min_DFCF/sz300595.csv
2023-11-24 sz300596 利安隆
./1min_DFCF/sz300596.csv
2023-11-24 sz300597 吉大通信
./1min_DFCF/sz300597.csv
2023-11-24 sz300598 诚迈科技
./1min_DFCF/sz300598.csv
2023-11-24 sz300599 雄塑科技
./1min_DFCF/sz300599.csv
2023-11-24 sz300600 国瑞科技
./1min_DFCF/sz300600.csv
2023-11-24 sz300601 康泰生物
./1min_DFCF/sz300601.csv
2023-11-24 sz300602 飞荣达
./1min_DFCF/sz300602.csv
2023-11-24 sz300603 立昂技术
./1min_DFCF/sz300603.csv
2023-11-24 sz300604 长川科技
./1min_DFCF/sz300604.csv
2023-11-24 sz300605 恒锋信息
./1min_DFCF/sz300605.csv
2023-11-24 sz300606 金太阳
./1min_DFCF/sz300606.csv
2023-11-24 sz300607 拓斯达
./1min_DFCF/sz300607.csv
2023-11-24 sz300608 思特奇
./1min_DFCF/sz300608.csv
2023-11-24 sz300609 汇纳科技
./1min_DFCF/sz300609.csv
2023-11-24 sz300610 晨化股份
./1min_DFCF/sz300610.csv
2023-11-24 sz300611 美力科技
./1min_DFCF/sz300611.csv
2023-11-24 sz300612 宣亚国际
./1min_DFCF/sz300612.csv
2023-11-24 sz300613 富瀚微
./1min_DFCF/sz300613.csv
2023-11-24 sz300614 百川畅银
./1min_DFCF/sz300614.csv
2023-11-24 sz300615 欣天科技
./1min_DFCF/sz300615.csv
2023-11-24 sz300616 尚品宅配
./1min_DFCF/sz300616.csv
2023-11-24 sz300617 安靠智电
./1min_DFCF/sz300617.csv
2023-11-24 sz300618 寒锐钴业
./1min_DFCF/sz300618.csv
2023-11-24 sz300619 金银河
./1min_DFCF/sz300619.csv
2023-11-24 sz300620 光库科技
./1min_DFCF/sz300620.csv
2023-11-24 sz300621 维业股份
./1min_DFCF/sz300621.csv
2023-11-24 sz300622 博士眼镜
./1min_DFCF/sz300622.csv
2023-11-24 sz300623 捷捷微电
./1min_DFCF/sz300623.csv
2023-11-24 sz300624 万兴科技
./1min_DFCF/sz300624.csv
2023-11-24 sz300625 三雄极光
./1min_DFCF/sz300625.csv
2023-11-24 sz300626 华瑞股份
./1min_DFCF/sz300626.csv
2023-11-24 sz300627 华测导航
./1min_DFCF/sz300627.csv
2023-11-24 sz300628 亿联网络
./1min_DFCF/sz300628.csv
2023-11-24 sz300629 新劲刚
./1min_DFCF/sz300629.csv
2023-11-24 sz300630 普利制药
./1min_DFCF/sz300630.csv
2023-11-24 sz300631 久吾高科
./1min_DFCF/sz300631.csv
2023-11-24 sz300632 光莆股份
./1min_DFCF/sz300632.csv
2023-11-24 sz300633 开立医疗
./1min_DFCF/sz300633.csv
2023-11-24 sz300634 彩讯股份
./1min_DFCF/sz300634.csv
2023-11-24 sz300635 中达安
./1min_DFCF/sz300635.csv
2023-11-24 sz300636 同和药业
./1min_DFCF/sz300636.csv
2023-11-24 sz300637 扬帆新材
./1min_DFCF/sz300637.csv
2023-11-24 sz300638 广和通
./1min_DFCF/sz300638.csv
2023-11-24 sz300639 凯普生物
./1min_DFCF/sz300639.csv
2023-11-24 sz300640 德艺文创
./1min_DFCF/sz300640.csv
2023-11-24 sz300641 正丹股份
./1min_DFCF/sz300641.csv
2023-11-24 sz300642 透景生命
./1min_DFCF/sz300642.csv
2023-11-24 sz300643 万通智控
./1min_DFCF/sz300643.csv
2023-11-24 sz300644 南京聚隆
./1min_DFCF/sz300644.csv
2023-11-24 sz300645 正元智慧
./1min_DFCF/sz300645.csv
2023-11-24 sz300647 超频三
./1min_DFCF/sz300647.csv
2023-11-24 sz300648 星云股份
./1min_DFCF/sz300648.csv
2023-11-24 sz300649 杭州园林
./1min_DFCF/sz300649.csv
2023-11-24 sz300650 太龙股份
./1min_DFCF/sz300650.csv
2023-11-24 sz300651 金陵体育
./1min_DFCF/sz300651.csv
2023-11-24 sz300652 雷迪克
./1min_DFCF/sz300652.csv
2023-11-24 sz300653 正海生物
./1min_DFCF/sz300653.csv
2023-11-24 sz300654 世纪天鸿
./1min_DFCF/sz300654.csv
2023-11-24 sz300655 晶瑞电材
./1min_DFCF/sz300655.csv
2023-11-24 sz300656 民德电子
./1min_DFCF/sz300656.csv
2023-11-24 sz300657 弘信电子
./1min_DFCF/sz300657.csv
2023-11-24 sz300658 延江股份
./1min_DFCF/sz300658.csv
2023-11-24 sz300659 中孚信息
./1min_DFCF/sz300659.csv
2023-11-24 sz300660 江苏雷利
./1min_DFCF/sz300660.csv
2023-11-24 sz300661 圣邦股份
./1min_DFCF/sz300661.csv
2023-11-24 sz300662 科锐国际
./1min_DFCF/sz300662.csv
2023-11-24 sz300663 科蓝软件
./1min_DFCF/sz300663.csv
2023-11-24 sz300664 鹏鹞环保
./1min_DFCF/sz300664.csv
2023-11-24 sz300665 飞鹿股份
./1min_DFCF/sz300665.csv
2023-11-24 sz300666 江丰电子
./1min_DFCF/sz300666.csv
2023-11-24 sz300667 必创科技
./1min_DFCF/sz300667.csv
2023-11-24 sz300668 杰恩设计
./1min_DFCF/sz300668.csv
2023-11-24 sz300669 沪宁股份
./1min_DFCF/sz300669.csv
2023-11-24 sz300670 大烨智能

./1min_DFCF/sz300670.csv
2023-11-24 sz300671 富满微
./1min_DFCF/sz300671.csv
2023-11-24 sz300672 国科微
./1min_DFCF/sz300672.csv
2023-11-24 sz300673 佩蒂股份
./1min_DFCF/sz300673.csv
2023-11-24 sz300674 宇信科技
./1min_DFCF/sz300674.csv
2023-11-24 sz300675 建科院
./1min_DFCF/sz300675.csv
2023-11-24 sz300676 华大基因
./1min_DFCF/sz300676.csv
2023-11-24 sz300677 英科医疗
./1min_DFCF/sz300677.csv
2023-11-24 sz300678 中科信息
./1min_DFCF/sz300678.csv
2023-11-24 sz300679 电连技术
./1min_DFCF/sz300679.csv
2023-11-24 sz300680 隆盛科技
./1min_DFCF/sz300680.csv
2023-11-24 sz300681 英搏尔
./1min_DFCF/sz300681.csv
2023-11-24 sz300682 朗新科技
./1min_DFCF/sz300682.csv
2023-11-24 sz300683 海特生物
./1min_DFCF/sz300683.csv
2023-11-24 sz300684 中石科技
./1min_DFCF/sz300684.csv
2023-11-24 sz300685 艾德生物
./1min_DFCF/sz300685.csv
2023-11-24 sz300686 智动力
./1min_DFCF/sz300686.csv
2023-11-24 sz300687 赛意信息
./1min_DFCF/sz300687.csv
2023-11-24 sz300688 创业黑马
./1min_DFCF/sz300688.csv
2023-11-24 sz300689 澄天伟业
./1min_DFCF/sz300689.csv
2023-11-24 sz300690 双一科技
./1min_DFCF/sz300690.csv
2023-11-24 sz300691 联合光电
./1min_DFCF/sz300691.csv
2023-11-24 sz300692 中环环保
./1min_DFCF/sz300692.csv
2023-11-24 sz300693 盛弘股份
./1min_DFCF/sz300693.csv
2023-11-24 sz300694 蠡湖股份
./1min_DFCF/sz300694.csv
2023-11-24 sz300695 兆丰股份
./1min_DFCF/sz300695.csv
2023-11-24 sz300696 爱乐达
./1min_DFCF/sz300696.csv
2023-11-24 sz300697 电工合金
./1min_DFCF/sz300697.csv
2023-11-24 sz300698 万马科技
./1min_DFCF/sz300698.csv
2023-11-24 sz300699 光威复材
./1min_DFCF/sz300699.csv
2023-11-24 sz300700 岱勒新材
./1min_DFCF/sz300700.csv
2023-11-24 sz300701 森霸传感
./1min_DFCF/sz300701.csv
2023-11-24 sz300702 天宇股份
./1min_DFCF/sz300702.csv
2023-11-24 sz300703 创源股份
./1min_DFCF/sz300703.csv
2023-11-24 sz300705 九典制药
./1min_DFCF/sz300705.csv
2023-11-24 sz300706 阿石创
./1min_DFCF/sz300706.csv
2023-11-24 sz300707 威唐工业
./1min_DFCF/sz300707.csv
2023-11-24 sz300708 聚灿光电
./1min_DFCF/sz300708.csv
2023-11-24 sz300709 精研科技
./1min_DFCF/sz300709.csv
2023-11-24 sz300710 万隆光电
./1min_DFCF/sz300710.csv
2023-11-24 sz300711 广哈通信
./1min_DFCF/sz300711.csv
2023-11-24 sz300712 永福股份
./1min_DFCF/sz300712.csv
2023-11-24 sz300713 英可瑞
./1min_DFCF/sz300713.csv
2023-11-24 sz300715 凯伦股份
./1min_DFCF/sz300715.csv
2023-11-24 sz300716 泉为科技
./1min_DFCF/sz300716.csv
2023-11-24 sz300717 华信新材
./1min_DFCF/sz300717.csv
2023-11-24 sz300718 长盛轴承
./1min_DFCF/sz300718.csv
2023-11-24 sz300719 安达维尔
./1min_DFCF/sz300719.csv
2023-11-24 sz300720 海川智能
./1min_DFCF/sz300720.csv
2023-11-24 sz300721 怡达股份
./1min_DFCF/sz300721.csv
2023-11-24 sz300722 新余国科
./1min_DFCF/sz300722.csv
2023-11-24 sz300723 一品红
./1min_DFCF/sz300723.csv
2023-11-24 sz300724 捷佳伟创
./1min_DFCF/sz300724.csv
2023-11-24 sz300725 药石科技
./1min_DFCF/sz300725.csv
2023-11-24 sz300726 宏达电子
./1min_DFCF/sz300726.csv
2023-11-24 sz300727 润禾材料
./1min_DFCF/sz300727.csv
2023-11-24 sz300729 乐歌股份
./1min_DFCF/sz300729.csv
2023-11-24 sz300730 科创信息
./1min_DFCF/sz300730.csv
2023-11-24 sz300731 科创新源
./1min_DFCF/sz300731.csv
2023-11-24 sz300732 设研院
./1min_DFCF/sz300732.csv
2023-11-24 sz300733 西菱动力
./1min_DFCF/sz300733.csv
2023-11-24 sz300735 光弘科技
./1min_DFCF/sz300735.csv
2023-11-24 sz300736 百邦科技
./1min_DFCF/sz300736.csv
2023-11-24 sz300737 科顺股份
./1min_DFCF/sz300737.csv
2023-11-24 sz300738 奥飞数据
./1min_DFCF/sz300738.csv
2023-11-24 sz300739 明阳电路
./1min_DFCF/sz300739.csv
2023-11-24 sz300740 水羊股份
./1min_DFCF/sz300740.csv
2023-11-24 sz300741 华宝股份
./1min_DFCF/sz300741.csv
2023-11-24 sz300742 *ST越博
./1min_DFCF/sz300742.csv
2023-11-24 sz300743 天地数码
./1min_DFCF/sz300743.csv
2023-11-24 sz300745 欣锐科技
./1min_DFCF/sz300745.csv
2023-11-24 sz300746 汉嘉设计
./1min_DFCF/sz300746.csv
2023-11-24 sz300747 锐科激光
./1min_DFCF/sz300747.csv
2023-11-24 sz300748 金力永磁
./1min_DFCF/sz300748.csv
2023-11-24 sz300749 顶固集创
./1min_DFCF/sz300749.csv
2023-11-24 sz300750 宁德时代
./1min_DFCF/sz300750.csv
2023-11-24 sz300751 迈为股份
./1min_DFCF/sz300751.csv
2023-11-24 sz300752 隆利科技
./1min_DFCF/sz300752.csv
2023-11-24 sz300753 爱朋医疗
./1min_DFCF/sz300753.csv
2023-11-24 sz300755 华致酒行
./1min_DFCF/sz300755.csv
2023-11-24 sz300756 金马游乐
./1min_DFCF/sz300756.csv
2023-11-24 sz300757 罗博特科
./1min_DFCF/sz300757.csv
2023-11-24 sz300758 七彩化学
./1min_DFCF/sz300758.csv
2023-11-24 sz300759 康龙化成
./1min_DFCF/sz300759.csv
2023-11-24 sz300760 迈瑞医疗
./1min_DFCF/sz300760.csv
2023-11-24 sz300761 立华股份
./1min_DFCF/sz300761.csv
2023-11-24 sz300762 上海瀚讯
./1min_DFCF/sz300762.csv
2023-11-24 sz300763 锦浪科技
./1min_DFCF/sz300763.csv
2023-11-24 sz300765 新诺威
./1min_DFCF/sz300765.csv
2023-11-24 sz300766 每日互动
./1min_DFCF/sz300766.csv
2023-11-24 sz300767 震安科技
./1min_DFCF/sz300767.csv
2023-11-24 sz300768 迪普科技
./1min_DFCF/sz300768.csv
2023-11-24 sz300769 德方纳米
./1min_DFCF/sz300769.csv
2023-11-24 sz300770 新媒股份
./1min_DFCF/sz300770.csv
2023-11-24 sz300771 智莱科技
./1min_DFCF/sz300771.csv
2023-11-24 sz300772 运达股份
./1min_DFCF/sz300772.csv
2023-11-24 sz300773 拉卡拉
./1min_DFCF/sz300773.csv
2023-11-24 sz300774 倍杰特
./1min_DFCF/sz300774.csv
2023-11-24 sz300775 三角防务
./1min_DFCF/sz300775.csv
2023-11-24 sz300776 帝尔激光
./1min_DFCF/sz300776.csv
2023-11-24 sz300777 中简科技
./1min_DFCF/sz300777.csv
2023-11-24 sz300778 新城市
./1min_DFCF/sz300778.csv
2023-11-24 sz300779 惠城环保
./1min_DFCF/sz300779.csv
2023-11-24 sz300780 德恩精工
./1min_DFCF/sz300780.csv
2023-11-24 sz300781 因赛集团
./1min_DFCF/sz300781.csv
2023-11-24 sz300782 卓胜微
./1min_DFCF/sz300782.csv
2023-11-24 sz300783 三只松鼠
./1min_DFCF/sz300783.csv
2023-11-24 sz300785 值得买
./1min_DFCF/sz300785.csv
2023-11-24 sz300786 国林科技
./1min_DFCF/sz300786.csv
2023-11-24 sz300787 海能实业
./1min_DFCF/sz300787.csv
2023-11-24 sz300788 中信出版
./1min_DFCF/sz300788.csv
2023-11-24 sz300789 唐源电气
./1min_DFCF/sz300789.csv
2023-11-24 sz300790 宇瞳光学
./1min_DFCF/sz300790.csv
2023-11-24 sz300791 仙乐健康
./1min_DFCF/sz300791.csv
2023-11-24 sz300792 壹网壹创
./1min_DFCF/sz300792.csv
2023-11-24 sz300793 佳禾智能
./1min_DFCF/sz300793.csv
2023-11-24 sz300795 米奥会展
./1min_DFCF/sz300795.csv
2023-11-24 sz300796 贝斯美
./1min_DFCF/sz300796.csv
2023-11-24 sz300797 钢研纳克
./1min_DFCF/sz300797.csv
2023-11-24 sz300798 锦鸡股份
./1min_DFCF/sz300798.csv
2023-11-24 sz300799 *ST左江
./1min_DFCF/sz300799.csv
2023-11-24 sz300800 力合科技
./1min_DFCF/sz300800.csv
2023-11-24 sz300801 泰和科技
./1min_DFCF/sz300801.csv
2023-11-24 sz300802 矩子科技
./1min_DFCF/sz300802.csv
2023-11-24 sz300803 指南针
./1min_DFCF/sz300803.csv
2023-11-24 sz300804 广康生化
./1min_DFCF/sz300804.csv
2023-11-24 sz300805 电声股份
./1min_DFCF/sz300805.csv
2023-11-24 sz300806 斯迪克
./1min_DFCF/sz300806.csv
2023-11-24 sz300807 天迈科技
./1min_DFCF/sz300807.csv
2023-11-24 sz300808 久量股份
./1min_DFCF/sz300808.csv
2023-11-24 sz300809 华辰装备
./1min_DFCF/sz300809.csv
2023-11-24 sz300810 中科海讯
./1min_DFCF/sz300810.csv
2023-11-24 sz300811 铂科新材
./1min_DFCF/sz300811.csv
2023-11-24 sz300812 易天股份
./1min_DFCF/sz300812.csv
2023-11-24 sz300813 泰林生物
./1min_DFCF/sz300813.csv
2023-11-24 sz300814 中富电路
./1min_DFCF/sz300814.csv
2023-11-24 sz300815 玉禾田
./1min_DFCF/sz300815.csv
2023-11-24 sz300816 艾可蓝
./1min_DFCF/sz300816.csv
2023-11-24 sz300817 双飞集团
./1min_DFCF/sz300817.csv
2023-11-24 sz300818 耐普矿机
./1min_DFCF/sz300818.csv
2023-11-24 sz300819 聚杰微纤
./1min_DFCF/sz300819.csv
2023-11-24 sz300820 英杰电气
./1min_DFCF/sz300820.csv
2023-11-24 sz300821 东岳硅材
./1min_DFCF/sz300821.csv
2023-11-24 sz300822 贝仕达克
./1min_DFCF/sz300822.csv
2023-11-24 sz300823 建科机械
./1min_DFCF/sz300823.csv
2023-11-24 sz300824 北鼎股份
./1min_DFCF/sz300824.csv
2023-11-24 sz300825 阿尔特
./1min_DFCF/sz300825.csv
2023-11-24 sz300826 测绘股份
./1min_DFCF/sz300826.csv
2023-11-24 sz300827 上能电气
./1min_DFCF/sz300827.csv
2023-11-24 sz300828 锐新科技
./1min_DFCF/sz300828.csv
2023-11-24 sz300829 金丹科技
./1min_DFCF/sz300829.csv
2023-11-24 sz300830 金现代
./1min_DFCF/sz300830.csv
2023-11-24 sz300831 派瑞股份
./1min_DFCF/sz300831.csv
2023-11-24 sz300832 新产业
./1min_DFCF/sz300832.csv
2023-11-24 sz300833 浩洋股份
./1min_DFCF/sz300833.csv
2023-11-24 sz300834 星辉环材
./1min_DFCF/sz300834.csv
2023-11-24 sz300835 龙磁科技
./1min_DFCF/sz300835.csv
2023-11-24 sz300836 佰奥智能
./1min_DFCF/sz300836.csv
2023-11-24 sz300837 浙矿股份
./1min_DFCF/sz300837.csv
2023-11-24 sz300838 浙江力诺
./1min_DFCF/sz300838.csv
2023-11-24 sz300839 博汇股份
./1min_DFCF/sz300839.csv
2023-11-24 sz300840 酷特智能
./1min_DFCF/sz300840.csv
2023-11-24 sz300841 康华生物
./1min_DFCF/sz300841.csv
2023-11-24 sz300842 帝科股份
./1min_DFCF/sz300842.csv
2023-11-24 sz300843 胜蓝股份
./1min_DFCF/sz300843.csv
2023-11-24 sz300844 山水比德

./1min_DFCF/sz300844.csv
2023-11-24 sz300845 捷安高科
./1min_DFCF/sz300845.csv
2023-11-24 sz300846 首都在线
./1min_DFCF/sz300846.csv
2023-11-24 sz300847 中船汉光
./1min_DFCF/sz300847.csv
2023-11-24 sz300848 美瑞新材
./1min_DFCF/sz300848.csv
2023-11-24 sz300849 锦盛新材
./1min_DFCF/sz300849.csv
2023-11-24 sz300850 新强联
./1min_DFCF/sz300850.csv
2023-11-24 sz300851 交大思诺
./1min_DFCF/sz300851.csv
2023-11-24 sz300852 四会富仕
./1min_DFCF/sz300852.csv
2023-11-24 sz300853 申昊科技
./1min_DFCF/sz300853.csv
2023-11-24 sz300854 中兰环保
./1min_DFCF/sz300854.csv
2023-11-24 sz300855 图南股份
./1min_DFCF/sz300855.csv
2023-11-24 sz300856 科思股份
./1min_DFCF/sz300856.csv
2023-11-24 sz300857 协创数据
./1min_DFCF/sz300857.csv
2023-11-24 sz300858 科拓生物
./1min_DFCF/sz300858.csv
2023-11-24 sz300859 *ST西域
./1min_DFCF/sz300859.csv
2023-11-24 sz300860 锋尚文化
./1min_DFCF/sz300860.csv
2023-11-24 sz300861 美畅股份
./1min_DFCF/sz300861.csv
2023-11-24 sz300862 蓝盾光电
./1min_DFCF/sz300862.csv
2023-11-24 sz300863 卡倍亿
./1min_DFCF/sz300863.csv
2023-11-24 sz300864 南大环境
./1min_DFCF/sz300864.csv
2023-11-24 sz300865 大宏立
./1min_DFCF/sz300865.csv
2023-11-24 sz300866 安克创新
./1min_DFCF/sz300866.csv
2023-11-24 sz300867 圣元环保
./1min_DFCF/sz300867.csv
2023-11-24 sz300868 杰美特
./1min_DFCF/sz300868.csv
2023-11-24 sz300869 康泰医学
./1min_DFCF/sz300869.csv
2023-11-24 sz300870 欧陆通
./1min_DFCF/sz300870.csv
2023-11-24 sz300871 回盛生物
./1min_DFCF/sz300871.csv
2023-11-24 sz300872 天阳科技
./1min_DFCF/sz300872.csv
2023-11-24 sz300873 海晨股份
./1min_DFCF/sz300873.csv
2023-11-24 sz300875 捷强装备
./1min_DFCF/sz300875.csv
2023-11-24 sz300876 蒙泰高新
./1min_DFCF/sz300876.csv
2023-11-24 sz300877 金春股份
./1min_DFCF/sz300877.csv
2023-11-24 sz300878 维康药业
./1min_DFCF/sz300878.csv
2023-11-24 sz300879 大叶股份
./1min_DFCF/sz300879.csv
2023-11-24 sz300880 迦南智能
./1min_DFCF/sz300880.csv
2023-11-24 sz300881 盛德鑫泰
./1min_DFCF/sz300881.csv
2023-11-24 sz300882 万胜智能
./1min_DFCF/sz300882.csv
2023-11-24 sz300883 龙利得
./1min_DFCF/sz300883.csv
2023-11-24 sz300884 狄耐克
./1min_DFCF/sz300884.csv
2023-11-24 sz300885 海昌新材
./1min_DFCF/sz300885.csv
2023-11-24 sz300886 华业香料
./1min_DFCF/sz300886.csv
2023-11-24 sz300887 谱尼测试
./1min_DFCF/sz300887.csv
2023-11-24 sz300888 稳健医疗
./1min_DFCF/sz300888.csv
2023-11-24 sz300889 爱克股份
./1min_DFCF/sz300889.csv
2023-11-24 sz300890 翔丰华
./1min_DFCF/sz300890.csv
2023-11-24 sz300891 惠云钛业
./1min_DFCF/sz300891.csv
2023-11-24 sz300892 品渥食品
./1min_DFCF/sz300892.csv
2023-11-24 sz300893 松原股份
./1min_DFCF/sz300893.csv
2023-11-24 sz300894 火星人
./1min_DFCF/sz300894.csv
2023-11-24 sz300895 铜牛信息
./1min_DFCF/sz300895.csv
2023-11-24 sz300896 爱美客
./1min_DFCF/sz300896.csv
2023-11-24 sz300897 山科智能
./1min_DFCF/sz300897.csv
2023-11-24 sz300898 熊猫乳品
./1min_DFCF/sz300898.csv
2023-11-24 sz300899 上海凯鑫
./1min_DFCF/sz300899.csv
2023-11-24 sz300900 广联航空
./1min_DFCF/sz300900.csv
2023-11-24 sz300901 中胤时尚
./1min_DFCF/sz300901.csv
2023-11-24 sz300902 国安达
./1min_DFCF/sz300902.csv
2023-11-24 sz300903 科翔股份
./1min_DFCF/sz300903.csv
2023-11-24 sz300904 威力传动
./1min_DFCF/sz300904.csv
2023-11-24 sz300905 宝丽迪
./1min_DFCF/sz300905.csv
2023-11-24 sz300906 日月明
./1min_DFCF/sz300906.csv
2023-11-24 sz300907 康平科技
./1min_DFCF/sz300907.csv
2023-11-24 sz300908 仲景食品
./1min_DFCF/sz300908.csv
2023-11-24 sz300909 汇创达
./1min_DFCF/sz300909.csv
2023-11-24 sz300910 瑞丰新材
./1min_DFCF/sz300910.csv
2023-11-24 sz300911 亿田智能
./1min_DFCF/sz300911.csv
2023-11-24 sz300912 凯龙高科
./1min_DFCF/sz300912.csv
2023-11-24 sz300913 兆龙互连
./1min_DFCF/sz300913.csv
2023-11-24 sz300915 海融科技
./1min_DFCF/sz300915.csv
2023-11-24 sz300916 朗特智能
./1min_DFCF/sz300916.csv
2023-11-24 sz300917 特发服务
./1min_DFCF/sz300917.csv
2023-11-24 sz300918 南山智尚
./1min_DFCF/sz300918.csv
2023-11-24 sz300919 中伟股份
./1min_DFCF/sz300919.csv
2023-11-24 sz300920 润阳科技
./1min_DFCF/sz300920.csv
2023-11-24 sz300921 南凌科技
./1min_DFCF/sz300921.csv
2023-11-24 sz300922 天秦装备
./1min_DFCF/sz300922.csv
2023-11-24 sz300923 研奥股份
./1min_DFCF/sz300923.csv
2023-11-24 sz300925 法本信息
./1min_DFCF/sz300925.csv
2023-11-24 sz300926 博俊科技
./1min_DFCF/sz300926.csv
2023-11-24 sz300927 江天化学
./1min_DFCF/sz300927.csv
2023-11-24 sz300928 华安鑫创
./1min_DFCF/sz300928.csv
2023-11-24 sz300929 华骐环保
./1min_DFCF/sz300929.csv
2023-11-24 sz300930 屹通新材
./1min_DFCF/sz300930.csv
2023-11-24 sz300931 通用电梯
./1min_DFCF/sz300931.csv
2023-11-24 sz300932 三友联众
./1min_DFCF/sz300932.csv
2023-11-24 sz300933 中辰股份
./1min_DFCF/sz300933.csv
2023-11-24 sz300935 盈建科
./1min_DFCF/sz300935.csv
2023-11-24 sz300936 中英科技
./1min_DFCF/sz300936.csv
2023-11-24 sz300937 药易购
./1min_DFCF/sz300937.csv
2023-11-24 sz300938 信测标准
./1min_DFCF/sz300938.csv
2023-11-24 sz300939 秋田微
./1min_DFCF/sz300939.csv
2023-11-24 sz300940 南极光
./1min_DFCF/sz300940.csv
2023-11-24 sz300941 创识科技
./1min_DFCF/sz300941.csv
2023-11-24 sz300942 易瑞生物
./1min_DFCF/sz300942.csv
2023-11-24 sz300943 春晖智控
./1min_DFCF/sz300943.csv
2023-11-24 sz300945 曼卡龙
./1min_DFCF/sz300945.csv
2023-11-24 sz300946 恒而达
./1min_DFCF/sz300946.csv
2023-11-24 sz300947 德必集团
./1min_DFCF/sz300947.csv
2023-11-24 sz300948 冠中生态
./1min_DFCF/sz300948.csv
2023-11-24 sz300949 奥雅股份
./1min_DFCF/sz300949.csv
2023-11-24 sz300950 德固特
./1min_DFCF/sz300950.csv
2023-11-24 sz300951 博硕科技
./1min_DFCF/sz300951.csv
2023-11-24 sz300952 恒辉安防
./1min_DFCF/sz300952.csv
2023-11-24 sz300953 震裕科技
./1min_DFCF/sz300953.csv
2023-11-24 sz300955 嘉亨家化
./1min_DFCF/sz300955.csv
2023-11-24 sz300956 英力股份
./1min_DFCF/sz300956.csv
2023-11-24 sz300957 贝泰妮
./1min_DFCF/sz300957.csv
2023-11-24 sz300958 建工修复
./1min_DFCF/sz300958.csv
2023-11-24 sz300959 线上线下
./1min_DFCF/sz300959.csv
2023-11-24 sz300960 通业科技
./1min_DFCF/sz300960.csv
2023-11-24 sz300961 深水海纳
./1min_DFCF/sz300961.csv
2023-11-24 sz300962 中金辐照
./1min_DFCF/sz300962.csv
2023-11-24 sz300963 中洲特材
./1min_DFCF/sz300963.csv
2023-11-24 sz300964 本川智能
./1min_DFCF/sz300964.csv
2023-11-24 sz300965 恒宇信通
./1min_DFCF/sz300965.csv
2023-11-24 sz300966 共同药业
./1min_DFCF/sz300966.csv
2023-11-24 sz300967 晓鸣股份
./1min_DFCF/sz300967.csv
2023-11-24 sz300968 格林精密
./1min_DFCF/sz300968.csv
2023-11-24 sz300969 恒帅股份
./1min_DFCF/sz300969.csv
2023-11-24 sz300970 华绿生物
./1min_DFCF/sz300970.csv
2023-11-24 sz300971 博亚精工
./1min_DFCF/sz300971.csv
2023-11-24 sz300972 万辰集团
./1min_DFCF/sz300972.csv
2023-11-24 sz300973 立高食品
./1min_DFCF/sz300973.csv
2023-11-24 sz300975 商络电子
./1min_DFCF/sz300975.csv
2023-11-24 sz300976 达瑞电子
./1min_DFCF/sz300976.csv
2023-11-24 sz300977 深圳瑞捷
./1min_DFCF/sz300977.csv
2023-11-24 sz300978 东箭科技
./1min_DFCF/sz300978.csv
2023-11-24 sz300979 华利集团
./1min_DFCF/sz300979.csv
2023-11-24 sz300980 祥源新材
./1min_DFCF/sz300980.csv
2023-11-24 sz300981 中红医疗
./1min_DFCF/sz300981.csv
2023-11-24 sz300982 苏文电能
./1min_DFCF/sz300982.csv
2023-11-24 sz300983 尤安设计
./1min_DFCF/sz300983.csv
2023-11-24 sz300984 金沃股份
./1min_DFCF/sz300984.csv
2023-11-24 sz300985 致远新能
./1min_DFCF/sz300985.csv
2023-11-24 sz300986 志特新材
./1min_DFCF/sz300986.csv
2023-11-24 sz300987 川网传媒
./1min_DFCF/sz300987.csv
2023-11-24 sz300988 津荣天宇
./1min_DFCF/sz300988.csv
2023-11-24 sz300989 蕾奥规划
./1min_DFCF/sz300989.csv
2023-11-24 sz300990 同飞股份
./1min_DFCF/sz300990.csv
2023-11-24 sz300991 创益通
./1min_DFCF/sz300991.csv
2023-11-24 sz300992 泰福泵业
./1min_DFCF/sz300992.csv
2023-11-24 sz300993 玉马遮阳
./1min_DFCF/sz300993.csv
2023-11-24 sz300994 久祺股份
./1min_DFCF/sz300994.csv
2023-11-24 sz300995 奇德新材
./1min_DFCF/sz300995.csv
2023-11-24 sz300996 普联软件
./1min_DFCF/sz300996.csv
2023-11-24 sz300997 欢乐家
./1min_DFCF/sz300997.csv
2023-11-24 sz300998 宁波方正
./1min_DFCF/sz300998.csv
2023-11-24 sz300999 金龙鱼
./1min_DFCF/sz300999.csv
2023-11-24 sz301000 肇民科技
./1min_DFCF/sz301000.csv
2023-11-24 sz301001 凯淳股份
./1min_DFCF/sz301001.csv
2023-11-24 sz301002 崧盛股份
./1min_DFCF/sz301002.csv
2023-11-24 sz301003 江苏博云
./1min_DFCF/sz301003.csv
2023-11-24 sz301004 嘉益股份
./1min_DFCF/sz301004.csv
2023-11-24 sz301005 超捷股份
./1min_DFCF/sz301005.csv
2023-11-24 sz301006 迈拓股份
./1min_DFCF/sz301006.csv
2023-11-24 sz301007 德迈仕
./1min_DFCF/sz301007.csv
2023-11-24 sz301008 宏昌科技
./1min_DFCF/sz301008.csv
2023-11-24 sz301009 可靠股份
./1min_DFCF/sz301009.csv
2023-11-24 sz301010 晶雪节能
./1min_DFCF/sz301010.csv
2023-11-24 sz301011 华立科技
./1min_DFCF/sz301011.csv
2023-11-24 sz301012 扬电科技
./1min_DFCF/sz301012.csv
2023-11-24 sz301013 利和兴
./1min_DFCF/sz301013.csv
2023-11-24 sz301015 百洋医药
./1min_DFCF/sz301015.csv
2023-11-24 sz301016 雷尔伟
./1min_DFCF/sz301016.csv
2023-11-24 sz301017 漱玉平民

./1min_DFCF/sz301017.csv
2023-11-24 sz301018 申菱环境
./1min_DFCF/sz301018.csv
2023-11-24 sz301019 宁波色母
./1min_DFCF/sz301019.csv
2023-11-24 sz301020 密封科技
./1min_DFCF/sz301020.csv
2023-11-24 sz301021 英诺激光
./1min_DFCF/sz301021.csv
2023-11-24 sz301022 海泰科
./1min_DFCF/sz301022.csv
2023-11-24 sz301023 江南奕帆
./1min_DFCF/sz301023.csv
2023-11-24 sz301024 霍普股份
./1min_DFCF/sz301024.csv
2023-11-24 sz301025 读客文化
./1min_DFCF/sz301025.csv
2023-11-24 sz301026 浩通科技
./1min_DFCF/sz301026.csv
2023-11-24 sz301027 华蓝集团
./1min_DFCF/sz301027.csv
2023-11-24 sz301028 东亚机械
./1min_DFCF/sz301028.csv
2023-11-24 sz301029 怡合达
./1min_DFCF/sz301029.csv
2023-11-24 sz301030 仕净科技
./1min_DFCF/sz301030.csv
2023-11-24 sz301031 中熔电气
./1min_DFCF/sz301031.csv
2023-11-24 sz301032 新柴股份
./1min_DFCF/sz301032.csv
2023-11-24 sz301033 迈普医学
./1min_DFCF/sz301033.csv
2023-11-24 sz301035 润丰股份
./1min_DFCF/sz301035.csv
2023-11-24 sz301036 双乐股份
./1min_DFCF/sz301036.csv
2023-11-24 sz301037 保立佳
./1min_DFCF/sz301037.csv
2023-11-24 sz301038 深水规院
./1min_DFCF/sz301038.csv
2023-11-24 sz301039 中集车辆
./1min_DFCF/sz301039.csv
2023-11-24 sz301040 中环海陆
./1min_DFCF/sz301040.csv
2023-11-24 sz301041 金百泽
./1min_DFCF/sz301041.csv
2023-11-24 sz301042 安联锐视
./1min_DFCF/sz301042.csv
2023-11-24 sz301043 绿岛风
./1min_DFCF/sz301043.csv
2023-11-24 sz301045 天禄科技
./1min_DFCF/sz301045.csv
2023-11-24 sz301046 能辉科技
./1min_DFCF/sz301046.csv
2023-11-24 sz301047 义翘神州
./1min_DFCF/sz301047.csv
2023-11-24 sz301048 金鹰重工
./1min_DFCF/sz301048.csv
2023-11-24 sz301049 超越科技
./1min_DFCF/sz301049.csv
2023-11-24 sz301050 雷电微力
./1min_DFCF/sz301050.csv
2023-11-24 sz301051 信濠光电
./1min_DFCF/sz301051.csv
2023-11-24 sz301052 果麦文化
./1min_DFCF/sz301052.csv
2023-11-24 sz301053 远信工业
./1min_DFCF/sz301053.csv
2023-11-24 sz301055 张小泉
./1min_DFCF/sz301055.csv
2023-11-24 sz301056 森赫股份
./1min_DFCF/sz301056.csv
2023-11-24 sz301057 汇隆新材
./1min_DFCF/sz301057.csv
2023-11-24 sz301058 中粮科工
./1min_DFCF/sz301058.csv
2023-11-24 sz301059 金三江
./1min_DFCF/sz301059.csv
2023-11-24 sz301060 兰卫医学
./1min_DFCF/sz301060.csv
2023-11-24 sz301061 匠心家居
./1min_DFCF/sz301061.csv
2023-11-24 sz301062 上海艾录
./1min_DFCF/sz301062.csv
2023-11-24 sz301063 海锅股份
./1min_DFCF/sz301063.csv
2023-11-24 sz301065 本立科技
./1min_DFCF/sz301065.csv
2023-11-24 sz301066 万事利
./1min_DFCF/sz301066.csv
2023-11-24 sz301067 显盈科技
./1min_DFCF/sz301067.csv
2023-11-24 sz301068 大地海洋
./1min_DFCF/sz301068.csv
2023-11-24 sz301069 凯盛新材
./1min_DFCF/sz301069.csv
2023-11-24 sz301070 开勒股份
./1min_DFCF/sz301070.csv
2023-11-24 sz301071 力量钻石
./1min_DFCF/sz301071.csv
2023-11-24 sz301072 中捷精工
./1min_DFCF/sz301072.csv
2023-11-24 sz301073 君亭酒店
./1min_DFCF/sz301073.csv
2023-11-24 sz301075 多瑞医药
./1min_DFCF/sz301075.csv
2023-11-24 sz301076 新瀚新材
./1min_DFCF/sz301076.csv
2023-11-24 sz301077 星华新材
./1min_DFCF/sz301077.csv
2023-11-24 sz301078 孩子王
./1min_DFCF/sz301078.csv
2023-11-24 sz301079 邵阳液压
./1min_DFCF/sz301079.csv
2023-11-24 sz301080 百普赛斯
./1min_DFCF/sz301080.csv
2023-11-24 sz301081 严牌股份
./1min_DFCF/sz301081.csv
2023-11-24 sz301082 久盛电气
./1min_DFCF/sz301082.csv
2023-11-24 sz301083 百胜智能
./1min_DFCF/sz301083.csv
2023-11-24 sz301085 亚康股份
./1min_DFCF/sz301085.csv
2023-11-24 sz301086 鸿富瀚
./1min_DFCF/sz301086.csv
2023-11-24 sz301087 可孚医疗
./1min_DFCF/sz301087.csv
2023-11-24 sz301088 戎美股份
./1min_DFCF/sz301088.csv
2023-11-24 sz301089 拓新药业
./1min_DFCF/sz301089.csv
2023-11-24 sz301090 华润材料
./1min_DFCF/sz301090.csv
2023-11-24 sz301091 深城交
./1min_DFCF/sz301091.csv
2023-11-24 sz301092 争光股份
./1min_DFCF/sz301092.csv
2023-11-24 sz301093 华兰股份
./1min_DFCF/sz301093.csv
2023-11-24 sz301095 广立微
./1min_DFCF/sz301095.csv
2023-11-24 sz301096 百诚医药
./1min_DFCF/sz301096.csv
2023-11-24 sz301097 天益医疗
./1min_DFCF/sz301097.csv
2023-11-24 sz301098 金埔园林
./1min_DFCF/sz301098.csv
2023-11-24 sz301099 雅创电子
./1min_DFCF/sz301099.csv
2023-11-24 sz301100 风光股份
./1min_DFCF/sz301100.csv
2023-11-24 sz301101 明月镜片
./1min_DFCF/sz301101.csv
2023-11-24 sz301102 兆讯传媒
./1min_DFCF/sz301102.csv
2023-11-24 sz301103 何氏眼科
./1min_DFCF/sz301103.csv
2023-11-24 sz301105 鸿铭股份
./1min_DFCF/sz301105.csv
2023-11-24 sz301106 骏成科技
./1min_DFCF/sz301106.csv
2023-11-24 sz301107 瑜欣电子
./1min_DFCF/sz301107.csv
2023-11-24 sz301108 洁雅股份
./1min_DFCF/sz301108.csv
2023-11-24 sz301109 军信股份
./1min_DFCF/sz301109.csv
2023-11-24 sz301110 青木股份
./1min_DFCF/sz301110.csv
2023-11-24 sz301111 粤万年青
./1min_DFCF/sz301111.csv
2023-11-24 sz301112 信邦智能
./1min_DFCF/sz301112.csv
2023-11-24 sz301113 雅艺科技
./1min_DFCF/sz301113.csv
2023-11-24 sz301115 建科股份
./1min_DFCF/sz301115.csv
2023-11-24 sz301116 益客食品
./1min_DFCF/sz301116.csv
2023-11-24 sz301117 佳缘科技
./1min_DFCF/sz301117.csv
2023-11-24 sz301118 恒光股份
./1min_DFCF/sz301118.csv
2023-11-24 sz301119 正强股份
./1min_DFCF/sz301119.csv
2023-11-24 sz301120 新特电气
./1min_DFCF/sz301120.csv
2023-11-24 sz301121 紫建电子
./1min_DFCF/sz301121.csv
2023-11-24 sz301122 采纳股份
./1min_DFCF/sz301122.csv
2023-11-24 sz301123 奕东电子
./1min_DFCF/sz301123.csv
2023-11-24 sz301125 腾亚精工
./1min_DFCF/sz301125.csv
2023-11-24 sz301126 达嘉维康
./1min_DFCF/sz301126.csv
2023-11-24 sz301127 天源环保
./1min_DFCF/sz301127.csv
2023-11-24 sz301128 强瑞技术
./1min_DFCF/sz301128.csv
2023-11-24 sz301129 瑞纳智能
./1min_DFCF/sz301129.csv
2023-11-24 sz301130 西点药业
./1min_DFCF/sz301130.csv
2023-11-24 sz301131 聚赛龙
./1min_DFCF/sz301131.csv
2023-11-24 sz301132 满坤科技
./1min_DFCF/sz301132.csv
2023-11-24 sz301133 金钟股份
./1min_DFCF/sz301133.csv
2023-11-24 sz301135 瑞德智能
./1min_DFCF/sz301135.csv
2023-11-24 sz301136 招标股份
./1min_DFCF/sz301136.csv
2023-11-24 sz301137 哈焊华通
./1min_DFCF/sz301137.csv
2023-11-24 sz301138 华研精机
./1min_DFCF/sz301138.csv
2023-11-24 sz301139 元道通信
./1min_DFCF/sz301139.csv
2023-11-24 sz301141 中科磁业
./1min_DFCF/sz301141.csv
2023-11-24 sz301148 嘉戎技术
./1min_DFCF/sz301148.csv
2023-11-24 sz301149 隆华新材
./1min_DFCF/sz301149.csv
2023-11-24 sz301150 中一科技
./1min_DFCF/sz301150.csv
2023-11-24 sz301151 冠龙节能
./1min_DFCF/sz301151.csv
2023-11-24 sz301152 天力锂能
./1min_DFCF/sz301152.csv
2023-11-24 sz301153 中科江南
./1min_DFCF/sz301153.csv
2023-11-24 sz301155 海力风电
./1min_DFCF/sz301155.csv
2023-11-24 sz301156 美农生物
./1min_DFCF/sz301156.csv
2023-11-24 sz301157 华塑科技
./1min_DFCF/sz301157.csv
2023-11-24 sz301158 德石股份
./1min_DFCF/sz301158.csv
2023-11-24 sz301159 三维天地
./1min_DFCF/sz301159.csv
2023-11-24 sz301160 翔楼新材
./1min_DFCF/sz301160.csv
2023-11-24 sz301161 唯万密封
./1min_DFCF/sz301161.csv
2023-11-24 sz301162 国能日新
./1min_DFCF/sz301162.csv
2023-11-24 sz301163 宏德股份
./1min_DFCF/sz301163.csv
2023-11-24 sz301165 锐捷网络
./1min_DFCF/sz301165.csv
2023-11-24 sz301166 优宁维
./1min_DFCF/sz301166.csv
2023-11-24 sz301167 建研设计
./1min_DFCF/sz301167.csv
2023-11-24 sz301168 通灵股份
./1min_DFCF/sz301168.csv
2023-11-24 sz301169 零点有数
./1min_DFCF/sz301169.csv
2023-11-24 sz301170 锡南科技
./1min_DFCF/sz301170.csv
2023-11-24 sz301171 易点天下
./1min_DFCF/sz301171.csv
2023-11-24 sz301172 君逸数码
./1min_DFCF/sz301172.csv
2023-11-24 sz301175 中科环保
./1min_DFCF/sz301175.csv
2023-11-24 sz301176 逸豪新材
./1min_DFCF/sz301176.csv
2023-11-24 sz301177 迪阿股份
./1min_DFCF/sz301177.csv
2023-11-24 sz301178 天亿马
./1min_DFCF/sz301178.csv
2023-11-24 sz301179 泽宇智能
./1min_DFCF/sz301179.csv
2023-11-24 sz301180 万祥科技
./1min_DFCF/sz301180.csv
2023-11-24 sz301181 标榜股份
./1min_DFCF/sz301181.csv
2023-11-24 sz301182 凯旺科技
./1min_DFCF/sz301182.csv
2023-11-24 sz301183 东田微
./1min_DFCF/sz301183.csv
2023-11-24 sz301185 鸥玛软件
./1min_DFCF/sz301185.csv
2023-11-24 sz301186 超达装备
./1min_DFCF/sz301186.csv
2023-11-24 sz301187 欧圣电气
./1min_DFCF/sz301187.csv
2023-11-24 sz301188 力诺特玻
./1min_DFCF/sz301188.csv
2023-11-24 sz301189 奥尼电子
./1min_DFCF/sz301189.csv
2023-11-24 sz301190 善水科技
./1min_DFCF/sz301190.csv
2023-11-24 sz301191 菲菱科思
./1min_DFCF/sz301191.csv
2023-11-24 sz301192 泰祥股份
./1min_DFCF/sz301192.csv
2023-11-24 sz301193 家联科技
./1min_DFCF/sz301193.csv
2023-11-24 sz301195 北路智控
./1min_DFCF/sz301195.csv
2023-11-24 sz301196 唯科科技
./1min_DFCF/sz301196.csv
2023-11-24 sz301197 工大科雅
./1min_DFCF/sz301197.csv
2023-11-24 sz301198 喜悦智行
./1min_DFCF/sz301198.csv
2023-11-24 sz301199 迈赫股份
./1min_DFCF/sz301199.csv
2023-11-24 sz301200 大族数控
./1min_DFCF/sz301200.csv
2023-11-24 sz301201 诚达药业
./1min_DFCF/sz301201.csv
2023-11-24 sz301202 朗威股份
./1min_DFCF/sz301202.csv
2023-11-24 sz301203 国泰环保
./1min_DFCF/sz301203.csv
2023-11-24 sz301205 联特科技
./1min_DFCF/sz301205.csv
2023-11-24 sz301206 三元生物
./1min_DFCF/sz301206.csv
2023-11-24 sz301207 华兰疫苗

./1min_DFCF/sz301207.csv
2023-11-24 sz301208 中亦科技
./1min_DFCF/sz301208.csv
2023-11-24 sz301209 联合化学
./1min_DFCF/sz301209.csv
2023-11-24 sz301210 金杨股份
./1min_DFCF/sz301210.csv
2023-11-24 sz301211 亨迪药业
./1min_DFCF/sz301211.csv
2023-11-24 sz301212 联盛化学
./1min_DFCF/sz301212.csv
2023-11-24 sz301213 观想科技
./1min_DFCF/sz301213.csv
2023-11-24 sz301215 中汽股份
./1min_DFCF/sz301215.csv
2023-11-24 sz301216 万凯新材
./1min_DFCF/sz301216.csv
2023-11-24 sz301217 铜冠铜箔
./1min_DFCF/sz301217.csv
2023-11-24 sz301218 华是科技
./1min_DFCF/sz301218.csv
2023-11-24 sz301219 腾远钴业
./1min_DFCF/sz301219.csv
2023-11-24 sz301220 亚香股份
./1min_DFCF/sz301220.csv
2023-11-24 sz301221 光庭信息
./1min_DFCF/sz301221.csv
2023-11-24 sz301222 浙江恒威
./1min_DFCF/sz301222.csv
2023-11-24 sz301223 中荣股份
./1min_DFCF/sz301223.csv
2023-11-24 sz301225 恒勃股份
./1min_DFCF/sz301225.csv
2023-11-24 sz301226 祥明智能
./1min_DFCF/sz301226.csv
2023-11-24 sz301227 森鹰窗业
./1min_DFCF/sz301227.csv
2023-11-24 sz301228 实朴检测
./1min_DFCF/sz301228.csv
2023-11-24 sz301229 纽泰格
./1min_DFCF/sz301229.csv
2023-11-24 sz301230 泓博医药
./1min_DFCF/sz301230.csv
2023-11-24 sz301231 荣信文化
./1min_DFCF/sz301231.csv
2023-11-24 sz301232 飞沃科技
./1min_DFCF/sz301232.csv
2023-11-24 sz301233 盛帮股份
./1min_DFCF/sz301233.csv
2023-11-24 sz301234 五洲医疗
./1min_DFCF/sz301234.csv
2023-11-24 sz301235 华康医疗
./1min_DFCF/sz301235.csv
2023-11-24 sz301236 软通动力
./1min_DFCF/sz301236.csv
2023-11-24 sz301237 和顺科技
./1min_DFCF/sz301237.csv
2023-11-24 sz301238 瑞泰新材
./1min_DFCF/sz301238.csv
2023-11-24 sz301239 普瑞眼科
./1min_DFCF/sz301239.csv
2023-11-24 sz301246 宏源药业
./1min_DFCF/sz301246.csv
2023-11-24 sz301248 杰创智能
./1min_DFCF/sz301248.csv
2023-11-24 sz301251 威尔高
./1min_DFCF/sz301251.csv
2023-11-24 sz301252 同星科技
./1min_DFCF/sz301252.csv
2023-11-24 sz301255 通力科技
./1min_DFCF/sz301255.csv
2023-11-24 sz301256 华融化学
./1min_DFCF/sz301256.csv
2023-11-24 sz301257 普蕊斯
./1min_DFCF/sz301257.csv
2023-11-24 sz301258 富士莱
./1min_DFCF/sz301258.csv
2023-11-24 sz301259 艾布鲁
./1min_DFCF/sz301259.csv
2023-11-24 sz301260 格力博
./1min_DFCF/sz301260.csv
2023-11-24 sz301261 恒工精密
./1min_DFCF/sz301261.csv
2023-11-24 sz301262 海看股份
./1min_DFCF/sz301262.csv
2023-11-24 sz301263 泰恩康
./1min_DFCF/sz301263.csv
2023-11-24 sz301265 华新环保
./1min_DFCF/sz301265.csv
2023-11-24 sz301266 宇邦新材
./1min_DFCF/sz301266.csv
2023-11-24 sz301267 华厦眼科
./1min_DFCF/sz301267.csv
2023-11-24 sz301268 铭利达
./1min_DFCF/sz301268.csv
2023-11-24 sz301269 华大九天
./1min_DFCF/sz301269.csv
2023-11-24 sz301270 汉仪股份
./1min_DFCF/sz301270.csv
2023-11-24 sz301272 英华特
./1min_DFCF/sz301272.csv
2023-11-24 sz301273 瑞晨环保
./1min_DFCF/sz301273.csv
2023-11-24 sz301276 嘉曼服饰
./1min_DFCF/sz301276.csv
2023-11-24 sz301277 新天地
./1min_DFCF/sz301277.csv
2023-11-24 sz301278 快可电子
./1min_DFCF/sz301278.csv
2023-11-24 sz301279 金道科技
./1min_DFCF/sz301279.csv
2023-11-24 sz301280 珠城科技
./1min_DFCF/sz301280.csv
2023-11-24 sz301281 科源制药
./1min_DFCF/sz301281.csv
2023-11-24 sz301282 金禄电子
./1min_DFCF/sz301282.csv
2023-11-24 sz301283 聚胶股份
./1min_DFCF/sz301283.csv
2023-11-24 sz301285 鸿日达
./1min_DFCF/sz301285.csv
2023-11-24 sz301286 侨源股份
./1min_DFCF/sz301286.csv
2023-11-24 sz301287 康力源
./1min_DFCF/sz301287.csv
2023-11-24 sz301288 清研环境
./1min_DFCF/sz301288.csv
2023-11-24 sz301289 国缆检测
./1min_DFCF/sz301289.csv
2023-11-24 sz301290 东星医疗
./1min_DFCF/sz301290.csv
2023-11-24 sz301291 明阳电气
./1min_DFCF/sz301291.csv
2023-11-24 sz301292 海科新源
./1min_DFCF/sz301292.csv
2023-11-24 sz301293 三博脑科
./1min_DFCF/sz301293.csv
2023-11-24 sz301295 美硕科技
./1min_DFCF/sz301295.csv
2023-11-24 sz301296 新巨丰
./1min_DFCF/sz301296.csv
2023-11-24 sz301297 富乐德
./1min_DFCF/sz301297.csv
2023-11-24 sz301298 东利机械
./1min_DFCF/sz301298.csv
2023-11-24 sz301299 卓创资讯
./1min_DFCF/sz301299.csv
2023-11-24 sz301300 远翔新材
./1min_DFCF/sz301300.csv
2023-11-24 sz301301 川宁生物
./1min_DFCF/sz301301.csv
2023-11-24 sz301302 华如科技
./1min_DFCF/sz301302.csv
2023-11-24 sz301303 真兰仪表
./1min_DFCF/sz301303.csv
2023-11-24 sz301305 朗坤环境
./1min_DFCF/sz301305.csv
2023-11-24 sz301306 西测测试
./1min_DFCF/sz301306.csv
2023-11-24 sz301307 美利信
./1min_DFCF/sz301307.csv
2023-11-24 sz301308 江波龙
./1min_DFCF/sz301308.csv
2023-11-24 sz301309 万得凯
./1min_DFCF/sz301309.csv
2023-11-24 sz301310 鑫宏业
./1min_DFCF/sz301310.csv
2023-11-24 sz301311 昆船智能
./1min_DFCF/sz301311.csv
2023-11-24 sz301312 智立方
./1min_DFCF/sz301312.csv
2023-11-24 sz301313 凡拓数创
./1min_DFCF/sz301313.csv
2023-11-24 sz301314 科瑞思
./1min_DFCF/sz301314.csv
2023-11-24 sz301315 威士顿
./1min_DFCF/sz301315.csv
2023-11-24 sz301316 慧博云通
./1min_DFCF/sz301316.csv
2023-11-24 sz301317 鑫磊股份
./1min_DFCF/sz301317.csv
2023-11-24 sz301318 维海德
./1min_DFCF/sz301318.csv
2023-11-24 sz301319 唯特偶
./1min_DFCF/sz301319.csv
2023-11-24 sz301320 豪江智能
./1min_DFCF/sz301320.csv
2023-11-24 sz301321 翰博高新
./1min_DFCF/sz301321.csv
2023-11-24 sz301322 绿通科技
./1min_DFCF/sz301322.csv
2023-11-24 sz301323 新莱福
./1min_DFCF/sz301323.csv
2023-11-24 sz301325 曼恩斯特
./1min_DFCF/sz301325.csv
2023-11-24 sz301326 捷邦科技
./1min_DFCF/sz301326.csv
2023-11-24 sz301327 华宝新能
./1min_DFCF/sz301327.csv
2023-11-24 sz301328 维峰电子
./1min_DFCF/sz301328.csv
2023-11-24 sz301329 信音电子
./1min_DFCF/sz301329.csv
2023-11-24 sz301330 熵基科技
./1min_DFCF/sz301330.csv
2023-11-24 sz301331 恩威医药
./1min_DFCF/sz301331.csv
2023-11-24 sz301332 德尔玛
./1min_DFCF/sz301332.csv
2023-11-24 sz301333 诺思格
./1min_DFCF/sz301333.csv
2023-11-24 sz301335 天元宠物
./1min_DFCF/sz301335.csv
2023-11-24 sz301336 趣睡科技
./1min_DFCF/sz301336.csv
2023-11-24 sz301337 亚华电子
./1min_DFCF/sz301337.csv
2023-11-24 sz301338 凯格精机
./1min_DFCF/sz301338.csv
2023-11-24 sz301339 通行宝
./1min_DFCF/sz301339.csv
2023-11-24 sz301345 涛涛车业
./1min_DFCF/sz301345.csv
2023-11-24 sz301348 蓝箭电子
./1min_DFCF/sz301348.csv
2023-11-24 sz301349 信德新材
./1min_DFCF/sz301349.csv
2023-11-24 sz301353 普莱得
./1min_DFCF/sz301353.csv
2023-11-24 sz301355 南王科技
./1min_DFCF/sz301355.csv
2023-11-24 sz301356 天振股份
./1min_DFCF/sz301356.csv
2023-11-24 sz301357 北方长龙
./1min_DFCF/sz301357.csv
2023-11-24 sz301358 湖南裕能
./1min_DFCF/sz301358.csv
2023-11-24 sz301359 东南电子
./1min_DFCF/sz301359.csv
2023-11-24 sz301360 荣旗科技
./1min_DFCF/sz301360.csv
2023-11-24 sz301361 众智科技
./1min_DFCF/sz301361.csv
2023-11-24 sz301362 民爆光电
./1min_DFCF/sz301362.csv
2023-11-24 sz301363 美好医疗
./1min_DFCF/sz301363.csv
2023-11-24 sz301365 矩阵股份
./1min_DFCF/sz301365.csv
2023-11-24 sz301366 一博科技
./1min_DFCF/sz301366.csv
2023-11-24 sz301367 怡和嘉业
./1min_DFCF/sz301367.csv
2023-11-24 sz301368 丰立智能
./1min_DFCF/sz301368.csv
2023-11-24 sz301369 联动科技
./1min_DFCF/sz301369.csv
2023-11-24 sz301370 国科恒泰
./1min_DFCF/sz301370.csv
2023-11-24 sz301371 敷尔佳
./1min_DFCF/sz301371.csv
2023-11-24 sz301372 科净源
./1min_DFCF/sz301372.csv
2023-11-24 sz301373 凌玮科技
./1min_DFCF/sz301373.csv
2023-11-24 sz301376 致欧科技
./1min_DFCF/sz301376.csv
2023-11-24 sz301377 鼎泰高科
./1min_DFCF/sz301377.csv
2023-11-24 sz301378 通达海
./1min_DFCF/sz301378.csv
2023-11-24 sz301379 天山电子
./1min_DFCF/sz301379.csv
2023-11-24 sz301380 挖金客
./1min_DFCF/sz301380.csv
2023-11-24 sz301381 赛维时代
./1min_DFCF/sz301381.csv
2023-11-24 sz301382 蜂助手
./1min_DFCF/sz301382.csv
2023-11-24 sz301383 天键股份
./1min_DFCF/sz301383.csv
2023-11-24 sz301386 未来电器
./1min_DFCF/sz301386.csv
2023-11-24 sz301387 光大同创
./1min_DFCF/sz301387.csv
2023-11-24 sz301388 欣灵电气
./1min_DFCF/sz301388.csv
2023-11-24 sz301389 隆扬电子
./1min_DFCF/sz301389.csv
2023-11-24 sz301390 经纬股份
./1min_DFCF/sz301390.csv
2023-11-24 sz301391 卡莱特
./1min_DFCF/sz301391.csv
2023-11-24 sz301393 昊帆生物
./1min_DFCF/sz301393.csv
2023-11-24 sz301395 仁信新材
./1min_DFCF/sz301395.csv
2023-11-24 sz301396 宏景科技
./1min_DFCF/sz301396.csv
2023-11-24 sz301397 溯联股份
./1min_DFCF/sz301397.csv
2023-11-24 sz301398 星源卓镁
./1min_DFCF/sz301398.csv
2023-11-24 sz301399 英特科技
./1min_DFCF/sz301399.csv
2023-11-24 sz301408 华人健康
./1min_DFCF/sz301408.csv
2023-11-24 sz301418 协昌科技
./1min_DFCF/sz301418.csv
2023-11-24 sz301419 阿莱德
./1min_DFCF/sz301419.csv
2023-11-24 sz301421 波长光电
./1min_DFCF/sz301421.csv
2023-11-24 sz301428 世纪恒通
./1min_DFCF/sz301428.csv
2023-11-24 sz301429 森泰股份
./1min_DFCF/sz301429.csv
2023-11-24 sz301439 泓淋电力
./1min_DFCF/sz301439.csv
2023-11-24 sz301446 福事特
./1min_DFCF/sz301446.csv
2023-11-24 sz301448 开创电气
./1min_DFCF/sz301448.csv
2023-11-24 sz301456 盘古智能
./1min_DFCF/sz301456.csv
2023-11-24 sz301468 博盈特焊
./1min_DFCF/sz301468.csv
2023-11-24 sz301469 恒达新材
./1min_DFCF/sz301469.csv
2023-11-24 sz301486 致尚科技

./1min_DFCF/sz301486.csv
2023-11-24 sz301487 盟固利
./1min_DFCF/sz301487.csv
2023-11-24 sz301488 豪恩汽电
./1min_DFCF/sz301488.csv
2023-11-24 sz301489 思泉新材
./1min_DFCF/sz301489.csv
2023-11-24 sz301498 乖宝宠物
./1min_DFCF/sz301498.csv
2023-11-24 sz301499 维科精密
./1min_DFCF/sz301499.csv
2023-11-24 sz301500 飞南资源
./1min_DFCF/sz301500.csv
2023-11-24 sz301503 智迪科技
./1min_DFCF/sz301503.csv
2023-11-24 sz301505 苏州规划
./1min_DFCF/sz301505.csv
2023-11-24 sz301507 民生健康
./1min_DFCF/sz301507.csv
2023-11-24 sz301509 金凯生科
./1min_DFCF/sz301509.csv
2023-11-24 sz301510 固高科技
./1min_DFCF/sz301510.csv
2023-11-24 sz301511 德福科技
./1min_DFCF/sz301511.csv
2023-11-24 sz301512 智信精密
./1min_DFCF/sz301512.csv
2023-11-24 sz301515 港通医疗
./1min_DFCF/sz301515.csv
2023-11-24 sz301517 陕西华达
./1min_DFCF/sz301517.csv
2023-11-24 sz301518 长华化学
./1min_DFCF/sz301518.csv
2023-11-24 sz301519 舜禹股份
./1min_DFCF/sz301519.csv
2023-11-24 sz301520 万邦医药
./1min_DFCF/sz301520.csv
2023-11-24 sz301525 儒竞科技
./1min_DFCF/sz301525.csv
2023-11-24 sz301528 多浦乐
./1min_DFCF/sz301528.csv
2023-11-24 sz301529 福赛科技
./1min_DFCF/sz301529.csv
2023-11-24 sz301533 威马农机
./1min_DFCF/sz301533.csv
2023-11-24 sz301548 崇德科技
./1min_DFCF/sz301548.csv
2023-11-24 sz301550 斯菱股份
./1min_DFCF/sz301550.csv
2023-11-24 sz301555 惠柏新材
./1min_DFCF/sz301555.csv
2023-11-24 sz301558 三态股份
./1min_DFCF/sz301558.csv
2023-11-24 sz301559 中集环科
./1min_DFCF/sz301559.csv

In [48]:
import glob
import pandas as pd
import os
folder_path = './1min_DFCF'

# Get all csv files
csv_files = glob.glob(os.path.join(folder_path, '*.csv'))
print(csv_files)
# New dataframe
df = pd.DataFrame()

# Iterate every csv file and concat data together
for f in csv_files:
    data = pd.read_csv(f,encoding='gbk')
    df = pd.concat([df, data])

# Merge csv files
df.to_csv('Fact_Stock_Minute.csv', index=False,encoding='gbk')

['./1min_DFCF/sh688136.csv', './1min_DFCF/sh603105.csv', './1min_DFCF/sz002435.csv', './1min_DFCF/sz002353.csv', './1min_DFCF/sz000544.csv', './1min_DFCF/sh603663.csv', './1min_DFCF/sz000550.csv', './1min_DFCF/sz001896.csv', './1min_DFCF/sh603677.csv', './1min_DFCF/sz002347.csv', './1min_DFCF/sz301190.csv', './1min_DFCF/sh600418.csv', './1min_DFCF/sz002421.csv', './1min_DFCF/sh688122.csv', './1min_DFCF/sh603111.csv', './1min_DFCF/sz002409.csv', './1min_DFCF/sh603139.csv', './1min_DFCF/sh603887.csv', './1min_DFCF/sh600356.csv', './1min_DFCF/sh688678.csv', './1min_DFCF/sh603893.csv', './1min_DFCF/sh688693.csv', './1min_DFCF/sh603878.csv', './1min_DFCF/sz002390.csv', './1min_DFCF/sz300259.csv', './1min_DFCF/sz301153.csv', './1min_DFCF/sz002384.csv', './1min_DFCF/sh688687.csv', './1min_DFCF/sz000593.csv', './1min_DFCF/sz300503.csv', './1min_DFCF/sh600395.csv', './1min_DFCF/sz300265.csv', './1min_DFCF/sh603688.csv', './1min_DFCF/sh600381.csv', './1min_DFCF/sz300271.csv', './1min_DFCF/sz300517.csv', './1min_DFCF/sh601921.csv', './1min_DFCF/sz301386.csv', './1min_DFCF/sh600168.csv', './1min_DFCF/sz300098.csv', './1min_DFCF/sz002151.csv', './1min_DFCF/sz002637.csv', './1min_DFCF/sz300926.csv', './1min_DFCF/sz000020.csv', './1min_DFCF/sh603307.csv', './1min_DFCF/sh688334.csv', './1min_DFCF/sz000034.csv', './1min_DFCF/sh603313.csv', './1min_DFCF/sh688320.csv', './1min_DFCF/sz002623.csv', './1min_DFCF/sz300932.csv', './1min_DFCF/sz002145.csv', './1min_DFCF/sz000752.csv', './1min_DFCF/sh688308.csv', './1min_DFCF/sh600626.csv', './1min_DFCF/sz000008.csv', './1min_DFCF/sz001316.csv', './1min_DFCF/sz002179.csv', './1min_DFCF/sz002192.csv', './1min_DFCF/sz301345.csv', './1min_DFCF/sz000785.csv', './1min_DFCF/sh600815.csv', './1min_DFCF/sz002838.csv', './1min_DFCF/sh600801.csv', './1min_DFCF/sz300729.csv', './1min_DFCF/sz000791.csv', './1min_DFCF/sh688485.csv', './1min_DFCF/sz000949.csv', './1min_DFCF/sz002186.csv', './1min_DFCF/sz000961.csv', './1min_DFCF/sz300067.csv', './1min_DFCF/sh600197.csv', './1min_DFCF/sz301379.csv', './1min_DFCF/sz002810.csv', './1min_DFCF/bj836433.csv', './1min_DFCF/sh600829.csv', './1min_DFCF/sz300701.csv', './1min_DFCF/sz300715.csv', './1min_DFCF/sz300073.csv', './1min_DFCF/sh600183.csv', './1min_DFCF/sz000975.csv', './1min_DFCF/sz000632.csv', './1min_DFCF/sh603515.csv', './1min_DFCF/sh688526.csv', './1min_DFCF/sz002025.csv', './1min_DFCF/sz300852.csv', './1min_DFCF/sz002743.csv', './1min_DFCF/sh603273.csv', './1min_DFCF/sh603267.csv', './1min_DFCF/sz300846.csv', './1min_DFCF/sz002757.csv', './1min_DFCF/sz002031.csv', './1min_DFCF/sh600008.csv', './1min_DFCF/sz000626.csv', './1min_DFCF/sh603501.csv', './1min_DFCF/sz002019.csv', './1min_DFCF/sh600020.csv', './1min_DFCF/sh603529.csv', './1min_DFCF/sh605158.csv', './1min_DFCF/sh600746.csv', './1min_DFCF/sh688268.csv', './1min_DFCF/sz301231.csv', './1min_DFCF/sz000829.csv', './1min_DFCF/sz001289.csv', './1min_DFCF/sh688283.csv', './1min_DFCF/sz300649.csv', './1min_DFCF/sz002780.csv', './1min_DFCF/sh600961.csv', './1min_DFCF/sz300891.csv', './1min_DFCF/sz002958.csv', './1min_DFCF/sh600975.csv', './1min_DFCF/sz300885.csv', './1min_DFCF/sh688297.csv', './1min_DFCF/sz301225.csv', './1min_DFCF/sz000815.csv', './1min_DFCF/bj836221.csv', './1min_DFCF/sz300113.csv', './1min_DFCF/sz300675.csv', './1min_DFCF/sh600785.csv', './1min_DFCF/sh603298.csv', './1min_DFCF/bj832735.csv', './1min_DFCF/sz300661.csv', './1min_DFCF/sh600791.csv', './1min_DFCF/sz002970.csv', './1min_DFCF/sz301219.csv', './1min_DFCF/sz300107.csv', './1min_DFCF/sz000801.csv', './1min_DFCF/sh603071.csv', './1min_DFCF/sz002541.csv', './1min_DFCF/sh601666.csv', './1min_DFCF/sz300488.csv', './1min_DFCF/sh600578.csv', './1min_DFCF/sh601100.csv', './1min_DFCF/sz002227.csv', './1min_DFCF/sh605366.csv', './1min_DFCF/sh603717.csv', './1min_DFCF/sz000430.csv', './1min_DFCF/sh603703.csv', './1min_DFCF/sz002233.csv', './1min_DFCF/sz002555.csv', './1min_DFCF/sh603065.csv', './1min_DFCF/sh688056.csv', './1min_DFCF/sh601882.csv', './1min_DFCF/sh688718.csv', './1min_DFCF/sh600222.csv', './1min_DFCF/sh600236.csv', './1min_DFCF/sh601128.csv', './1min_DFCF/sh603059.csv', './1min_DFCF/sz002569.csv', './1min_DFCF/sh600550.csv', './1min_DFCF/sz002582.csv', './1min_DFCF/sh688081.csv', './1min_DFCF/sz301033.csv', './1min_DFCF/sz300339.csv', './1min_DFCF/sz301027.csv', './1min_DFCF/sh603918.csv', './1min_DFCF/sh688095.csv', './1min_DFCF/sh601869.csv', './1min_DFCF/sz002596.csv', './1min_DFCF/sh600587.csv', './1min_DFCF/sz300477.csv', './1min_DFCF/sh601699.csv', './1min_DFCF/sz300311.csv', './1min_DFCF/sh605399.csv', './1min_DFCF/sz300305.csv', './1min_DFCF/sh600593.csv', './1min_DFCF/sz300463.csv', './1min_DFCF/sz300304.csv', './1min_DFCF/sz300462.csv', './1min_DFCF/sh600592.csv', './1min_DFCF/sh601698.csv', './1min_DFCF/sz300476.csv', './1min_DFCF/sh600586.csv', './1min_DFCF/bj832522.csv', './1min_DFCF/sh605398.csv', './1min_DFCF/sh603931.csv', './1min_DFCF/sz300310.csv', './1min_DFCF/sh603919.csv', './1min_DFCF/sz301026.csv', './1min_DFCF/sz300338.csv', './1min_DFCF/sz002597.csv', './1min_DFCF/sh601868.csv', './1min_DFCF/sh688080.csv', './1min_DFCF/sz002583.csv', './1min_DFCF/sz301032.csv', './1min_DFCF/bj832278.csv', './1min_DFCF/sz000419.csv', './1min_DFCF/sh600237.csv', './1min_DFCF/sh600551.csv', './1min_DFCF/sz002568.csv', './1min_DFCF/sh603058.csv', './1min_DFCF/sh600545.csv', './1min_DFCF/sh600223.csv', './1min_DFCF/sh688719.csv', './1min_DFCF/sz002232.csv', './1min_DFCF/sz000425.csv', './1min_DFCF/sh688057.csv', './1min_DFCF/sz002554.csv', './1min_DFCF/sh600579.csv', './1min_DFCF/sz300489.csv', './1min_DFCF/sz002540.csv', './1min_DFCF/sh603070.csv', './1min_DFCF/sh603716.csv', './1min_DFCF/sz002226.csv', './1min_DFCF/bj871396.csv', './1min_DFCF/sh601101.csv', './1min_DFCF/sz002971.csv', './1min_DFCF/sh600790.csv', './1min_DFCF/sz300660.csv', './1min_DFCF/sh603299.csv', './1min_DFCF/sz000800.csv', './1min_DFCF/sz300106.csv', './1min_DFCF/sz301218.csv', './1min_DFCF/sz300112.csv', './1min_DFCF/sz002965.csv', './1min_DFCF/sh600784.csv', './1min_DFCF/sz300674.csv', './1min_DFCF/sh688296.csv', './1min_DFCF/sz300884.csv', './1min_DFCF/sz002795.csv', './1min_DFCF/bj836208.csv', './1min_DFCF/sz000828.csv', './1min_DFCF/sz301230.csv', './1min_DFCF/sz002959.csv', './1min_DFCF/sz300890.csv', './1min_DFCF/sh600960.csv', './1min_DFCF/sz300648.csv', './1min_DFCF/sh688282.csv', './1min_DFCF/sz001288.csv', './1min_DFCF/sh688269.csv', './1min_DFCF/sh600753.csv', './1min_DFCF/sh600035.csv', './1min_DFCF/sh603528.csv', './1min_DFCF/sh600021.csv', './1min_DFCF/sz002756.csv', './1min_DFCF/sz300847.csv', './1min_DFCF/sh603266.csv', './1min_DFCF/sh688255.csv', './1min_DFCF/sh688533.csv', './1min_DFCF/sh603500.csv', './1min_DFCF/sz000627.csv', './1min_DFCF/sh600009.csv', './1min_DFCF/sz002030.csv', './1min_DFCF/sz002024.csv', './1min_DFCF/sz000633.csv', './1min_DFCF/sz000155.csv', './1min_DFCF/sh603272.csv', './1min_DFCF/sz002742.csv', './1min_DFCF/sz300853.csv', './1min_DFCF/sz002805.csv', './1min_DFCF/sh600182.csv', './1min_DFCF/sz300072.csv', './1min_DFCF/sz301378.csv', './1min_DFCF/sh600196.csv', './1min_DFCF/sz300066.csv', './1min_DFCF/sh601288.csv', './1min_DFCF/sz000960.csv', './1min_DFCF/sz300700.csv', './1min_DFCF/sh600828.csv', './1min_DFCF/sz002811.csv', './1min_DFCF/sh600800.csv', './1min_DFCF/bj839729.csv', './1min_DFCF/sz002839.csv', './1min_DFCF/sz002187.csv', './1min_DFCF/sz000948.csv', './1min_DFCF/sh688484.csv', './1min_DFCF/sz000790.csv', './1min_DFCF/sz002193.csv', './1min_DFCF/sh600814.csv', './1min_DFCF/bj873152.csv', './1min_DFCF/sz001317.csv', './1min_DFCF/sz000009.csv', './1min_DFCF/sz002178.csv', './1min_DFCF/sh600141.csv', './1min_DFCF/sh600155.csv', './1min_DFCF/sh600633.csv', './1min_DFCF/sh688309.csv', './1min_DFCF/sz300933.csv', './1min_DFCF/sz002622.csv', './1min_DFCF/sh688321.csv', './1min_DFCF/sz000035.csv', './1min_DFCF/sz000753.csv', './1min_DFCF/sh605005.csv', './1min_DFCF/sz002144.csv', './1min_DFCF/sz301393.csv', './1min_DFCF/sz002150.csv', './1min_DFCF/sz300099.csv', './1min_DFCF/sh600169.csv', './1min_DFCF/sz301387.csv', './1min_DFCF/sh605011.csv', './1min_DFCF/sh688335.csv', './1min_DFCF/sh603306.csv', './1min_DFCF/sz000021.csv', './1min_DFCF/sz300927.csv', './1min_DFCF/sz002636.csv', './1min_DFCF/sz300270.csv', './1min_DFCF/sh600380.csv', './1min_DFCF/sh603689.csv', './1min_DFCF/bj834033.csv', './1min_DFCF/sz300516.csv', './1min_DFCF/sz300502.csv', './1min_DFCF/sz300264.csv', './1min_DFCF/sz000592.csv', './1min_DFCF/sh688686.csv', './1min_DFCF/sz002385.csv', './1min_DFCF/sz301152.csv', './1min_DFCF/bj871553.csv', './1min_DFCF/bj835305.csv', './1min_DFCF/sh601908.csv', './1min_DFCF/sz300258.csv', './1min_DFCF/sz002391.csv', './1min_DFCF/sz000586.csv', './1min_DFCF/sh603879.csv', './1min_DFCF/sh688679.csv', './1min_DFCF/sh600343.csv', './1min_DFCF/sh600425.csv', './1min_DFCF/sh603138.csv', './1min_DFCF/sz002408.csv', './1min_DFCF/sh603886.csv', './1min_DFCF/sz301191.csv', './1min_DFCF/sh601061.csv', './1min_DFCF/sz002346.csv', './1min_DFCF/sh603676.csv', './1min_DFCF/sz000551.csv', './1min_DFCF/sh603110.csv', './1min_DFCF/sh688123.csv', './1min_DFCF/sz002420.csv', './1min_DFCF/sh600419.csv', './1min_DFCF/sz002434.csv', './1min_DFCF/sh688137.csv', './1min_DFCF/sh688651.csv', './1min_DFCF/sh603662.csv', './1min_DFCF/sz000545.csv', './1min_DFCF/sz301185.csv', './1min_DFCF/sz002352.csv', './1min_DFCF/sz002422.csv', './1min_DFCF/sh688121.csv', './1min_DFCF/sh603112.csv', './1min_DFCF/sz000553.csv', './1min_DFCF/bj872925.csv', './1min_DFCF/sz002344.csv', './1min_DFCF/sz301193.csv', './1min_DFCF/sz002350.csv', './1min_DFCF/sz300299.csv', './1min_DFCF/sh601077.csv', './1min_DFCF/sz301187.csv', './1min_DFCF/sh600369.csv', './1min_DFCF/sz000547.csv', './1min_DFCF/sh603660.csv', './1min_DFCF/sh688653.csv', './1min_DFCF/sh605577.csv', './1min_DFCF/sh688135.csv', './1min_DFCF/sh603106.csv', './1min_DFCF/sz002436.csv', './1min_DFCF/bj838810.csv', './1min_DFCF/sz002378.csv', './1min_DFCF/bj831834.csv', './1min_DFCF/sh603648.csv', './1min_DFCF/sh603890.csv', './1min_DFCF/sh600355.csv', './1min_DFCF/sh600433.csv', './1min_DFCF/sh688109.csv', './1min_DFCF/sz300528.csv', './1min_DFCF/sz301150.csv', './1min_DFCF/sz002387.csv', './1min_DFCF/sz000590.csv', './1min_DFCF/sh688690.csv', './1min_DFCF/sz000584.csv', './1min_DFCF/sz002393.csv', './1min_DFCF/sz300514.csv', './1min_DFCF/sh600382.csv', './1min_DFCF/bj839273.csv', './1min_DFCF/sz300272.csv', './1min_DFCF/sh600396.csv', './1min_DFCF/sz301178.csv', './1min_DFCF/sh601088.csv', './1min_DFCF/sz300266.csv', './1min_DFCF/sh605588.csv', './1min_DFCF/sz300500.csv', './1min_DFCF/sz301391.csv', './1min_DFCF/sz002146.csv', './1min_DFCF/sh605007.csv', './1min_DFCF/sz000989.csv', './1min_DFCF/sz000751.csv', './1min_DFCF/sz000037.csv', './1min_DFCF/sh688323.csv', './1min_DFCF/sz002620.csv', './1min_DFCF/sh600619.csv', './1min_DFCF/sz300931.csv', './1min_DFCF/sz002634.csv', './1min_DFCF/sz300925.csv', './1min_DFCF/sz000023.csv', './1min_DFCF/sh688337.csv', './1min_DFCF/sz002152.csv', './1min_DFCF/sh688479.csv', './1min_DFCF/sh600143.csv', './1min_DFCF/sh603338.csv', './1min_DFCF/sz001301.csv', './1min_DFCF/sz002608.csv', './1min_DFCF/sz300919.csv', './1min_DFCF/bj836395.csv', './1min_DFCF/sh600157.csv', './1min_DFCF/sz000779.csv', './1min_DFCF/sz000792.csv', './1min_DFCF/sh688486.csv', './1min_DFCF/sz002185.csv', './1min_DFCF/sh600802.csv', './1min_DFCF/bj871753.csv', './1min_DFCF/sh600816.csv', './1min_DFCF/sz300058.csv', './1min_DFCF/sz002191.csv', './1min_DFCF/sz000786.csv', './1min_DFCF/sz300070.csv', './1min_DFCF/sh600180.csv', './1min_DFCF/sh603489.csv', './1min_DFCF/sz000976.csv', './1min_DFCF/sz002807.csv', './1min_DFCF/sz301408.csv', './1min_DFCF/sz300716.csv', './1min_DFCF/sz002813.csv', './1min_DFCF/sz300702.csv', './1min_DFCF/sz000962.csv', './1min_DFCF/sz002032.csv', './1min_DFCF/sz000625.csv', './1min_DFCF/sh688531.csv', './1min_DFCF/sh688257.csv', './1min_DFCF/sz300845.csv', './1min_DFCF/sz300851.csv', './1min_DFCF/sh600779.csv', './1min_DFCF/sz002998.csv', './1min_DFCF/sz300689.csv', './1min_DFCF/sz002740.csv', './1min_DFCF/sh603270.csv', './1min_DFCF/sz000157.csv', './1min_DFCF/sz000631.csv', './1min_DFCF/sh603516.csv', './1min_DFCF/sh688525.csv', './1min_DFCF/sh605167.csv', './1min_DFCF/sz002026.csv', './1min_DFCF/sz000619.csv', './1min_DFCF/sh600037.csv', './1min_DFCF/sz300879.csv', './1min_DFCF/sh600751.csv', './1min_DFCF/sz002768.csv', './1min_DFCF/sh600989.csv', './1min_DFCF/sh603258.csv', './1min_DFCF/sh600745.csv', './1min_DFCF/sh600023.csv', './1min_DFCF/sh688519.csv', './1min_DFCF/sz301226.csv', './1min_DFCF/bj838227.csv', './1min_DFCF/sz300138.csv', './1min_DFCF/sh600976.csv', './1min_DFCF/sz002797.csv', './1min_DFCF/sz300886.csv', './1min_DFCF/sh688280.csv', './1min_DFCF/sh600962.csv', './1min_DFCF/sz002783.csv', './1min_DFCF/sz300892.csv', './1min_DFCF/sz301232.csv', './1min_DFCF/sz000802.csv', './1min_DFCF/sz300662.csv', './1min_DFCF/sz002973.csv', './1min_DFCF/sh600792.csv', './1min_DFCF/sz300676.csv', './1min_DFCF/sz002967.csv', './1min_DFCF/sz000816.csv', './1min_DFCF/sh605198.csv', './1min_DFCF/sz300110.csv', './1min_DFCF/sz002556.csv', './1min_DFCF/sh603066.csv', './1min_DFCF/sh688055.csv', './1min_DFCF/sh688733.csv', './1min_DFCF/sh603700.csv', './1min_DFCF/sh601117.csv', './1min_DFCF/sz002230.csv', './1min_DFCF/sz002224.csv', './1min_DFCF/sh605365.csv', './1min_DFCF/bj833819.csv', './1min_DFCF/sh688041.csv', './1min_DFCF/sz002542.csv', './1min_DFCF/sh601665.csv', './1min_DFCF/sh688069.csv', './1min_DFCF/sh600235.csv', './1min_DFCF/sh603728.csv', './1min_DFCF/sh600221.csv', './1min_DFCF/sz002218.csv', './1min_DFCF/sh600547.csv', './1min_DFCF/sh601881.csv', './1min_DFCF/sh688096.csv', './1min_DFCF/sz002595.csv', './1min_DFCF/sz301024.csv', './1min_DFCF/sz301030.csv', './1min_DFCF/sz002581.csv', './1min_DFCF/sz300448.csv', './1min_DFCF/sh688082.csv', './1min_DFCF/sh600590.csv', './1min_DFCF/sz300460.csv', './1min_DFCF/sh603099.csv', './1min_DFCF/sh603927.csv', './1min_DFCF/sz300306.csv', './1min_DFCF/sz301018.csv', './1min_DFCF/sh603933.csv', './1min_DFCF/sh600584.csv', './1min_DFCF/sz300474.csv', './1min_DFCF/sz300313.csv', './1min_DFCF/sz300475.csv', './1min_DFCF/sh600585.csv', './1min_DFCF/sh603098.csv', './1min_DFCF/sz300461.csv', './1min_DFCF/sh601857.csv', './1min_DFCF/sz301019.csv', './1min_DFCF/sz300307.csv', './1min_DFCF/sh603926.csv', './1min_DFCF/sz301031.csv', './1min_DFCF/bj838030.csv', './1min_DFCF/sh688083.csv', './1min_DFCF/sz300449.csv', './1min_DFCF/sz002580.csv', './1min_DFCF/sz002594.csv', './1min_DFCF/sh688097.csv', './1min_DFCF/bj833171.csv', './1min_DFCF/sz301025.csv', './1min_DFCF/sz002219.csv', './1min_DFCF/sh600220.csv', './1min_DFCF/sh603729.csv', './1min_DFCF/sh605358.csv', './1min_DFCF/sh601880.csv', './1min_DFCF/bj838971.csv', './1min_DFCF/sh600546.csv', './1min_DFCF/sh601658.csv', './1min_DFCF/sh600552.csv', './1min_DFCF/sh688068.csv', './1min_DFCF/sh600234.csv', './1min_DFCF/sz002225.csv', './1min_DFCF/sz002543.csv', './1min_DFCF/sh603073.csv', './1min_DFCF/sh603067.csv', './1min_DFCF/sz002557.csv', './1min_DFCF/sz002231.csv', './1min_DFCF/sh601116.csv', './1min_DFCF/sh600208.csv', './1min_DFCF/sz000426.csv', './1min_DFCF/sh603701.csv', './1min_DFCF/sh600787.csv', './1min_DFCF/sz002966.csv', './1min_DFCF/sz300677.csv', './1min_DFCF/sz300111.csv', './1min_DFCF/sh605199.csv', './1min_DFCF/sz000803.csv', './1min_DFCF/sz300105.csv', './1min_DFCF/sh600793.csv', './1min_DFCF/sz002972.csv', './1min_DFCF/sz300663.csv', './1min_DFCF/bj833429.csv', './1min_DFCF/sz301555.csv', './1min_DFCF/sz300893.csv', './1min_DFCF/sz002782.csv', './1min_DFCF/sh600963.csv', './1min_DFCF/sh688281.csv', './1min_DFCF/sz301233.csv', './1min_DFCF/sz300139.csv', './1min_DFCF/sz301227.csv', './1min_DFCF/sh688295.csv', './1min_DFCF/sz300887.csv', './1min_DFCF/sz002796.csv', './1min_DFCF/sh600977.csv', './1min_DFCF/sh600744.csv', './1min_DFCF/sh688518.csv', './1min_DFCF/sh600022.csv', './1min_DFCF/sh600036.csv', './1min_DFCF/sh601328.csv', './1min_DFCF/sh603259.csv', './1min_DFCF/sz001260.csv', './1min_DFCF/sh600988.csv', './1min_DFCF/sz002769.csv', './1min_DFCF/sh600750.csv', './1min_DFCF/sz300878.csv', './1min_DFCF/sz000156.csv', './1min_DFCF/sz002741.csv', './1min_DFCF/sz300688.csv', './1min_DFCF/sz002999.csv', './1min_DFCF/sh600778.csv', './1min_DFCF/sz300850.csv', './1min_DFCF/sz002027.csv', './1min_DFCF/sh605166.csv', './1min_DFCF/bj430556.csv', './1min_DFCF/sh603517.csv', './1min_DFCF/sz000630.csv', './1min_DFCF/sz002033.csv', './1min_DFCF/sz002755.csv', './1min_DFCF/sz300844.csv', './1min_DFCF/sh688256.csv', './1min_DFCF/sz300703.csv', './1min_DFCF/sz002812.csv', './1min_DFCF/sh600195.csv', './1min_DFCF/sz300065.csv', './1min_DFCF/sz000963.csv', './1min_DFCF/sz000977.csv', './1min_DFCF/bj835892.csv', './1min_DFCF/sh603488.csv', './1min_DFCF/sz300071.csv', './1min_DFCF/sz300717.csv', './1min_DFCF/sz002806.csv', './1min_DFCF/sh600817.csv', './1min_DFCF/sz301421.csv', './1min_DFCF/bj833575.csv', './1min_DFCF/sz002190.csv', './1min_DFCF/sz300059.csv', './1min_DFCF/sz301353.csv', './1min_DFCF/sz002184.csv', './1min_DFCF/sz000793.csv', './1min_DFCF/sh600803.csv', './1min_DFCF/bj836419.csv', './1min_DFCF/sz300918.csv', './1min_DFCF/sh600630.csv', './1min_DFCF/sz002609.csv', './1min_DFCF/sz001300.csv', './1min_DFCF/sh603339.csv', './1min_DFCF/sz000778.csv', './1min_DFCF/sh600156.csv', './1min_DFCF/sh688478.csv', './1min_DFCF/sz001314.csv', './1min_DFCF/sh600624.csv', './1min_DFCF/sh688336.csv', './1min_DFCF/sh603305.csv', './1min_DFCF/sh601512.csv', './1min_DFCF/sz002635.csv', './1min_DFCF/sz002153.csv', './1min_DFCF/sh688450.csv', './1min_DFCF/sz000750.csv', './1min_DFCF/sh603477.csv', './1min_DFCF/sz000988.csv', './1min_DFCF/sh605006.csv', './1min_DFCF/sz301390.csv', './1min_DFCF/sz300930.csv', './1min_DFCF/sh600618.csv', './1min_DFCF/sz002621.csv', './1min_DFCF/sz001328.csv', './1min_DFCF/sh688322.csv', './1min_DFCF/sh603311.csv', './1min_DFCF/sz000036.csv', './1min_DFCF/sz300267.csv', './1min_DFCF/sh601089.csv', './1min_DFCF/sz301179.csv', './1min_DFCF/sh600397.csv', './1min_DFCF/sz300501.csv', './1min_DFCF/sh605589.csv', './1min_DFCF/sz300515.csv', './1min_DFCF/sh600383.csv', './1min_DFCF/sz002392.csv', './1min_DFCF/bj832469.csv', './1min_DFCF/sz300529.csv', './1min_DFCF/sz000591.csv', './1min_DFCF/sh688685.csv', './1min_DFCF/sz002386.csv', './1min_DFCF/sz301151.csv', './1min_DFCF/sh600354.csv', './1min_DFCF/sh603885.csv', './1min_DFCF/sh688108.csv', './1min_DFCF/sh600426.csv', './1min_DFCF/sh600340.csv', './1min_DFCF/sz002379.csv', './1min_DFCF/sh603661.csv', './1min_DFCF/sz000546.csv', './1min_DFCF/sh600368.csv', './1min_DFCF/sz301186.csv', './1min_DFCF/sz300298.csv', './1min_DFCF/sz002351.csv', './1min_DFCF/sz002437.csv', './1min_DFCF/sh603107.csv', './1min_DFCF/sh603113.csv', './1min_DFCF/sh688120.csv', './1min_DFCF/sz002423.csv', './1min_DFCF/sz301192.csv', './1min_DFCF/sz002345.csv', './1min_DFCF/sh688646.csv', './1min_DFCF/sz000552.csv', './1min_DFCF/sh603895.csv', './1min_DFCF/sh688118.csv', './1min_DFCF/sh600422.csv', './1min_DFCF/sh600436.csv', './1min_DFCF/sh601728.csv', './1min_DFCF/sh603659.csv', './1min_DFCF/sh605228.csv', './1min_DFCF/sh603881.csv', './1min_DFCF/sz002369.csv', './1min_DFCF/sh600350.csv', './1min_DFCF/sz300288.csv', './1min_DFCF/sh601066.csv', './1min_DFCF/sz002341.csv', './1min_DFCF/sz301196.csv', './1min_DFCF/sh600378.csv', './1min_DFCF/sz002427.csv', './1min_DFCF/sh601700.csv', './1min_DFCF/sh605566.csv', './1min_DFCF/sh603117.csv', './1min_DFCF/sh688130.csv', './1min_DFCF/sh603103.csv', './1min_DFCF/sz002433.csv', './1min_DFCF/sz002355.csv', './1min_DFCF/sz301182.csv', './1min_DFCF/sh603665.csv', './1min_DFCF/sh688656.csv', './1min_DFCF/sh603856.csv', './1min_DFCF/sh600387.csv', './1min_DFCF/sz301169.csv', './1min_DFCF/sh601099.csv', './1min_DFCF/sz300277.csv', './1min_DFCF/sz300511.csv', './1min_DFCF/sh605599.csv', './1min_DFCF/sz300505.csv', './1min_DFCF/sh601933.csv', './1min_DFCF/sz300263.csv', './1min

# Update Minute Data into Postgres

In [6]:
def GetMinuteID(x:str):
    dt = datetime.strptime(x, "%Y-%m-%d %H:%M:%S")
    result = int(dt.strftime("%Y%m%d%H%M"))
    return result
    
def check_data_exist(Start_Min:str, stockid:str):
    sql = "SELECT COUNT(fsm_id) from \"Trading\".Fact_Stock_Minute\
                where Minute_ID=" + str(GetMinuteID(Start_Min)) + " and Stock_ID=" + stockid+";"
    conn = psycopg2.connect(host="localhost", database="yuzhuoran", user="postgres", password="YZRyzr010306!")
    cur = conn.cursor()
    conn.commit()
    conn.rollback()
    conn.autocommit = True
    cur.execute(sql)
    col_names = [desc [0] for desc in cur.description]
    results = cur.fetchall()
    cur.close()
    return col_names,results
    
def update_minute_data(Current_Date:str):
    conn = psycopg2.connect(host="localhost", database="yuzhuoran", user="postgres", password="YZRyzr010306!")
    cur = conn.cursor()
    conn.commit()
    conn.rollback()
    conn.autocommit = True
    start_min = Current_Date + ' 09:30:00'
    end_min = Current_Date + ' 15:00:00'
    for CodeDes in code_list.values:
        ak_code, ak_name = CodeDes[1],CodeDes[2]
        print(Current_Date,ak_code,ak_name)
        col,result = check_data_exist(start_min, ak_code[2:])
        if result[0][0]>0:
            print("Exists")
            continue
        try:
            stock_zh_a_hist_min_em_df = ak.stock_zh_a_hist_min_em(symbol=ak_code[2:], start_date=start_min, end_date=end_min, period='1', adjust='')
        except Exception as e:
            print(e)
            continue
        if len(stock_zh_a_hist_min_em_df)==0:
            continue
        stock_zh_a_hist_min_em_df.rename(columns = {'时间':'Time','开盘':'Open','收盘':'Close','最高':'High','最低':'Low',
                                                    '成交量':'Volume','成交额':'Turnover','最新价':'Latest'},inplace = True)
        stock_zh_a_hist_min_em_df['Minute_ID'] = stock_zh_a_hist_min_em_df['Time'].apply(lambda x:GetMinuteID(x))
        stock_zh_a_hist_min_em_df['FSM_ID'] = ak_code[2:]+stock_zh_a_hist_min_em_df['Minute_ID'].astype(str)
        stock_zh_a_hist_min_em_df['Stock_ID'] = ak_code[2:]
        stock_zh_a_hist_min_em_df['Stock_Name'] = ak_name
        stock_zh_a_hist_min_em_df = stock_zh_a_hist_min_em_df[['FSM_ID','Stock_ID','Minute_ID','Open',
                                                               'High','Low','Volume','Stock_Name','Turnover','Close']]
        sql = "INSERT INTO \"Trading\".Fact_Stock_Minute (FSM_ID, Stock_ID, Minute_ID, Open, High, Low, Volume, \
                                        Stock_Name, Turnover, Close) \
                                        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
        
        for index, row in stock_zh_a_hist_min_em_df.iterrows():
            values = (row['FSM_ID'], row['Stock_ID'],row['Minute_ID'],row['Open'], row['High'],row['Low'],row['Volume'],
                    row['Stock_Name'],row['Turnover'],row['Close']) 
            cur.execute(sql, values)
    cur.close()

In [9]:
Current_Date = '2023-12-01'
update_minute_data(Current_Date)

2023-12-01 bj430017 星昊医药
Exists
2023-12-01 bj430047 诺思兰德
Exists
2023-12-01 bj430090 同辉信息
Exists
2023-12-01 bj430139 华岭股份
Exists
2023-12-01 bj430198 微创光电
Exists
2023-12-01 bj430300 辰光医疗
Exists
2023-12-01 bj430418 苏轴股份
Exists
2023-12-01 bj430425 乐创技术
Exists
2023-12-01 bj430476 海能技术
Exists
2023-12-01 bj430478 峆一药业
Exists
2023-12-01 bj430489 佳先股份
Exists
2023-12-01 bj430510 丰光精密
Exists
2023-12-01 bj430556 雅达股份
Exists
2023-12-01 bj430564 天润科技
Exists
2023-12-01 bj430685 新芝生物
Exists
2023-12-01 bj430718 合肥高科
Exists
2023-12-01 bj830779 武汉蓝电
Exists
2023-12-01 bj830799 艾融软件
Exists
2023-12-01 bj830809 安达科技
Exists
2023-12-01 bj830832 齐鲁华信
Exists
2023-12-01 bj830839 万通液压
Exists
2023-12-01 bj830879 基康仪器
Exists
2023-12-01 bj830896 旺成科技
Exists
2023-12-01 bj830946 森萱医药
Exists
2023-12-01 bj830964 润农节水
Exists
2023-12-01 bj830974 凯大催化
Exists
2023-12-01 bj831010 凯添燃气
Exists
2023-12-01 bj831039 国义招标
Exists
2023-12-01 bj831087 秋乐种业
Exists
2023-12-01 bj831152 昆工科技
Exists
2023-12-01 bj831167 鑫汇科
Exists
2023-12-01 bj831195 三祥科技
Exists
2023-12-01 bj831278 泰德股份
Exists
2023-12-01 bj831304 迪尔化工
Exists
2023-12-01 bj831305 海希通讯
Exists
2023-12-01 bj831370 新安洁
Exists
2023-12-01 bj831445 龙竹科技
Exists
2023-12-01 bj831526 凯华材料
Exists
2023-12-01 bj831627 力王股份
Exists
2023-12-01 bj831641 格利尔
Exists
2023-12-01 bj831689 克莱特
Exists
2023-12-01 bj831726 朱老六
Exists
2023-12-01 bj831768 拾比佰
Exists
2023-12-01 bj831832 科达自控
Exists
2023-12-01 bj831834 三维股份
Exists
2023-12-01 bj831855 浙江大农
Exists
2023-12-01 bj831856 浩淼科技
Exists
2023-12-01 bj831906 舜宇精工
Exists
2023-12-01 bj831961 创远信科
Exists
2023-12-01 bj832000 安徽凤凰
Exists
2023-12-01 bj832023 田野股份
Exists
2023-12-01 bj832089 禾昌聚合
Exists
2023-12-01 bj832110 雷特科技
Exists
2023-12-01 bj832145 恒合股份
Exists
2023-12-01 bj832149 利尔达
Exists
2023-12-01 bj832171 志晟信息
Exists
2023-12-01 bj832175 东方碳素
Exists
2023-12-01 bj832225 利通科技
Exists
2023-12-01 bj832278 鹿得医疗
Exists
2023-12-01 bj832419 路斯股份
Exists
2023-12-01 bj832469 富恒新材
Exists
2023-12-01 bj832471 美邦科技
Exists
2023-12-01 bj832491 奥迪威
Exists
2023-12-01 bj832522 纳科诺尔
Exists
2023-12-01 bj832566 梓橦宫
Exists
2023-12-01 bj832651 天罡股份
Exists
2023-12-01 bj832662 方盛股份
Exists
2023-12-01 bj832735 德源药业
Exists
2023-12-01 bj832786 骑士乳业
Exists
2023-12-01 bj832802 保丽洁
Exists
2023-12-01 bj832876 慧为智能
Exists
2023-12-01 bj832885 星辰科技
Exists
2023-12-01 bj832978 开特股份
Exists
2023-12-01 bj832982 锦波生物
Exists
2023-12-01 bj833030 立方控股
Exists
2023-12-01 bj833075 柏星龙
Exists
2023-12-01 bj833171 国航远洋
Exists
2023-12-01 bj833230 欧康医药
Exists
2023-12-01 bj833266 生物谷
Exists
2023-12-01 bj833346 威贸电子
Exists
2023-12-01 bj833394 民士达
Exists
2023-12-01 bj833427 华维设计
Exists
2023-12-01 bj833429 康比特
Exists
2023-12-01 bj833454 同心传动
Exists
2023-12-01 bj833455 汇隆活塞
Exists
2023-12-01 bj833509 同惠电子
Exists
2023-12-01 bj833523 德瑞锂电
Exists
2023-12-01 bj833533 骏创科技
Exists
2023-12-01 bj833575 康乐卫士
Exists
2023-12-01 bj833580 科创新材
Exists
2023-12-01 bj833751 惠同新材
Exists
2023-12-01 bj833781 瑞奇智造
Exists
2023-12-01 bj833819 颖泰生物
Exists
2023-12-01 bj833873 中设咨询
Exists
2023-12-01 bj833914 远航精密
Exists
2023-12-01 bj833943 优机股份
Exists
2023-12-01 bj834014 特瑞斯
Exists
2023-12-01 bj834021 流金科技
Exists
2023-12-01 bj834033 康普化学
Exists
2023-12-01 bj834058 华洋赛车
Exists
2023-12-01 bj834062 科润智控
Exists
2023-12-01 bj834261 一诺威
Exists
2023-12-01 bj834407 驰诚股份
Exists
2023-12-01 bj834415 恒拓开源
Exists
2023-12-01 bj834475 三友科技
Exists
2023-12-01 bj834599 同力股份
Exists
2023-12-01 bj834639 晨光电缆
Exists
2023-12-01 bj834682 球冠电缆
Exists
2023-12-01 bj834765 美之高
Exists
2023-12-01 bj834770 艾能聚
Exists
2023-12-01 bj834950 迅安科技
Exists
2023-12-01 bj835174 五新隧装
Exists
2023-12-01 bj835179 凯德石英
Exists
2023-12-01 bj835184 国源科技
Exists
2023-12-01 bj835185 贝特瑞
Exists
2023-12-01 bj835207 众诚科技
Exists
2023-12-01 bj835237 力佳科技
Exists
2023-12-01 bj835305 云创数据
Exists
2023-12-01 bj835368 连城数控
Exists
2023-12-01 bj835508 殷图网联
Exists
2023-12-01 bj835640 富士达
Exists
2023-12-01 bj835670 数字人
Exists
2023-12-01 bj835857 百甲科技
Exists
2023-12-01 bj835892 中科美菱
Exists
2023-12-01 bj835985 海泰新能
Exists
2023-12-01 bj836077 吉林碳谷
Exists
2023-12-01 bj836149 旭杰科技
Exists
2023-12-01 bj836208 青矩技术
Exists
2023-12-01 bj836221 易实精密
Exists
2023-12-01 bj836239 长虹能源
Exists
2023-12-01 bj836247 华密新材
Exists
2023-12-01 bj836260 中寰股份
Exists
2023-12-01 bj836263 中航泰达
Exists
2023-12-01 bj836270 天铭科技
Exists
2023-12-01 bj836395 朗鸿科技
Exists
2023-12-01 bj836414 欧普泰
Exists
2023-12-01 bj836419 万德股份
Exists
2023-12-01 bj836422 润普食品
Exists
2023-12-01 bj836433 大唐药业
Exists
2023-12-01 bj836504 博迅生物
Exists
2023-12-01 bj836675 秉扬科技
Exists
2023-12-01 bj836699 海达尔
Exists
2023-12-01 bj836717 瑞星股份
Exists
2023-12-01 bj836720 吉冈精密
Exists
2023-12-01 bj836807 奔朗新材
Exists
2023-12-01 bj836826 盖世食品
Exists
2023-12-01 bj836871 派特尔
Exists
2023-12-01 bj836892 广咨国际
Exists
2023-12-01 bj836942 恒立钻具
Exists
2023-12-01 bj836957 汉维科技
Exists
2023-12-01 bj837006 晟楠科技
Exists
2023-12-01 bj837046 亿能电力
Exists
2023-12-01 bj837092 汉鑫科技
Exists
2023-12-01 bj837174 宏裕包材
Exists
2023-12-01 bj837212 智新电子
Exists
2023-12-01 bj837242 建邦科技
Exists
2023-12-01 bj837344 三元基因
Exists
2023-12-01 bj837592 华信永道
Exists
2023-12-01 bj837663 明阳科技
Exists
2023-12-01 bj837748 路桥信息
Exists
2023-12-01 bj837821 则成电子
Exists
2023-12-01 bj838030 德众汽车
Exists
2023-12-01 bj838163 方大新材
Exists
2023-12-01 bj838171 邦德股份
Exists
2023-12-01 bj838227 美登科技
Exists
2023-12-01 bj838262 太湖雪
Exists
2023-12-01 bj838275 驱动力
Exists
2023-12-01 bj838402 硅烷科技
Exists
2023-12-01 bj838670 恒进感应
Exists
2023-12-01 bj838701 豪声电子
Exists
2023-12-01 bj838810 春光药装
Exists
2023-12-01 bj838837 华原股份
Exists
2023-12-01 bj838924 广脉科技
Exists
2023-12-01 bj838971 天马新材
Exists
2023-12-01 bj839167 同享科技
Exists
2023-12-01 bj839273 一致魔芋
Exists
2023-12-01 bj839371 欧福蛋业
Exists
2023-12-01 bj839493 并行科技
Exists
2023-12-01 bj839680 广道数字
Exists
2023-12-01 bj839719 宁新新材
Exists
2023-12-01 bj839725 惠丰钻石
Exists
2023-12-01 bj839729 永顺生物
Exists
2023-12-01 bj839790 联迪信息
Exists
2023-12-01 bj839792 东和新材
Exists
2023-12-01 bj839946 华阳变速
Exists
2023-12-01 bj870199 倍益康
Exists
2023-12-01 bj870204 沪江材料
Exists
2023-12-01 bj870299 灿能电力
Exists
2023-12-01 bj870357 雅葆轩
Exists
2023-12-01 bj870436 大地电气
Exists
2023-12-01 bj870508 丰安股份
Exists
2023-12-01 bj870726 鸿智科技
Exists
2023-12-01 bj870866 绿亨科技
Exists
2023-12-01 bj870976 视声智能
Exists
2023-12-01 bj871245 威博液压
Exists
2023-12-01 bj871396 常辅股份
Exists
2023-12-01 bj871478 巨能股份
Exists
2023-12-01 bj871553 凯腾精工
Exists
2023-12-01 bj871634 新威凌
Exists
2023-12-01 bj871642 通易航天
Exists
2023-12-01 bj871694 中裕科技
Exists
2023-12-01 bj871753 天纺标
Exists
2023-12-01 bj871857 泓禧科技
Exists
2023-12-01 bj871970 大禹生物
Exists
2023-12-01 bj871981 晶赛科技
Exists
2023-12-01 bj872190 雷神科技
Exists
2023-12-01 bj872351 华光源海
Exists
2023-12-01 bj872374 云里物里
Exists
2023-12-01 bj872392 佳合科技
2023-12-01 bj872541 铁大科技
2023-12-01 bj872808 曙光数创
2023-12-01 bj872895 花溪科技
2023-12-01 bj872925 锦好医疗
2023-12-01 bj872953 国子软件
2023-12-01 bj873001 纬达光电
2023-12-01 bj873122 中纺标
2023-12-01 bj873132 泰鹏智能
2023-12-01 bj873152 天宏锂电
2023-12-01 bj873167 新赣江
2023-12-01 bj873169 七丰精工
2023-12-01 bj873223 荣亿精密
2023-12-01 bj873305 九菱科技
2023-12-01 bj873339 恒太照明
2023-12-01 bj873527 夜光明
2023-12-01 bj873576 天力复合
2023-12-01 bj873593 鼎智科技
2023-12-01 bj873665 科强股份
2023-12-01 bj873679 前进科技
2023-12-01 bj873693 阿为特
2023-12-01 bj873726 卓兆点胶
2023-12-01 bj873833 美心翼申
2023-12-01 sh600000 浦发银行
2023-12-01 sh600004 白云机场
2023-12-01 sh600006 东风汽车
2023-12-01 sh600007 中国国贸
2023-12-01 sh600008 首创环保
2023-12-01 sh600009 上海机场
2023-12-01 sh600010 包钢股份
2023-12-01 sh600011 华能国际
2023-12-01 sh600012 皖通高速
2023-12-01 sh600015 华夏银行
2023-12-01 sh600016 民生银行
2023-12-01 sh600017 日照港
2023-12-01 sh600018 上港集团
2023-12-01 sh600019 宝钢股份
2023-12-01 sh600020 中原高速
2023-12-01 sh600021 上海电力
2023-12-01 sh600022 山东钢铁
2023-12-01 sh600023 浙能电力
2023-12-01 sh600025 华能水电
2023-12-01 sh600026 中远海能
2023-12-01 sh600027 华电国际
2023-12-01 sh600028 中国石化
2023-12-01 sh600029 南方航空
2023-12-01 sh600030 中信证券
2023-12-01 sh600031 三一重工
2023-12-01 sh600032 浙江新能
2023-12-01 sh600033 福建高速
2023-12-01 sh600035 楚天高速
2023-12-01 sh600036 招商银行
2023-12-01 sh600037 歌华有线
2023-12-01 sh600038 中直股份
2023-12-01 sh600039 四川路桥
2023-12-01 sh600048 保利发展
2023-12-01 sh600050 中国联通
2023-12-01 sh600051 宁波联合
2023-12-01 sh600052 东望时代
2023-12-01 sh600053 九鼎投资
2023-12-01 sh600054 黄山旅游
2023-12-01 sh600055 万东医疗
2023-12-01 sh600056 中国医药
2023-12-01 sh600057 厦门象屿
2023-12-01 sh600058 五矿发展
2023-12-01 sh600059 古越龙山
2023-12-01 sh600060 海信视像
2023-12-01 sh600061 国投资本
2023-12-01 sh600062 华润双鹤
2023-12-01 sh600063 皖维高新
2023-12-01 sh600064 南京高科
2023-12-01 sh600066 宇通客车
2023-12-01 sh600067 冠城大通
2023-12-01 sh600070 ST富润
2023-12-01 sh600071 凤凰光学
2023-12-01 sh600072 中船科技
2023-12-01 sh600073 上海梅林
2023-12-01 sh600075 新疆天业
2023-12-01 sh600076 康欣新材
2023-12-01 sh600078 ST澄星
2023-12-01 sh600079 人福医药
2023-12-01 sh600080 金花股份
2023-12-01 sh600081 东风科技
2023-12-01 sh600082 海泰发展
2023-12-01 sh600083 博信股份
2023-12-01 sh600084 中信尼雅
2023-12-01 sh600085 同仁堂
2023-12-01 sh600088 中视传媒
2023-12-01 sh600089 特变电工
2023-12-01 sh600094 大名城
2023-12-01 sh600095 湘财股份
2023-12-01 sh600096 云天化
2023-12-01 sh600097 开创国际
2023-12-01 sh600098 广州发展
2023-12-01 sh600099 林海股份
2023-12-01 sh600100 同方股份
2023-12-01 sh600101 明星电力
2023-12-01 sh600103 青山纸业
2023-12-01 sh600104 上汽集团
2023-12-01 sh600105 永鼎股份
2023-12-01 sh600106 重庆路桥
2023-12-01 sh600107 美尔雅
2023-12-01 sh600108 亚盛集团
2023-12-01 sh600109 国金证券
2023-12-01 sh600110 诺德股份
2023-12-01 sh600111 北方稀土
2023-12-01 sh600112 ST天成
2023-12-01 sh600113 浙江东日
2023-12-01 sh600114 东睦股份
2023-12-01 sh600115 中国东航
2023-12-01 sh600116 三峡水利
2023-12-01 sh600117 *ST西钢
2023-12-01 sh600118 中国卫星
2023-12-01 sh600119 长江投资
2023-12-01 sh600120 浙江东方
2023-12-01 sh600121 郑州煤电
2023-12-01 sh600123 兰花科创
2023-12-01 sh600125 铁龙物流
2023-12-01 sh600126 杭钢股份
2023-12-01 sh600127 金健米业
2023-12-01 sh600128 苏豪弘业
2023-12-01 sh600129 太极集团
2023-12-01 sh600130 波导股份
2023-12-01 sh600131 国网信通
2023-12-01 sh600132 重庆啤酒
2023-12-01 sh600133 东湖高新
2023-12-01 sh600135 乐凯胶片
2023-12-01 sh600136 *ST明诚
2023-12-01 sh600137 浪莎股份
2023-12-01 sh600138 中青旅
2023-12-01 sh600141 兴发集团
2023-12-01 sh600143 金发科技
2023-12-01 sh600148 长春一东
2023-12-01 sh600149 廊坊发展
2023-12-01 sh600150 中国船舶
2023-12-01 sh600151 航天机电
2023-12-01 sh600152 维科技术
2023-12-01 sh600153 建发股份
2023-12-01 sh600155 华创云信
2023-12-01 sh600156 华升股份
2023-12-01 sh600157 永泰能源
2023-12-01 sh600158 中体产业
2023-12-01 sh600159 大龙地产
2023-12-01 sh600160 巨化股份
2023-12-01 sh600161 天坛生物
2023-12-01 sh600162 香江控股
2023-12-01 sh600163 中闽能源
2023-12-01 sh600165 宁科生物
2023-12-01 sh600166 福田汽车
2023-12-01 sh600167 联美控股
2023-12-01 sh600168 武汉控股
2023-12-01 sh600169 太原重工
2023-12-01 sh600170 上海建工
2023-12-01 sh600171 上海贝岭
2023-12-01 sh600172 黄河旋风
2023-12-01 sh600173 卧龙地产
2023-12-01 sh600176 中国巨石
2023-12-01 sh600177 雅戈尔
2023-12-01 sh600178 东安动力
2023-12-01 sh600179 安通控股
2023-12-01 sh600180 瑞茂通
2023-12-01 sh600182 S佳通
2023-12-01 sh600183 生益科技
2023-12-01 sh600184 光电股份
2023-12-01 sh600185 格力地产
2023-12-01 sh600186 莲花健康
2023-12-01 sh600187 国中水务
2023-12-01 sh600188 兖矿能源
2023-12-01 sh600189 泉阳泉
2023-12-01 sh600190 锦州港
2023-12-01 sh600191 华资实业
2023-12-01 sh600192 长城电工
2023-12-01 sh600193 创兴资源
2023-12-01 sh600195 中牧股份
2023-12-01 sh600196 复星医药
2023-12-01 sh600197 伊力特
2023-12-01 sh600198 大唐电信
2023-12-01 sh600199 金种子酒
2023-12-01 sh600200 江苏吴中
2023-12-01 sh600201 生物股份
2023-12-01 sh600202 哈空调
2023-12-01 sh600203 福日电子
2023-12-01 sh600206 有研新材
2023-12-01 sh600207 安彩高科
2023-12-01 sh600208 新湖中宝
2023-12-01 sh600210 紫江企业
2023-12-01 sh600211 西藏药业
2023-12-01 sh600212 绿能慧充
2023-12-01 sh600213 亚星客车
2023-12-01 sh600215 派斯林
2023-12-01 sh600216 浙江医药
2023-12-01 sh600217 中再资环
2023-12-01 sh600218 全柴动力
2023-12-01 sh600219 南山铝业
2023-12-01 sh600220 江苏阳光
2023-12-01 sh600221 海航控股
2023-12-01 sh600222 太龙药业
2023-12-01 sh600223 福瑞达
2023-12-01 sh600225 卓朗科技
2023-12-01 sh600226 瀚叶股份
2023-12-01 sh600227 赤天化
2023-12-01 sh600228 返利科技
2023-12-01 sh600229 城市传媒
2023-12-01 sh600230 沧州大化
2023-12-01 sh600231 凌钢股份
2023-12-01 sh600232 金鹰股份
2023-12-01 sh600233 圆通速递
2023-12-01 sh600234 科新发展
2023-12-01 sh600235 民丰特纸
2023-12-01 sh600236 桂冠电力
2023-12-01 sh600237 铜峰电子
2023-12-01 sh600238 海南椰岛
2023-12-01 sh600239 云南城投
2023-12-01 sh600241 时代万恒
2023-12-01 sh600243 青海华鼎
2023-12-01 sh600246 万通发展
2023-12-01 sh600248 陕建股份
2023-12-01 sh600249 两面针
2023-12-01 sh600250 南纺股份
2023-12-01 sh600251 冠农股份
2023-12-01 sh600252 中恒集团
2023-12-01 sh600255 鑫科材料
2023-12-01 sh600256 广汇能源
2023-12-01 sh600257 大湖股份
2023-12-01 sh600258 首旅酒店
2023-12-01 sh600259 广晟有色
2023-12-01 sh600261 阳光照明
2023-12-01 sh600262 北方股份
2023-12-01 sh600265 ST景谷
2023-12-01 sh600266 城建发展
2023-12-01 sh600267 海正药业
2023-12-01 sh600268 国电南自
2023-12-01 sh600269 赣粤高速
2023-12-01 sh600271 航天信息
2023-12-01 sh600272 开开实业
2023-12-01 sh600273 嘉化能源
2023-12-01 sh600276 恒瑞医药
2023-12-01 sh600277 亿利洁能
2023-12-01 sh600278 东方创业
2023-12-01 sh600279 重庆港
2023-12-01 sh600280 中央商场
2023-12-01 sh600281 华阳新材
2023-12-01 sh600282 南钢股份
2023-12-01 sh600283 钱江水利
2023-12-01 sh600284 浦东建设
2023-12-01 sh600285 羚锐制药
2023-12-01 sh600287 江苏舜天
2023-12-01 sh600288 大恒科技
2023-12-01 sh600289 ST信通
2023-12-01 sh600290 *ST华仪
2023-12-01 sh600292 远达环保
2023-12-01 sh600293 三峡新材
2023-12-01 sh600295 鄂尔多斯
2023-12-01 sh600297 广汇汽车
2023-12-01 sh600298 安琪酵母
2023-12-01 sh600299 安迪苏
2023-12-01 sh600300 维维股份
2023-12-01 sh600301 华锡有色
2023-12-01 sh600302 标准股份
2023-12-01 sh600303 ST曙光
2023-12-01 sh600305 恒顺醋业
2023-12-01 sh600306 *ST商城
2023-12-01 sh600307 酒钢宏兴
2023-12-01 sh600308 华泰股份
2023-12-01 sh600309 万华化学
2023-12-01 sh600310 广西能源
2023-12-01 sh600312 平高电气
2023-12-01 sh600313 农发种业
2023-12-01 sh600315 上海家化
2023-12-01 sh600316 洪都航空
2023-12-01 sh600318 新力金融
2023-12-01 sh600319 亚星化学
2023-12-01 sh600320 振华重工
2023-12-01 sh600321 正源股份
2023-12-01 sh600322 津投城开
2023-12-01 sh600323 瀚蓝环境
2023-12-01 sh600325 华发股份
2023-12-01 sh600326 西藏天路
2023-12-01 sh600327 大东方
2023-12-01 sh600328 中盐化工
2023-12-01 sh600329 达仁堂
2023-12-01 sh600330 天通股份
2023-12-01 sh600331 宏达股份
2023-12-01 sh600332 白云山
2023-12-01 sh600333 长春燃气
2023-12-01 sh600335 国机汽车
2023-12-01 sh600336 澳柯玛
2023-12-01 sh600337 美克家居
2023-12-01 sh600338 西藏珠峰
2023-12-01 sh600339 中油工程
2023-12-01 sh600340 华夏幸福
2023-12-01 sh600343 航天动力
2023-12-01 sh600345 长江通信
2023-12-01 sh600346 恒力石化
2023-12-01 sh600348 华阳股份
2023-12-01 sh600350 山东高速
2023-12-01 sh600351 亚宝药业
2023-12-01 sh600352 浙江龙盛
2023-12-01 sh600353 旭光电子
2023-12-01 sh600354 敦煌种业
2023-12-01 sh600355 精伦电子
2023-12-01 sh600356 恒丰纸业
2023-12-01 sh600358 国旅联合
2023-12-01 sh600359 新农开发
2023-12-01 sh600360 华微电子
2023-12-01 sh600361 创新新材
2023-12-01 sh600362 江西铜业
2023-12-01 sh600363 联创光电
2023-12-01 sh600365 ST通葡
2023-12-01 sh600366 宁波韵升
2023-12-01 sh600367 红星发展
2023-12-01 sh600368 五洲交通
2023-12-01 sh600369 西南证券
2023-12-01 sh600370 三房巷
2023-12-01 sh600371 万向德农
2023-12-01 sh600372 中航机载
2023-12-01 sh600373 中文传媒
2023-12-01 sh600375 汉马科技
2023-12-01 sh600376 首开股份
2023-12-01 sh600377 宁沪高速
2023-12-01 sh600378 昊华科技
2023-12-01 sh600379 宝光股份
2023-12-01 sh600380 健康元
2023-12-01 sh600381 青海春天
2023-12-01 sh600382 广东明珠
2023-12-01 sh600383 金地集团
2023-12-01 sh600386 北巴传媒
2023-12-01 sh600387 ST海越
2023-12-01 sh600388 龙净环保
2023-12-01 sh600389 江山股份
2023-12-01 sh600390 五矿资本
2023-12-01 sh600391 航发科技
2023-12-01 sh600392 盛和资源
2023-12-01 sh600395 盘江股份
2023-12-01 sh600396 *ST金山
2023-12-01 sh600397 安源煤业
2023-12-01 sh600398 海澜之家
2023-12-01 sh600399 抚顺特钢
2023-12-01 sh600400 红豆股份
2023-12-01 sh600403 大有能源
2023-12-01 sh600405 动力源
2023-12-01 sh600406 国电南瑞
2023-12-01 sh600408 安泰集团
2023-12-01 sh600409 三友化工
2023-12-01 sh600410 华胜天成
2023-12-01 sh600415 小商品城
2023-12-01 sh600416 湘电股份
2023-12-01 sh600418 江淮汽车
2023-12-01 sh600419 天润乳业
2023-12-01 sh600420 国药现代
2023-12-01 sh600421 华嵘控股
2023-12-01 sh600422 昆药集团
2023-12-01 sh600423 柳化股份
2023-12-01 sh600425 青松建化
2023-12-01 sh600426 华鲁恒升
2023-12-01 sh600428 中远海特
2023-12-01 sh600429 三元股份
2023-12-01 sh600433 冠豪高新
2023-12-01 sh600435 北方导航
2023-12-01 sh600436 片仔癀
2023-12-01 sh600438 通威股份
2023-12-01 sh600439 瑞贝卡
2023-12-01 sh600444 国机通用
2023-12-01 sh600446 金证股份
2023-12-01 sh600448 华纺股份
2023-12-01 sh600449 宁夏建材
2023-12-01 sh600452 涪陵电力
2023-12-01 sh600455 博通股份
2023-12-01 sh600456 宝钛股份
2023-12-01 sh600458 时代新材
2023-12-01 sh600459 贵研铂业
2023-12-01 sh600460 士兰微
2023-12-01 sh600461 洪城环境
2023-12-01 sh600462 ST九有
2023-12-01 sh600463 空港股份
2023-12-01 sh600467 好当家
2023-12-01 sh600468 百利电气
2023-12-01 sh600469 风神股份
2023-12-01 sh600470 六国化工
2023-12-01 sh600475 华光环能
2023-12-01 sh600476 湘邮科技
2023-12-01 sh600477 杭萧钢构
2023-12-01 sh600478 科力远
2023-12-01 sh600479 千金药业
2023-12-01 sh600480 凌云股份
2023-12-01 sh600481 双良节能
2023-12-01 sh600482 中国动力
2023-12-01 sh600483 福能股份
2023-12-01 sh600486 扬农化工
2023-12-01 sh600487 亨通光电
2023-12-01 sh600488 津药药业
2023-12-01 sh600489 中金黄金
2023-12-01 sh600490 鹏欣资源
2023-12-01 sh600491 龙元建设
2023-12-01 sh600493 凤竹纺织
2023-12-01 sh600495 晋西车轴
2023-12-01 sh600496 精工钢构
2023-12-01 sh600497 驰宏锌锗
2023-12-01 sh600498 烽火通信
2023-12-01 sh600499 科达制造
2023-12-01 sh600500 中化国际
2023-12-01 sh600501 航天晨光
2023-12-01 sh600502 安徽建工
2023-12-01 sh600503 华丽家族
2023-12-01 sh600505 西昌电力
2023-12-01 sh600506 统一股份
2023-12-01 sh600507 方大特钢
2023-12-01 sh600508 上海能源
2023-12-01 sh600509 天富能源
2023-12-01 sh600510 黑牡丹
2023-12-01 sh600511 国药股份
2023-12-01 sh600512 腾达建设
2023-12-01 sh600513 联环药业
2023-12-01 sh600515 海南机场
2023-12-01 sh600516 方大炭素
2023-12-01 sh600517 国网英大
2023-12-01 sh600518 ST康美
2023-12-01 sh600519 贵州茅台
2023-12-01 sh600520 文一科技
2023-12-01 sh600521 华海药业
2023-12-01 sh600522 中天科技
2023-12-01 sh600523 贵航股份
2023-12-01 sh600525 长园集团
2023-12-01 sh600526 菲达环保
2023-12-01 sh600527 江南高纤
2023-12-01 sh600528 中铁工业
2023-12-01 sh600529 山东药玻
2023-12-01 sh600530 ST交昂
2023-12-01 sh600531 豫光金铅
2023-12-01 sh600533 栖霞建设
2023-12-01 sh600535 天士力
2023-12-01 sh600536 中国软件
2023-12-01 sh600537 亿晶光电
2023-12-01 sh600538 国发股份
2023-12-01 sh600539 狮头股份
2023-12-01 sh600540 新赛股份
2023-12-01 sh600543 *ST莫高
2023-12-01 sh600545 卓郎智能
2023-12-01 sh600546 山煤国际
2023-12-01 sh600547 山东黄金
2023-12-01 sh600548 深高速
2023-12-01 sh600549 厦门钨业
2023-12-01 sh600550 保变电气
2023-12-01 sh600551 时代出版
2023-12-01 sh600552 凯盛科技
2023-12-01 sh600556 天下秀
2023-12-01 sh600557 康缘药业
2023-12-01 sh600558 大西洋
2023-12-01 sh600559 老白干酒
2023-12-01 sh600560 金自天正
2023-12-01 sh600561 江西长运
2023-12-01 sh600562 国睿科技
2023-12-01 sh600563 法拉电子
2023-12-01 sh600565 迪马股份
2023-12-01 sh600566 济川药业
2023-12-01 sh600567 山鹰国际
2023-12-01 sh600568 ST中珠
2023-12-01 sh600569 安阳钢铁
2023-12-01 sh600570 恒生电子
2023-12-01 sh600571 信雅达
2023-12-01 sh600572 康恩贝
2023-12-01 sh600573 惠泉啤酒
2023-12-01 sh600575 淮河能源
2023-12-01 sh600576 祥源文旅
2023-12-01 sh600577 精达股份
2023-12-01 sh600578 京能电力
2023-12-01 sh600579 克劳斯
2023-12-01 sh600580 卧龙电驱
2023-12-01 sh600581 八一钢铁
2023-12-01 sh600582 天地科技
2023-12-01 sh600583 海油工程
2023-12-01 sh600584 长电科技
2023-12-01 sh600585 海螺水泥
2023-12-01 sh600586 金晶科技
2023-12-01 sh600587 新华医疗
2023-12-01 sh600588 用友网络
2023-12-01 sh600589 *ST榕泰
2023-12-01 sh600590 泰豪科技
2023-12-01 sh600592 龙溪股份
2023-12-01 sh600593 大连圣亚
2023-12-01 sh600594 益佰制药
2023-12-01 sh600595 中孚实业
2023-12-01 sh600596 新安股份
2023-12-01 sh600597 光明乳业
2023-12-01 sh600598 北大荒
2023-12-01 sh600599 ST熊猫
2023-12-01 sh600600 青岛啤酒
2023-12-01 sh600601 方正科技
2023-12-01 sh600602 云赛智联
2023-12-01 sh600603 广汇物流
2023-12-01 sh600604 市北高新
2023-12-01 sh600605 汇通能源
2023-12-01 sh600606 绿地控股
2023-12-01 sh600608 ST沪科
2023-12-01 sh600609 金杯汽车
2023-12-01 sh600610 中毅达
2023-12-01 sh600611 大众交通
2023-12-01 sh600612 老凤祥
2023-12-01 sh600613 神奇制药
2023-12-01 sh600615 丰华股份
2023-12-01 sh600616 金枫酒业
2023-12-01 sh600617 国新能源
2023-12-01 sh600618 氯碱化工
2023-12-01 sh600619 海立股份
2023-12-01 sh600620 天宸股份
2023-12-01 sh600621 华鑫股份
2023-12-01 sh600622 光大嘉宝
2023-12-01 sh600623 华谊集团
2023-12-01 sh600624 复旦复华
2023-12-01 sh600626 申达股份
2023-12-01 sh600628 新世界
2023-12-01 sh600629 华建集团
2023-12-01 sh600630 龙头股份
2023-12-01 sh600633 浙数文化
2023-12-01 sh600635 大众公用
2023-12-01 sh600636 国新文化
2023-12-01 sh600637 东方明珠
2023-12-01 sh600638 新黄浦
2023-12-01 sh600639 浦东金桥
2023-12-01 sh600640 国脉文化
2023-12-01 sh600641 万业企业
2023-12-01 sh600642 申能股份
2023-12-01 sh600643 爱建集团
2023-12-01 sh600644 乐山电力
2023-12-01 sh600645 中源协和
2023-12-01 sh600647 *ST同达
2023-12-01 sh600648 外高桥
2023-12-01 sh600649 城投控股
2023-12-01 sh600650 锦江在线
2023-12-01 sh600651 飞乐音响
2023-12-01 sh600653 申华控股
2023-12-01 sh600654 ST中安
2023-12-01 sh600655 豫园股份
2023-12-01 sh600657 信达地产
2023-12-01 sh600658 电子城
2023-12-01 sh600660 福耀玻璃

# Check Data Accuracy

In [23]:
def SQLSearch(s:str):
    conn = psycopg2.connect(host="localhost", database="yuzhuoran", user="postgres", password="YZRyzr010306!")
    cur = conn.cursor()
    conn.commit()
    conn.rollback()
    conn.autocommit = True
    cur.execute(s)
    col_names = [desc [0] for desc in cur.description]
    results = cur.fetchall()
    cur.close()
    return col_names,results

In [26]:
start_min = Current_Date + ' 09:30:00'
sql = "SELECT * from \"Trading\".Fact_Stock_Minute\
                where Minute_ID=" + str(GetMinuteID(start_min)) + ";"
col,res = SQLSearch(sql)
df = pd.DataFrame(res,columns=col)
df.tail()

               fsm_id  stock_id     minute_id  open   high    low  volume stock_name    turnover  close
0  430017202311270930    430017  202311270930  0.00  17.66  17.66    5655   星昊医药  9986482.00  17.66